### ISSUE TITLE
finishline.com - cannot add to cart

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1015]
https://www.finishline.com/store/product/adidas-originals-samba-casual-shoes/prod750640?styleId=B75807&colorId=001 - attempting to add to cart yields infinite spinner (2023-06-15).

Disabling `fingerprintingCanvas` mitigates.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
