### ISSUE TITLE
runtime checks prevents changing Google account profile image

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1023]
On Chrome, login and navigate to https://myaccount.google.com/personal-info. Attempt to change profile picture and a squashed bar shows up. Disabling protections allows profile image selector to show. (2023-06-19)

Due to runtimeChecks.

Asana: https://app.asana.com/0/1200277586140538/1204845017663717/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
