### ISSUE TITLE
maxymiser.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1030]
- https://us.etrade.com/home/welcome-back (2023-06-20)
  - site gets stuck loading
  - Asana: https://app.asana.com/0/1200277586140538/1204846434207957/f
  - requests required:
    - `service.maxymiser.net/cdn/etrade/js/mmcore.js`
- https://www.allegiantair.com/my-trips (2023-06-20)
  - page content is blank (doesn't show that you need to sign in)
  - requests required:
    - `service.maxymiser.net/api/us/allegiantair.com/fba06c/mmapi.js`
- as well as various reports for financial/banking sites

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
