### ISSUE TITLE
runtime checks rollout breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1035]
Breakage during runtime checks rollout:

- https://www.royalcaribbean.com/cruises?search=departurePort:MIA|startDate:2024-03-01~2024-05-31&sort=RECOMMENDED (2023-06-21)
  - causes severe slowdowns, site becomes less responsive
  - https://app.asana.com/0/0/1204208106954755/1204871761531589/f
- https://customer.concordgroupinsurance.com/ccp/login (2023-06-21)
  - problems logging in
  - https://app.asana.com/0/1200277586140538/1204844344074234/f
- https://customercenter.auto-owners.com/cp/ui/login (2023-06-21)
  - problems logging in
  - https://app.asana.com/0/1200277586140538/1204844344074234/f
- https://www.aoins.com/my.policy (2023-06-21)
  - problems logging in
  - https://app.asana.com/0/1200277586140538/1204844344074234/f
- https://mybell.bell.ca/Login (2023-06-21)
  - problems logging in 
  - https://app.asana.com/0/0/1204863914637254/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
