### ISSUE TITLE
certona.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1038]
- https://outlet.asics.com/gb/en-gb/gel-kayano-28/p/1011B189-403.html?size=7.5&width=Standard (2023-06-21)
  - "add to cart" has no effect
  - requests required:
    - `edge1.certona.net/cd/dd7aa8af/www.asics.com/scripts/resonance.js`
  - https://app.asana.com/0/0/1204670471114497/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
