### ISSUE TITLE
focus.de

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1043]
### Description of Breakage

- comment section does not open when clicked upon (last verified 2023-06-23)

### Tracker Requests breaking the site

1. `tags.focus.de` which CNAMES to `tags.focus.de.greylabeldelivery.com`

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

https://app.asana.com/0/1200277586140538/1204848164616711/f

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
