### ISSUE TITLE
nytimes.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1045]
- https://www.nytimes.com (2023-06-23)
  - cannot interact with nav bar (button doesn't cause anything to load when clicked)
  - https://app.asana.com/0/1200277586140538/1204887750184850/f
  - requests required:
    - `securepubads.g.doubleclick.net/tag/js/gpt.js` (can be blocked or unblocked - surrogate likely broken)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
