### ISSUE TITLE
Broken Site: livenation.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1053]
### Description of Breakage

bot detection

### Tracker Requests breaking the site

none

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
