### ISSUE TITLE
Broken Site: marksandspencer.com 

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1056]
### Description of Breakage

When trying to load my lastest credit card statement I recieved the following message.

Important Message
We are unable to deal with your request. Please try again later (888).

### Tracker Requests breaking the site

unknown

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by GuiltyDolphin** [comment]
Moving this to #794
