### ISSUE TITLE
Style-src content security policy prevents styletag injection

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1058]
This issue contains a collection of sites where we are unable to inject a style tag into the page due to the site's strict CSP. Attempting to inject a style tag on these sites shouldn't cause any real breakage, but it will trigger CSP reports (which we'd like to avoid).

- https://duckduckgo.com (last verified: 6/27/2023)
- https://github.com (last verified: 6/27/2023)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
