### ISSUE TITLE
cdnjs.cloudflare.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1066]
- https://kartor.eniro.se/ (2023-06-30)
  - map (i.e., full page) doesn't render
  - https://app.asana.com/0/1200277586140538/1204928062074300/f
  - requests required:
    - `cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js`
- 2000mules.com (2023-06-30)
  - Loading percentage hits 100% and the site does not proceed to display usual content.
  - requests required:
    - `cdnjs.cloudflare.com/ajax/libs/three.js/84/three.min.js`
- https://www.winnipegfreepress.com/local/city-will-try-to-fill-money-losing-ex-canada-post-office-576646662.html
  - Main text content on article does not load
  - requests required:
    - `cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/1.8.6/fingerprint2.min.js`
      - (note: 2023-06-30, presently unable to get this request to fire)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
