### ISSUE TITLE
Broken Site: express.co.uk

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1068]
### URLs affected

express.co.uk

### Description of Breakage

Comments ' section does not load under any news article

### Tracker Requests breaking the site

`cmp.quantcast.com` eg via `cmp.quantcast.com/choice/JYWDqeLS64fbt/www.express.co.uk/choice.js`

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

[_No response_](https://app.asana.com/0/0/1204924405961830/f)

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
