### ISSUE TITLE
Broken Site: Google sheets

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1072]
### URLs affected

https://docs.google.com/spreadsheets/u/0/

### Description of Breakage

Screen size fingerprint protection is running first by mistake and so we're not fixing the values properly.

### Tracker Requests breaking the site

None

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

https://app.asana.com/0/1177771139624306/1204944717262422/f

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
