### ISSUE TITLE
Broken Site: citizensbankonline.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1079]
### URLs affected

https://www4.citizensbankonline.com/efs/servlet/efs/default.jsp

### Description of Breakage

Reports of login issues

### Tracker Requests breaking the site

1. https://h.online-metrix.net/fp/sid_fp.html

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
