### ISSUE TITLE
Broken Site: bestbuy.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1083]
### URLs affected

https://www.bestbuy.com/identity/signin?token=tid%3Ae1b411ae-1c06-11ee-9521-12ae03d428e7

### Description of Breakage

The inability to close the google sign in pop-up, freezes the login/sign up element.
We need to add an exception so the pop-up is visible and the user can close it manually to be able to sign in/up

### Tracker Requests breaking the site

Google account pop up

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
