### ISSUE TITLE
Broken Site: paramountplus.com 

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1085]
### URLs affected

paramountplus.com 

### Description of Breakage

Videos don't play

### Tracker Requests breaking the site

unknown

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
