### ISSUE TITLE
Broken Site: wcvb.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1088]
### URLs affected

https://www.wcvb.com/article/blueberries-have-joined-green-beans-in-this-years-dirty-dozen-list/44441224

Other sites using the same video player that have the same issue:
[
  "4029tv.com",
  "kcci.com",
  "kcra.com",
  "ketv.com",
  "kmbc.com",
  "koat.com",
  "koco.com",
  "ksbw.com",
  "mynbc5.com",
  "wapt.com",
  "wbaltv.com",
  "wcvb.com",
  "wdsu.com",
  "wesh.com",
  "wgal.com",
  "wisn.com",
  "wlky.com",
  "wlwt.com",
  "wmtw.com",
  "wmur.com",
  "wpbf.com",
  "wtae.com",
  "wvtm13.com",
  "wxii12.com",
  "wyff4.com"
]

### Description of Breakage

Videos don't load because of a tracker we block

### Tracker Requests breaking the site

https://c.amazon-adsystem.com/aax2/apstag.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
