### ISSUE TITLE
YouTube shorts not working well with Duck Player

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1091]
When clicking on YouTube "shorts" from the YouTube homepage, Duck Player loads in full, preventing the use of YouTube shorts video scrolling.

https://app.asana.com/0/1200277586140538/1204993779631302/f / https://app.asana.com/0/1201048563534612/1204993915251837/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
