### ISSUE TITLE
techlab-cdn breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1094]
- https://www.jcrew.com/uk/m/mens/categories/clothing/shirts/broken-in-oxford/broken-in-organic-cotton-oxford-shirt/MP461?display=standard&fit=Classic&color_name=university-stripe-rain&colorProductCode=BE996 (2023-07-11)
  - reviews don't show
  - https://app.asana.com/0/1200277586140538/1204996892810398/f
  - requests required:
    - `p11.techlab-cdn.com/collect`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
