### ISSUE TITLE
Broken Site: www.derstandard.at/

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1101]
### URLs affected

www.derstandard.at
https://www.derstandard.at/story/3000000178430/w
https://www.derstandard.at/story/3000000178509/italiener-sinner-erstmals-bei-einem-grand-slam-turnier-im-halbfinale
https://www.derstandard.at/story/3000000178357/hei%C3%9Feste-woche-der-messgeschichte-60000-hitzetote
https://www.derstandard.at/story/3000000178470/nehammer-haelt-kickl-fuer-ein-siche

### Description of Breakage

DuckDuckGo is seen as an adblocker and users are requested to deactivate it to keep reading.
That notification does not always get triggered straight away by the site and may require couple of article reads before it shows up.
Here the site is trying to display an html element that's hidden. To mitigate we need to make an exception so this domain isn't under element hiding scope.

### Tracker Requests breaking the site

NA

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
