### ISSUE TITLE
Broken Site: 

### ISSUE THREAD

**Issue by codeguy12345** [duckduckgo/privacy-configuration#1103]
### URLs affected

https://onlinebanking.mtb.com
https://secure.wilmingtontrust.com
https://nao.mtb.com
https://auth.mtb.com

### Description of Breakage

As others have mentioned, these sites do not work with the newest update. I have to disable runtime checks. Per other posts, I am requesting that mtb.com and wilmingtontrust.com sites be added to the exceptions.

### Tracker Requests breaking the site

runtimechecks

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

This is happening on the duckduckgo privacy extension for chrome.

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by jonathanKingston** [comment]
This runtimeChecks feature is currently globally disabled.


- Can you explain more what is happening on those sites? Is there anything in the browser console?
- Does disabling the protections through the extension prevent the issue? (see screenshot, the icon might be hidden for you)

<img width="386" alt="image" src="https://github.com/duckduckgo/privacy-configuration/assets/338988/f58e2757-1c70-4443-9191-38d33fe52997">

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
