### ISSUE TITLE
Batch of site breakage fixes

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1107]
A thorough review of our blocklist and user-reported site breakages turned up quite a few cases where we are blocking requests that aren't actually trackers, and provide real site functionality. This is happening because these requests have a profile that appears similar to trackers--they might set a cookie, touch localStorage, or hit browser APIs commonly used by fingerprinting scripts--so they are flagged as such by our crawler.

### Request patterns
- att.com/scripts/att_common.js
  - fraud prevention script used on directv.com, blocking interferes with login
- aweber.com/form/*
  - newsletter sign up form, can be seen on growweedeasy.com
- cloudflare.com:
  - cdnjs.cloudflare.com/cdn-cgi/scripts/.*/cloudflare-static/rocket-loader.min.js
  - cdnjs.cloudflare.com/ajax/libs/leaflet/
  - cdnjs.cloudflare.com/ajax/libs/vue/
  - cdnjs.cloudflare.com/ajax/libs/video.js/
  - cdnjs.cloudflare.com/ajax/libs/headjs/
  - cdnjs.cloudflare.com/ajax/libs/three.js/
  - cdnjs.cloudflare.com/ajax/libs/hola_player/
  - https://github.com/duckduckgo/privacy-configuration/issues/1066
  - cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/
- crisp.chat
  - chat widget, can be seen on umc.org/en/who-we-are/ask-the-umc-faqs
- cudasvc.com/url, proofpoint.com/v2/url
  - enterprise link protection services
- driftt.com
  - chat widget, can be seen on asana.com
- flowplayer.org
  - embedded video player
- memberful.com/embed.js, patreon.com/becomePatronButton.bundle.js
  - embedded subscription widgets
- redditstatic.com/shreddit, embed.reddit.com, gql.reddit.com
  - embedded reddit comments, galleries,  and widgets
  - https://github.com/duckduckgo/privacy-configuration/issues/369
- scene7.com/s7viewersdk, scene7.com.edgekey.net/s7viewersdk
  - embedded video player
  - https://github.com/duckduckgo/privacy-configuration/issues/356
- shop.app/pay/session
  - used on shopify sites to set up session for payment flow
- shopifyapps.com/locale_bar/script.js, shopifyapps.com/selectors/script.js
  - used on shopify sites to autopopulate country & currency
- snapkit.com/js/v1/create.js
  - used to integrate a variety of snapchat features
- theplatform.com
  - embedded video player, can be seen on comcasttechnologysolutions.com
  - https://github.com/duckduckgo/privacy-configuration/issues/512
- tidiochat.com
  - embedded chat widget
- voxmedia.com/sso/unison_request
  - related to auth on sites that embed content from vox
- zencdn.net
  - embedded video player
- zip.co/v1/quadpay.js
  - embedded payment service, can be seen on solgaard.co
- action.crunch11.com
  - login page for ilovepho.menu11.com

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
