### ISSUE TITLE
Broken Site: my.freenom.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1109]
### URLs affected

https://my.freenom.com/clientarea.php

### Description of Breakage

Facebook click to load element blocks the 'sign in with Google' button.

### Tracker Requests breaking the site

Click to play must be disabled.

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
