### ISSUE TITLE
omappapi.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1113]
- https://www.dogfoodadvisor.com/dog-food-recall-alerts/ (2023-07-13)
  - main content e-mail box doesn't render, leaving a blank space
  - https://app.asana.com/0/1200277586140538/1205015459471516/f
  - requests required:
    - `omappapi.com` (various)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
