### ISSUE TITLE
Broken Site: bleedcubbieblue.com"

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1115]
### URLs affected

https://www.bleedcubbieblue.com/2023/7/13/23793351/chicago-cubs-bcb-after-dark-trade-deadline-selloff-wins

### Description of Breakage

comments are hidden by another selector since the comments sections are inside of a shadow dom container and not a div.

### Tracker Requests breaking the site

none - selector override is needed for 'ad_unit'

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
