### ISSUE TITLE
googleoptimize.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1117]
- https://www.motherdenim.com/ (2023-07-13)
  - https://app.asana.com/0/0/1205010991570492/f
  - site is blank for 4-5 seconds before loading
  - requests required:
    - `www.googleoptimize.com/optimize.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
