### ISSUE TITLE
adthrive broken videos

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1122]
### URLs affected

https://www.gardeningknowhow.com/ornamental/bulbs/iris/potted-iris-care.htm
https://adamtheautomator.com/how-to-use-youtube-dl/
https://packhacker.com/travel-gear/topo-designs/square-bag/

### Description of Breakage

Missing videos

### Tracker Requests breaking the site

adthrive.com

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
