### ISSUE TITLE
Broken Site: cmp.quantcast.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1125]
### URLs affected

https://www.hulldailymail.co.uk/news/hull-east-yorkshire-news/bransholme-nan-devastated-after-midnight-8606665

https://www.dailystar.co.uk/real-life/randy-pensioner-83-splits-egyptian-30494313

https://www.liverpoolecho.co.uk/news/cost-of-living/dwp-says-many-people-could-27341657

### Description of Breakage

Videos don't play when we block quantcast. 
This is to expand the exemption we already have to cover more sites using quantcast.

### Tracker Requests breaking the site

cmp.quantcast.com

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
