### ISSUE TITLE
Broken Site: citi.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1129]
### URLs affected

citi.com

### Description of Breakage

broken logins

### Tracker Requests breaking the site

unknown

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
