### ISSUE TITLE
Broken Site: info.stimmoney.com

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#1137]
### URLs affected

info.stimmoney.com

### Description of Breakage

Page redirects several times before saying "Something went wrong".

### Tracker Requests breaking the site

None

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Caused by customUserAgent

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
