### ISSUE TITLE
Broken Site: crunchyroll.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1140]
### URLs affected

https://www.crunchyroll.com/watch/GPWUK51VP/awakening-and-another-world

### Description of Breakage

Video can't play and break because we block an ad streaming tracker meant to play at the start of the video

### Tracker Requests breaking the site

pubads.g.doubleclick.net/gampad/ads

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
