### ISSUE TITLE
cxense.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1143]
- https://www.bizjournals.com/phoenix/news/2023/07/21/valley-contractors-extreme-heat-job-site.html
  - Subscribe button missing from page
- https://www.marketwatch.com/
  - Subscribe button missing from page
- wsj.com
  - Opinion section article elements do not render. Note that Firefox Enhanced Tracking Protection may prevent mitigation from succeeding on Firefox.
- Same issue is impacting quite a few other sites as well

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
