### ISSUE TITLE
Broken Site: hulu.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1145]
### URLs affected

hulu.com

### Description of Breakage

unsupported browser

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
