### ISSUE TITLE
Broken Site: support.norton.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1156]
### URLs affected

https://support.norton.com/sp/en/us/home/current/contact?

### Description of Breakage

By blocking a tracker we prevent the chat feature to open

### Tracker Requests breaking the site

https://analytics.analytics-egain.com/onetag/EG94020756

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
