### ISSUE TITLE
act.alz.org

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1158]
### URLs affected

[act.alz.org](act.alz.org) 

### Description of Breakage

page doesn't load (too many redirects) - this is due to SSL upgrade -> https

### Tracker Requests breaking the site

NA

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
