### ISSUE TITLE
Amazon Prime Video breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1162]
- https://primevideo.com, https://www.amazon.com/Amazon-Video/* (last verified 2023-07-28)
  - video won't play (DRM)
  - due to eme permissions not enabled
  - https://app.asana.com/0/1200223097357040/1205132730961921/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
