### ISSUE TITLE
sinclair sites: screen turning blank

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1173]
- https://upnorthlive.com/ (2023-08-01)
  - screen turns blank shortly after loading
  - https://app.asana.com/0/1200277586140538/1205170786543366/f
  - this is due to the GPT surrogate

Multiple properties in https://sbgi.net/tv-stations/ are affected.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
