### ISSUE TITLE
pardot.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1180]
- https://www.linwoodhomes.com/contact/ (2023-08-04)
  - contact form doesn't show
  - requests required:
    - `go.pardot.com/`
- #625
- https://www.hopeforpaws.org/ (2023-08-04)
  - sign-up popup form doesn't render
  - `go.pardot.com`
- https://go.asrw.com.au/resource-portfolio (2023-08-04)
  - background image doesn't render
  - `storage.pardot.com`
- https://go.coptrz.com/coptrz-dji-air-3-brochure (2023-08-04)
  - PDF page doesn't load
  - `storage.pardot.com`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
