### ISSUE TITLE
doubleclick.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1185]
- https://www.history.com/topics/us-presidents/nixons-secret-plan-to-end-vietnam-war-video (2023-08-04)
  - video doesn't play (DAI error)
  - https://app.asana.com/0/1200277586140538/1205212065118174/f
  - `pubads.g.doubleclick.net/ondemand/hls/content/2540938/vid/21109727/*`
- https://www.plus.fifa.com/en/content/w57-v-w58-semi-finals-fifa-womens-world-cup-australia-and-new-zealand-2023-extended-highlights/9622ec8c-564f-40cf-b6fa-56a2db4d2b73 (2023-08-15)
  - adwall triggers
  - https://app.asana.com/0/1200277586140538/1205271473837648/f
  - `pubads.g.doubleclick.net/gampad/ads`
- https://www.nhl.com/video/minnesota-wild-season-preview/t-277350912/c-18369806 (2023-08-15)
  - after clicking to play, video shows a spinner and never loads
  - https://app.asana.com/0/1200223097357040/1201208127782807/f
  - `pubads.g.doubleclick.net/gampad/ads`
- https://www.viki.com/videos/1237531v (2023-08-15)
  - after clicking to play, adwall shows after a couple of seconds
  - https://app.asana.com/0/1200223097357040/1202509100110253/f
  - `pubads.g.doubleclick.net/gampad/ads`
- https://www.goplay.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-s19/de-slimste-mens-ter-wereld-s19-aflevering-33
  - video won't play
  - https://app.asana.com/0/1200277586140538/1201530709463533/f
  - `https://securepubads.g.doubleclick.net/tag/js/gpt.js`
- https://10play.com.au/masterchef/episodes/season-14/episode-28/tpv220524qpbdz
  - video won't play
  - https://app.asana.com/0/1200277586140538/1202577978579494/f
  - `pubads.g.doubleclick.net/ondemand/hls/content/2489270/vid/9000000000046383/streams`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
