### ISSUE TITLE
qualtrics.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1196]
- https://lms.ecornell.com/courses/1650434/pages/activity-weighting-performance-metrics (last verified: 2023-08-04)
  - Blocking cornell.qualtrics.com/SE causes iframe to not load
  - A dozen other requests to qualtrics.com are initiated to load the iframe
  - This is likely responsible for other reports of online course breakage that we haven't been able to test

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
