### ISSUE TITLE
Broken Site: walmart.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1198]
### URLs affected

walmart.com

### Description of Breakage

redirects to login page

### Tracker Requests breaking the site

none

### Affected Platforms

- [x] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

caused by gpc

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
