### ISSUE TITLE
Broken Site: crunchynihongo.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1201]
### URLs affected

crunchynihongo.com

### Description of Breakage

Doesn't load

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

User agent

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
