### ISSUE TITLE
Broken Site: 9to5mac.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1204]
### URLs affected

9to5mac.com

### Description of Breakage

light/dark mode toggle is broken

### Tracker Requests breaking the site

https://cdn.viglink.com/api/vglnk.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
