### ISSUE TITLE
Broken Site: rte.ie

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1217]
### URLs affected

https://www.rte.ie/news/player/

### Description of Breakage

requires user's drm permission to play the live news video

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
