### ISSUE TITLE
Broken Site: cnn.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1220]
### URLs affected

https://www.cnn.com/videos/cnn
https://www.cnn.com/videos/us/2023/07/23/doc-ron-1-gligo-beach-dna-hair-actws-vpx.cnn

### Description of Breakage

On Android, an article's video does not load protection ON/OFF
On MacOS, there's a delay between audio and video where audio starts couple of seconds before the audio privacy protection ON/OFF

### Tracker Requests breaking the site

To mitigate android, add it to the eme/DRM exception list
To mitigate MacOS, unblock [amazon-adsystem.com/aax2/apstag.js](http://amazon-adsystem.com/aax2/apstag.js)

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
