### ISSUE TITLE
boldapps.net breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1222]
- https://www.frogmouthclothing.com/products/perfect-scrimmage-top (last verified 2023-08-17)
  - form missing from product page, need to unblock https://option.boldapps.net/js/options.js
  - we've had quite a few reports for [others sites](https://github.com/duckduckgo/tracker-radar/blob/main/domains/US/boldapps.net.json#L244) where we saw this request, likely for the same issue.

- https://www.pixelempire.com/products/clue-scott-the-woz-edition
  - most of page doesn't load, requires unblocking https://mc.boldapps.net/install_assets/bold.multicurrency.js
  - likely breaking other small sites so better to unblock on all domains

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
