### ISSUE TITLE
Broken Site: airbnb.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1224]
### URLs affected

https://www.airbnb.com/s/Richmond--Virginia--United-States/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2023-09-01&monthly_length=3&price_filter_input_type=2&price_filter_num_nights=2&channel=EXPLORE&search_type=user_map_move&date_picker_type=calendar&checkin=2023-10-13&checkout=2023-10-15&children=1&adults=5&source=structured_search_input_header&query=Richmond%2C%20VA&zoom_level=12.172809671723735&place_id=ChIJ7cmZVwkRsYkRxTxC4m0-2L8&ne_lat=37.64960340015052&ne_lng=-77.39414424915259&sw_lat=37.46489951130762&sw_lng=-77.57908731014817&zoom=12.172809671723735&search_by_map=true

### Description of Breakage

map on airbnb does not load properly on MacOS when protection is ON because of fingerprinting-hardware. An exception was added to the macos-override file

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
