### ISSUE TITLE
Broken Site: kleen-ritecorp.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1231]
### URLs affected

https://www.kleen-ritecorp.com/p-71063-250-gallon-horizontal-above-ground-propane-tank-asme.aspx

### Description of Breakage

Page is blank with protection ON

### Tracker Requests breaking the site

monetate.net

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
