### ISSUE TITLE
Element hiding JSE's

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1236]
### URLs affected

https://duckduckgo.com

### Description of Breakage

We're getting an influx on Firefox of JavaScript exceptions but without the ability to reproduce currently. The errors are coming from the element hiding feature which should have no effect on our own site anyway so disabling probably should have been the default anyway.

### Tracker Requests breaking the site

None

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
