### ISSUE TITLE
Broken Site: dtaconnect.eohhs.mass.gov

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1239]
### URLs affected

https://dtaconnect.eohhs.mass.gov/ 

### Description of Breakage

Page loads indefinitely

### Tracker Requests breaking the site

1. https://api.ipify.org/

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
