### ISSUE TITLE
Broken Site: allocine.fr

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1241]
### URLs affected

https://www.allocine.fr/article/fichearticle_gen_carticle=1000038282.html

### Description of Breakage

If a user does not accept all cookies, some features can't be run (eg streaming trailers). allocine.fr needs to be added to autoconsent exemption list so CPM does not run on the site.

### Tracker Requests breaking the site

None

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
