### ISSUE TITLE
Broken Site: isra.org

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1245]
### URLs affected

https://isra.org/litigation/

### Description of Breakage

Click-To-Load takes up the site's content space. this site needs to be added to CTL exception list.

### Tracker Requests breaking the site

None

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
