### ISSUE TITLE
Broken Site: motorsport.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1250]
### URLs affected

https://www.motorsport.com/f1/news/haas-retains-magnussen-and-hulkenberg-for-2024-f1-season/10510756/

### Description of Breakage

[motorsport.com](https://motorsport.com/) forces users to accept analytics cookies to access the site's content. Otherwise it triggers an ad blocker banner.
On platforms where CPM is implemented this banner is automatically triggered. We need to turn off CPM for this domain.

### Tracker Requests breaking the site

None

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
