### ISSUE TITLE
Broken Site: wildrivers.lostcoastoutpost.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1252]
### URLs affected

wildrivers.lostcoastoutpost.com

### Description of Breakage

Ad block banner triggered because of blocking a tracker

### Tracker Requests breaking the site

c.amazon-adsystem.com/aax2/apstag.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
