### ISSUE TITLE
Broken Site: myaccountaccess.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1253]
### URLs affected

https://www.myaccountaccess.com/onlineCard/login.do

### Description of Breakage

Page does not load if the GPC signal is set.

### Tracker Requests breaking the site

GPC.

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
