### ISSUE TITLE
Broken Site: m.facebook.com

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#1258]
### URLs affected

m.facebook.com

### Description of Breakage

Facebook stories videos fail to play on Android.
![facebook_stories](https://github.com/duckduckgo/privacy-configuration/assets/3471025/b27733d5-99ab-44c3-82aa-cc9b1723a830)

### Tracker Requests breaking the site

Custom user agent causing the issue.

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
