### ISSUE TITLE
Banks with reported login issues

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1265]
### URLs affected

'fidelity.com',
 'americanexpress.com',
 'capitalone.com',
 'marcus.com'
 'bankofamerica.com',
 'wellsfargo.com',
 'usbank.com',
 'citizensbankonline.com',
 'sofi.com',
 'regions.com',
 'usaa.com',
 'boh.com',
 'santander.com.br',
 'pnc.com',
 'edwardjones.com',
 'ally.com',
 'metrobank.com.ph',
 'key.com',
 'synchronybank.com', 
 'oldglorybank.com',
 'santander.com.mx',
 'secureinternetbank.com',
 'bankfirst.com.au',
 'fnbo.com',
 'salliemae.com',
'bnc.bank',
'kanza.bank',
'prosperity.bank',
'firstwestern.bank',
'penncrest.bank',
'northwest.bank',
'bell.bank',
'dollar.bank',
'dellsbank.bank',
'rcbbank.bank',
'ebt.bank',
'mybct.bank',
'wells.bank',
'365.bank',
'atom.bank',
'ibanking-services.com'
'bmo.com',
'tsb.co.uk'

### Description of Breakage

Collecting a list of banks that we have reports of login issues

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
