### ISSUE TITLE
Tracker breakage: klarnaservices.com subdomains

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1266]
### URLs affected

https://boxlunch.com/
https://www.eadobikeco.com/
https://www.libertybibs.com/YB790.html
brooksrunning.com
joann.com

### Description of Breakage

A few shopping sites break because of some klarna' subdomains being blocked. We think more sites are being broken by these so instead of unblocking the tracker on those exact known domains and to prevent a breakage spike we chose to unblock 3 trackers on all domains.

### Tracker Requests breaking the site

1. na-library.klarnaservices.com/lib.js
2. eu-library.klarnaservices.com/lib.js
3. osm.library.klarnaservices.com/lib.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
