### ISSUE TITLE
Broken Site: dangerousminds.net

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1270]
### URLs affected

https://dangerousminds.net/articles

### Description of Breakage

ad wall banner triggered due to a tracker being blocked

### Tracker Requests breaking the site

htlbid.com/v3/dangerousminds.net/htlbid.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
