### ISSUE TITLE
Broken Site: reddit.com

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#1272]
### URLs affected

reddit.com

https://github.com/duckduckgo/privacy-configuration/assets/3471025/bf1b072e-0833-4a0c-a0ea-0bc137d5ffb2

### Description of Breakage

Menu flickers and doesn't open.

### Tracker Requests breaking the site

Custom user agent causing the issue.

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by sammacbeth** [comment]
I can't reproduce this anymore with the exception removed. I'll revert the mitigation.
