### ISSUE TITLE
Broken Site: kidsguide.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1277]
### URLs affected

https://thekidsguide.com/choose-trump/

### Description of Breakage

an input form is missing because we're blocking a klaviyo tracker

### Tracker Requests breaking the site

https://static.klaviyo.com/onsite/js/klaviyo.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by icodebyamanda** [comment]
List of domains unblocked:
- kidsguide.com
- urbanebikes.com
- essentialpraxis.com

**Comment by muodov** [comment]
Added more domains:
- muc-off.com
- paria.cc

**Comment by icodebyamanda** [comment]
Added more domains:
- combustion.inc

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
