### ISSUE TITLE
Broken Site: polygon.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1280]
### URLs affected

https://www.polygon.com/23844183/gran-turismo-movie-jann-mardenborough-interview-kenny-g#comments

### Description of Breakage

Comments are hidden

### Tracker Requests breaking the site

`elementHiding` feature

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
