### ISSUE TITLE
Broken Site: verizon.com

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#1282]
### URLs affected

https://www.verizon.com/switch-to-verizon/check-status/

### Description of Breakage

Captcha does not show (A captcha should be visible where the red box is).

![verizon](https://github.com/duckduckgo/privacy-configuration/assets/3471025/4af6d53e-45b9-45d1-a5b5-e5cc2b0a6a78)

### Tracker Requests breaking the site

GPC causing the issue.

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
