### ISSUE TITLE
Broken Site: andieswim.com

### ISSUE THREAD

**Issue by shakyShane** [duckduckgo/privacy-configuration#1285]
### URLs affected

https://andieswim.com/en-gb/pages/fit-finder

### Description of Breakage

Page content is missing - there should be a quiz

### Tracker Requests breaking the site

- www.lightboxcdn.com/vendor/c605dbd7-cbfb-4e9b-801e-387b0656384c/user.js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

I only tested the 3 browsers ticked, but assuming it's the same for all

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
