### ISSUE TITLE
Tracker Breakage: geoip-js.com

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1288]
- Sites impacted: https://www.yourrewardcard.com/
- Requests required to load: https://geoip-js.com/js/apis/geoip2/v2.1/geoip2.js 

- https://www.fathomevents.com/events/back-to-the-future-day/ (2023-10-19)
  - https://app.asana.com/0/1200277586140538/1205751898183597/f
  - "Get Tickets" button doesn't load selection screen after clicking (just shows loading)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
