### ISSUE TITLE
Broken Site: accounts.google.com

### ISSUE THREAD

**Issue by shakyShane** [duckduckgo/privacy-configuration#1295]
### URLs affected

any google login flows, on macOS Catalina 

### Description of Breakage

<img width="634" alt="image" src="https://github.com/duckduckgo/privacy-configuration/assets/1643522/cad18dee-01a8-4681-bca2-ca6ff49ebfba">

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

Works when we disable `referrer` feature.

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
