### ISSUE TITLE
Broken Site: paypal.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1303]
### URLs affected

https://paypal.com

### Description of Breakage

The "Manage your cookie settings" dialog can sometimes appear in a loop.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [X] Windows Browser

### Other Details

Disabling the automatic cookie management feature fixes the problem.

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
