### ISSUE TITLE
Broken Site: goodrx.com

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#1305]
### URLs affected

https://goodrx.com

### Description of Breakage

Site loads and then shows a blanks screen.

![goodrx copy](https://github.com/duckduckgo/privacy-configuration/assets/3471025/a268aa71-865b-48f9-a71b-95f22fbffe3e)

### Tracker Requests breaking the site

Custom user agent causing the issue.

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
