### ISSUE TITLE
Broken Site: Asana.com

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1309]
### URLs affected

https://asana.com

### Description of Breakage

Autofill in Firefox is causing site slowdown warnings.

### Tracker Requests breaking the site

.

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
