### ISSUE TITLE
Broken Site: booking.com

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#1317]
### URLs affected

https://booking.com

### Description of Breakage

Map and filter buttons don't work on Android

### Tracker Requests breaking the site

Caused by custom user agent

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Adding an exception to `omitVersionSites` fixes the issue

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
