### ISSUE TITLE
Broken Site: theverge.com

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1326]
### URLs affected

https://www.theverge.com/

### Description of Breakage

Homepage redirects to reddit due to embedded content

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Issue caused by `trackingParameters` feature

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
