### ISSUE TITLE
Broken Site: pch.com

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1344]
### URLs affected

https://lotto.pch.com/onboarding

### Description of Breakage

Various issues with games loading

### Tracker Requests breaking the site

1. https://sts.eccmp.com/sts/scripts/conversen-SDK.js
2. https://apps.rokt.com/wsdk/integrations/snippet.js
3. https://tags.tiqcdn.com/utag/pch/*

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
