### ISSUE TITLE
Broken Site: oracle.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1353]
### URLs affected

https://www.oracle.com/cloud/cloud-native/

### Description of Breakage

Videos do not load

### Tracker Requests breaking the site

1. `tags.tiqcdn.com/utag/tiqapp/utag.v.js`

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
