### ISSUE TITLE
Broken Site: peacocktv.com

### ISSUE THREAD

**Issue by kdzwinel** [duckduckgo/privacy-configuration#1356]
### URLs affected

peacocktv.com

### Description of Breakage

We are getting user reports from Android that peacocktv.com is experiencing playback issues.

### Tracker Requests breaking the site

No requests, it's an EME issue

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
