### ISSUE TITLE
Duckduckgo blocking Digioh

### ISSUE THREAD

**Issue by keithsibson** [duckduckgo/privacy-configuration#136]
Digioh is a JavaScript tag that provides tools for site owners to do newsletter signups, content walls, and product recommendation widgets on their site. Duckduckgo is blocking the Digioh CDN domain www.lightboxcdn.com, which causes sites not to function correctly. Two examples: 

https://www.adweek.com - premium content wall does not function
https://powerstep.com/pages/insole-finder - insole finder does not function

There are hundreds of sites that are (to a greater or lesser degree) functionally broken by this blocking. Can we please add an exception for www.lightboxcdn.com?

**Comment by sammacbeth** [comment]
I would look at trying to reduce the calls to such APIs to as few as possible - our fingerprinting detection calculates the [likelihood](https://github.com/duckduckgo/tracker-radar/blob/main/build-data/generated/api_fingerprint_weights.json) that each API is used for fingerprint and then generates a score based on the set used. Therefore, using fewer APIs reduces the likelihood your script will be blocked for fingerprinting.

For your use-case, it seems unlikely that you need to check the client's battery level (`Navigator.prototype.getBattery`), screen colorDepth, the mimeTypes recognised by the browser, the exact device orientation in degrees (`DeviceOrientationEvent.prototype.alpha`), nor do you need to check all of cookies, localStorage and indexedDB. If DeviceAtlas are doing all this automatic, you could perhaps ask them to not eagerly check all these APIs, or look for a less invasive alternative.
