### ISSUE TITLE
zopim.com chat widget blocked

### ISSUE THREAD

**Issue by kdzwinel** [duckduckgo/privacy-configuration#1360]
### URLs affected

widget-mediator.zopim.com serves support cha widget on many sites: https://slayterdev.github.io/tracker-radar-wiki/domains/zopim.com.html . 

### Description of Breakage

Chat does not load.

### Tracker Requests breaking the site

1. go to https://account.ui.com/supportform
2. login
3. try to start chat with support

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

and ryanair.com/pl/pl/lp/chat (2023-10-17). https://app.asana.com/0/1200277586140538/1205698706260564/f

**Comment by GuiltyDolphin** [comment]
and also on https://www.ryanair.com/pl/pl/lp/chat

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
