### ISSUE TITLE
Broken Site: top streaming sites android exception 

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1363]
### URLs affected

[disneyplus.com](https://disneyplus.com/)
[hulu.com](https://hulu.com/)
[plus.espn.com](https://plus.espn.com/) 
[netflix.com](https://netflix.com/) 
[paramountplus.com](https://paramountplus.com/) 
[tv.apple.com](https://tv.apple.com/) 
[curiositystream.com](https://curiositystream.com/) 
[starz.com](https://starz.com/) 
[dazn.com](https://dazn.com/) 
crunchyroll.com
[funimation.com](https://funimation.com/) 
[mubi.com](https://mubi.com/) 
crave.ca 
[britbox.com](https://britbox.com/)
[dailywire.com](https://dailywire.com/) 
fubo.tv 
acorn.tv 
[shudder.com](https://shudder.com/)
music.amazon.com 
[youtube.com](https://youtube.com/)

### Description of Breakage

Adding eme/drm exceptionstop streaming sites on android.

### Tracker Requests breaking the site

Not a tracker. DRM/EME functionality.

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
