### ISSUE TITLE
Broken Site: pocketbook.digital

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1365]
### URLs affected

https://cloud.pocketbook.digital/browser/en

### Description of Breakage

Page is blank

### Tracker Requests breaking the site

None

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Injecting a stylesheet for element hiding seems to be the source of the page going blank.

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
