### ISSUE TITLE
Broken Site: nascar.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1373]
### URLs affected

nascar.com

### Description of Breakage

Most content on the page is missing

### Tracker Requests breaking the site

lightboxcdn.com user.js

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
