### ISSUE TITLE
consent opt-out sites

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1377]
Some sites can contact third parties to try and perform opt-outs on the user's behalf.

To function, these sites need to be able to make requests to a variety of third parties, and may need to set opt-out cookies (i.e., need `contentBlocking` and `cookie` disabled).

- https://optout.networkadvertising.org/ (2023-10-11)
- https://optout.aboutads.info/ (2023-10-11)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
