### ISSUE TITLE
Broken Site: worlddutyfree.com

### ISSUE THREAD

**Issue by kdzwinel** [duckduckgo/privacy-configuration#1380]
### URLs affected

https://london-heathrow.worlddutyfree.com/en/63/fortnum-mason-lemon-curd-piccadilly-biscuits-200g

### Description of Breakage

Steps to reproduce:
click "add to bag"
pick terminal and time
click "Update"

Expected result
page reloads / navigates away

Actual result
nothing happens

### Tracker Requests breaking the site

https://www.google-analytics.com/analytics.js surrogate is causing issues, needs to be unblocked

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
