### ISSUE TITLE
Broken Site: Newsletter sign-up form not showing on Politico

### ISSUE THREAD

**Issue by kdzwinel** [duckduckgo/privacy-configuration#1382]
### URLs affected

https://www.politico.com/news/2023/10/09/israel-seeks-weapons-missiles-artillery-from-us-00120587

### Description of Breakage

Email form at the bottom doesn't load w/o https://tags.tiqcdn.com/utag/politico/main/prod/utag.js

### Tracker Requests breaking the site

Scroll to the bottom, see if email form loads

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
