### ISSUE TITLE
Broken Site: yandex map

### ISSUE THREAD

**Issue by kdzwinel** [duckduckgo/privacy-configuration#1384]
### URLs affected

https://www.ent-en.com/en/page/contacts

### Description of Breakage

Yandex map is missing on https://www.ent-en.com/en/page/contacts

### Tracker Requests breaking the site

Go to https://www.ent-en.com/en/page/contacts and look for the map :)

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
