### ISSUE TITLE
https redirect issues

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1392]
Issues where `https` feature causes sites to fail to load due to "too many redirects".

- https://github.com/duckduckgo/privacy-configuration/issues/1336
- https://github.com/duckduckgo/privacy-configuration/issues/1158
- https://www.jp.square-enix.com/seiken2_som/news.html (2023-10-16)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
