### ISSUE TITLE
osano.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1398]
- https://www.insider.com/guides/health/diet-nutrition/too-much-magnesium (2023-10-17)
  - https://app.asana.com/0/1200277586140538/1205727436463649/f
  - Clicking the account button has no effect.
  - requires `cmp.osano.com`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
