### ISSUE TITLE
tiktok embeds breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1412]
- https://www.barstoolsports.com/blog/3489694/couple-gets-totally-exposed-by-best-friend (2023-10-19)
  - https://app.asana.com/0/1200277586140538/1205755947676604/f
  - embed doesn't show
  - `www.tiktok.com/embed.js`
  - `www.tiktok.com/embed/v2/7291065905709075743`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
