### ISSUE TITLE
permutive breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1418]
- https://watch.globaltv.com/series/32666571/episode/GLOB0057038490000000/?action=play (2023-10-20)
  - https://app.asana.com/0/1200277586140538/1205762813777733/f
  - video gets stuck on loading spinner
  - `edge.permutive.app`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
