### ISSUE TITLE
sundancecatalog.com broken?

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1420]
https://app.asana.com/0/892838074342800/1205750948129814/f
- various issues - menus not loading, login button doesn't work
- can't get a clear repro of a mitigation, and breakage occurs w/ and w/o protections. Possibly `contentBlocking` if any

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
