### ISSUE TITLE
mytrackman not loading (macOS)

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1426]
- https://mytrackman.com/system/dynamic-report (2023-10-20)
- https://app.asana.com/0/1200277586140538/1205762783606668/f
- displays blank on macOS
- `connect.facebook.net/en_US/sdk.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
