### ISSUE TITLE
RevenueCat in App Tracker blocklist

### ISSUE THREAD

**Issue by RikH81** [duckduckgo/privacy-configuration#1429]
Hey! 👋

I work for [RevenueCat](http://revenuecat.com/) and we just noticed that we were added to this list, as we started getting support requests from Android users.

RevenueCat is an in-app purchase processing system and is not used to serve ads to users (actually, some apps use us to let users remove ads!). Blocking our API prevents people from being able to buy and access content in the 30,000+ apps that have shipped with our SDK.

For more context on what it is we do when it comes to data gathering, [here's our Play Data Safety guidance doc](https://www.revenuecat.com/docs/google-plays-data-safety). The same is linked to from [our Play SDK Index entrance here](https://play.google.com/sdks/details/com-revenuecat-purchases-purchases), which is an all-round solid resource when you're looking to gather info on SDKs you might want to block (or ignore).

It would be great if we could remove RevenueCat from this list, since lots of users would be getting errors and asking for support from both RC and our customers, with us being unable to help. Actually, we have been getting some reports already that some of our customers' apps are broken because of this.

Let us know your thoughts, I’m happy to answer any questions about our service if you need it.

Thanks!

**Comment by nshuba** [comment]
Hello and thank you for letting us know. We have added an exception for RevenueCat: https://github.com/duckduckgo/tracker-blocklists/pull/38

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
