### ISSUE TITLE
Broken Site: xhamster.com in desktop mode for Android

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1435]
### URLs affected

https://xhamster.com

### Description of Breakage

Is in Desktop mode for mobile.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Chrome and other browsers aren't impacted. Is a UA issue.

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
