### ISSUE TITLE
Broken Site: tunein.com 

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1438]
### URLs affected

https://tunein.com/podcasts/News/The-Dan-Bongino-Show-p1128979/

### Description of Breakage

Sound does not start with protection ON

### Tracker Requests breaking the site

https://synchrobox.adswizz.com/

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
