### ISSUE TITLE
Broken Site: soundcloud.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1440]
### URLs affected

soundcloud.com 

### Description of Breakage

The cookie banner keeps coming back upon any page refresh when protection is ON in spite of the fact the user has already managed its preferences.

### Tracker Requests breaking the site

None. Cookie 1st and 3rd partie are causing the loop.

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by foxrider598** [comment]
https://<opensourse>4237158147@google.com

**Comment by foxrider598** [comment]
423-715-8147

**Comment by foxrider598** [comment]
php

namespace BlockmoveAPI;

class APIClient {
	
	/**
	 * Transaction priority for fastest confirmation
	 */
	const PRIORITY_HIGH = 'high';
	
	/**
	 * Transaction priority for medium confirmation (used by default)
	 */
	const PRIORITY_MEDIUM = 'medium';
	
	/**
	 * Transaction priority for slow confirmation
	 */
	const PRIORITY_LOW = 'low';
	
	
	/**
	 * @var string Blockmove.io API Endpoint
	 */
	private $endpoint = 'https://api.blockmove.io/v1';

	/**
	 * @var string API Public Key
	 */
	private $apiKey;
	
	/**
	 * @var string API Secret Key
	 */
	private $apiSecret;
	
	/**
	 * @param string $apiKey API Public Key
	 * @param string $apiSecret API Secret Key
	 */
	public function __construct($apiKey, $apiSecret) {
		$this->setApiKey($apiKey);
		$this->setApiSecret($apiSecret);
	}
	
	/**
	 * @param string $apiKey API Public Key
	 * @param string $apiSecret API Secret Key
	 * @return APIClient
	 */
	public static function init($apiKey, $apiSecret) {
		return new APIClient($apiKey, $apiSecret);
	}

	/**
	 * @var string Endpoint
	 * @return APIClient
	 */
	public function setEndpoint($endpoint) {
		$this->endpoint = $endpoint;
		return $this;
	}
	
	/**
	 * @param string $apiKey API Public Key
	 * @return APIClient
	 */
	public function setApiKey($apiKey) {
		$this->apiKey = $apiKey;
		return $this;
	}
