### ISSUE TITLE
Broken Site: fanfiction.net

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1443]
### URLs affected

https://m.fanfiction.net/s/13742894/5/

### Description of Breakage

User custom agent prevents the cloudflare human verification process to succeed, creating a loop so the user is unable to access the site.

### Tracker Requests breaking the site

None

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
