### ISSUE TITLE
Broken Site: delta.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1445]
### URLs affected

https://www.delta.com/change-trip/

### Description of Breakage

Most of the page remains blank

### Tracker Requests breaking the site

[https://cdn.trackjs.com/agent/v3/latest/t.js](https://cdn.trackjs.com/agent/v3/latest/t.js)

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
