### ISSUE TITLE
Broken Site: collider.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1447]
### URLs affected

https://collider.com/movies-releases-2023/

### Description of Breakage

ad blocker banner caused by content blocking

### Tracker Requests breaking the site

https://adserver.adtech.advertising.com/pubapi/3.0/1/54669.7/0/0/ADTECH;v=2;cmd=bid;cors=yes

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
