### ISSUE TITLE
Broken Site: thehustle.co

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1460]
### URLs affected

https://thehustle.co/aairpass-american-airlines-250k-lifetime-ticket/

### Description of Breakage

Page constantly reloading

### Tracker Requests breaking the site

Page is redirecting away from canonical URL, but AMP protections prevents the amp page from loading.

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
