### ISSUE TITLE
Broken Site: oneill.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1465]
### URLs affected

https://eu.oneill.com/collections/swimsuits-women

### Description of Breakage

Shop items do not load

### Tracker Requests breaking the site

https://connect.nosto.com/script/shopify/nosto.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
