### ISSUE TITLE
webcompat breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#1473]
- https://www.svt.se/nyheter/lokalt/dalarna/har-lamnar-bjornen-diego-rovdjursparken-skjutsas-med-lastbil-till-england--b4hjyw (2023-11-07)
  - https://app.asana.com/0/1200277586140538/1205889100396691
  - Android
  - video doesn't play (no play button)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
