### ISSUE TITLE
Broken Site: nfl.com

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1488]
### URLs affected

https://www.nfl.com/news/49ers-qb-brock-purdy-takes-ownership-of-turnovers-i-have-to-be-smart-with-the-ba

### Description of Breakage

Video won't play on iOS & macOS

### Tracker Requests breaking the site

1. imasdk.googleapis.com/js/sdkloader/ima3.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

Breakage is caused by a timing issue with surrogate injection

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing in favor of broader iOS/macOS exception issue #1965.
