### ISSUE TITLE
Broken Site: finewineandgoodspirits.com

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1490]
### URLs affected

https://www.finewineandgoodspirits.com/

### Description of Breakage

Search doesn't function

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

User Agent issue

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
