### ISSUE TITLE
Broken Site: oreillyauto.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1501]
### URLs affected

https://locations.oreillyauto.com/wa/

### Description of Breakage

product search input not clickable after GPC gets acknowledged. Only happenign on iOS and Android.

### Tracker Requests breaking the site

none - GPC causes the breakage

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
