### ISSUE TITLE
Broken Site: bloomberg.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1507]
### URLs affected

https://www.bloomberg.com/live

### Description of Breakage

ad blocker "banner" is preventing the live show to play. Issue is on iOS/MacOS. This is linked to some redirection issue with googleapis.com

### Tracker Requests breaking the site

imasdk.googleapis.com

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing in favor of broader iOS/macOS exception issue #1965.
