### ISSUE TITLE
Broken Site: paper-io.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1510]
### URLs affected

https://paper-io.com/

### Description of Breakage

with protection ON, the game does not launch and the screen stays blank. 
When protection is OFF, a video ad pops up and afterwards, the game starts.
when adding an exception to ima3, no video ad on the way, the game starts straight away
issue on android/FF

### Tracker Requests breaking the site

imasdk.googleapis.com/js/sdkloader/ima3.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
