### ISSUE TITLE
Broken Site: metro.co.uk

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1513]
### URLs affected

https://metro.co.uk/2023/11/09/essex-motorcyclist-banned-filming-wheelies-going-150mph-19802529/

### Description of Breakage

Video does not behave as expected and differently based on multiple platforms. The breakage seems to have mix origins (ima3 and CPM / the combo of the two).
Check more details here: https://app.asana.com/0/1200277586140538/1205950090299863/f

### Tracker Requests breaking the site

imasdk.googleapis.com/js/sdkloader/ima3.js
CPM

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
