### ISSUE TITLE
Broken Site: thesurfersview.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1516]
### URLs affected

https://thesurfersview.com/live-cams/new-jersey/manasquan-beach-cam-and-surf-report/

### Description of Breakage

video does not load. Play button does not work. ad blocker banner appearing on MacOS.

### Tracker Requests breaking the site

https://c.amazon-adsystem.com/aax2/apstag.js 

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
