### ISSUE TITLE
Broken Site: games.washingtonpost.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1518]
### URLs affected

https://games.washingtonpost.com/games/jigsaw

### Description of Breakage

Certainly caused by ima3 surrogate, a video ad can't load, therefore the game can't load

### Tracker Requests breaking the site

imasdk.googleapis.com/js/sdkloader/ima3.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

scoped mitigation to iOS and MacOS

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing in favor of broader iOS/macOS exception issue #1965.
