### ISSUE TITLE
Broken Site: blick.ch 

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1520]
### URLs affected

https://www.blick.ch/sport/tennis/ballsituation-ist-verrueckt-belag-in-turin-zu-schnell-tennis-star-alcaraz-holt-zum-rundumschlag-aus-id19145506.html

### Description of Breakage

ad blocker banner on iOS and MacOS only

### Tracker Requests breaking the site

https://www.npttech.com/advertising.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
