### ISSUE TITLE
Broken Site: drakescans.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1522]
### URLs affected

drakescans.com

### Description of Breakage

ad blocker caused by a surrogate 

### Tracker Requests breaking the site

pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
