### ISSUE TITLE
Broken Site: chime.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1524]
### URLs affected

https://www.chime.com/blog/how-to-set-up-direct-deposit-with-chime/

### Description of Breakage

Youtube video doesn't load:
- The user is required to enable "Sale or Share of Personal Information" for the video to load.
- However, with the GPC option on, the CPM (Onetrust) prevents this setting from being enabled.

### Tracker Requests breaking the site

GPC must be disabled

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
