### ISSUE TITLE
Broken Site: littleunicorn.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1526]
### URLs affected

https://littleunicorn.com/products/cotton-sleep-bag-x-large-watercolor-roses

### Description of Breakage

Checkout button isn't responsive because we're blocking a tracker

### Tracker Requests breaking the site

[protection-widget.route.com/protect.core.js](https://protection-widget.route.com/protect.core.js)

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by dharb** [comment]
Closing in favor of https://github.com/duckduckgo/privacy-configuration/issues/1591
