### ISSUE TITLE
Broken Site: Reach PLC sites

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1529]
### URLs affected

https://www.belfastlive.co.uk/news/belfast-news/belfast-student-saved-police-after-27765864
https://www.cornwalllive.com/news/cornwall-news/santas-bike-2023-see-santas-8905618?int_source=nba

### Description of Breakage

video does not load caused by a tracker we're blocking

### Tracker Requests breaking the site

[live.primis.tech/live/liveView.php](http://live.primis.tech/live/liveView.php)

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
