### ISSUE TITLE
Broken Site: takealot.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1532]
### URLs affected

takealot.com

### Description of Breakage

2 issues:
- site can't be accessed due to an overlay created by CPM (on mobile only **where the mitigation will be sitting)** 
- some pictures don't load and keep spinning which is due to element hiding (everywhere)

### Tracker Requests breaking the site

none

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
