### ISSUE TITLE
Broken Site: politico.com 

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1534]
### URLs affected

https://www.politico.com/gallery/2023/11/10/the-nations-cartoonists-on-the-week-in-politics-00126491?slide=0

### Description of Breakage

Sliding on politico's carousel is broken because of some video ad that can't be played. 
A transparent overlay with the message "skip ad in" freezes the page and there's no way to escape it. 
Only happening on MacOS and iOS.

### Tracker Requests breaking the site

tags.tiqcdn.com/utag/

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [x] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
