### ISSUE TITLE
Broken Site: tipranks.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1537]
### URLs affected

https://www.tipranks.com/news/microsoft-nasdaqmsft-takes-aim-at-nvidia-nasdaqnvda-with-new-chip

### Description of Breakage

Tipranks.com new article returns 500 because of blocking a tracker

### Tracker Requests breaking the site

https://cdn.taboola.com/libtrc/unip/1622815/tfa.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
