### ISSUE TITLE
Broken Site: foxweather.com

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1541]
### URLs affected

https://www.foxweather.com/live

### Description of Breakage

Video doesn't load

### Tracker Requests breaking the site

1. c.amazon-adsystem.com/aax2/apstag.js
2. pubads.g.doubleclick.net/ssai/pods/

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Other Details

apstag surrogate should solve this.

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
