### ISSUE TITLE
Broken Site: cakebycourtney.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1547]
### URLs affected

https://cakebycourtney.com/

### Description of Breakage

the search bar is not responsive. This is caused by blocking the slickstream trackers.

### Tracker Requests breaking the site

https://app.slickstream.com/

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
