### ISSUE TITLE
Broken Site: recipetineats.com

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1549]
### URLs affected

- https://www.recipetineats.com/southern-thai-tumeric-chicken-grilled-or-baked/comment-page-2/
- other sites that load this same request in https://github.com/duckduckgo/tracker-radar/blob/main/domains/US/slickstream.com.json
### Description of Breakage

Can't favorite recipes or access account section of site

### Tracker Requests breaking the site

1. https://app.slickstream.com/d/page-boot-data

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
