### ISSUE TITLE
Broken Site: gamak.tv

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1558]
### URLs affected

https://www.gamak.tv/ren-tv/2023-11-18/11:00/

### Description of Breakage

video player is missing and we're getting a notification to unblock https://imasdk.googleapis.com/js/sdkloader/ima3.js (iOS and MacOS).
works fine on iOS/macOS with protection OFF but not on Android.
No issue on extension.

### Tracker Requests breaking the site

https://imasdk.googleapis.com/js/sdkloader/ima3.js

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
