### ISSUE TITLE
Broken Site: startpagina.nl

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1565]
### URLs affected

https://www.startpagina.nl/

### Description of Breakage

Site becomes unresponsive due to element hiding

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
