### ISSUE TITLE
Broken Site: tamashiiweb.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1574]
### URLs affected

tamashiiweb.com

### Description of Breakage

A the bottom of the page there's a widget to change the page language.
When clicked, it should open a pop up stating that the translation is approximate.
When clicked on OK the page should have been translated.

Our protection is blocking a tracker that prevents this pop up to open and therefore the translation cannot happen.

### Tracker Requests breaking the site

https://j.wovn.io/1

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
