### ISSUE TITLE
Broken Site: clionadhcosmetics.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1583]
### URLs affected

https://clionadhcosmetics.com/cart

### Description of Breakage

User can't get to checkout after filling up their basket because we're blocking a tracker meant to activate an option to add to the cart. Having it visible activate the checkout button.

### Tracker Requests breaking the site

https://protection-widget.route.com/protect.core.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by dharb** [comment]
Closing in favor of https://github.com/duckduckgo/privacy-configuration/issues/1591
