### ISSUE TITLE
Broken Site: www.hotpoint.co.uk

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1586]
### URLs affected

https://www.hotpoint.co.uk/service/repair/out-of-warranty

### Description of Breakage

Service buttons not working.

See also:
https://app.asana.com/0/1200277586140538/1206091922260017/f

### Tracker Requests breaking the site

1. widget.trustpilot.com/bootstrap/v5/tp.widget.sync.bootstrap.min.js
2. widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

.

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
