### ISSUE TITLE
tfaforms.net breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1588]
- https://foundation.mozilla.org/en/donate/help/ (2023-12-04)
  - tfaforms.net/wForms/3.11/js/wforms.js needs to load for form submission
  - Probably shouldn't be blocking this anywhere
- https://www.cpr.org/
  - tfaforms.net/20 needs to load for newsletter sign up in footer to appear

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
