### ISSUE TITLE
protection-widget.route.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1591]
Blocking https://protection-widget.route.com/protect.core.js causes issues with many Shopify sites where the checkout button doesn't work, see:
- https://github.com/duckduckgo/privacy-configuration/issues/1526
- https://github.com/duckduckgo/privacy-configuration/issues/1554
- https://github.com/duckduckgo/privacy-configuration/issues/1583

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
