### ISSUE TITLE
Broken Site: learning.edx.org

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1596]
### URLs affected

https://learning.edx.org/course/course-v1:IBM+CAD101EN+3T2022/home

### Description of Breakage

Page is blank on iOS & macOS only

### Tracker Requests breaking the site

1. js.appboycdn.com/web-sdk/3.1/appboy.min.js
2. google-analytics.com/analytics.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

As far as I can tell, this is another issue with surrogate injection timing on iOS & macOS

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
