### ISSUE TITLE
Broken Site: landsend.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1602]
### URLs affected

https://www.landsend.com/customer-service/contact-us/

### Description of Breakage

blocking a tracker is preventing the chat feature to launch

### Tracker Requests breaking the site

https://analytics.analytics-egain.com/onetag/EG95369676

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
