### ISSUE TITLE
Broken Site: daotranslate.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1604]
### URLs affected

daotranslate.com

### Description of Breakage

ad blocker banner caused by surrogate

### Tracker Requests breaking the site

pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
