### ISSUE TITLE
Broken Site: arkadium.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1606]
### URLs affected

https://www.arkadium.com/games/word-wipe/?__arkver=688

### Description of Breakage

Blocking video pre-roll ads prevents game from loading. This is caused by a surrogate.

### Tracker Requests breaking the site

https://imasdk.googleapis.com/js/sdkloader/ima3.js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
