### ISSUE TITLE
Broken Site: searchhudforeclosures.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1608]
### URLs affected

searchhudforeclosures.com

### Description of Breakage

site is blank when protections are enabled caused by blocking a tracker

### Tracker Requests breaking the site

https://dev.visualwebsiteoptimizer.com/j.php

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
