### ISSUE TITLE
Broken Site: silhouetteu.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1610]
### URLs affected

https://silhouetteu.com/pages/join

### Description of Breakage

Website does not load with protections on. This is caused by blocking a tracker.

### Tracker Requests breaking the site

klaviyo.com/media/js/public/klaviyo_subscribe.js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
