### ISSUE TITLE
Broken Site: express.co.uk

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1613]
### URLs affected

https://www.express.co.uk/news/politics/1843214/tory-attack-ad-labour-bbc-middle-finger#conversation-wrapper

### Description of Breakage

comments section does not load due to a blocked tracker

### Tracker Requests breaking the site

cmp.inmobi.com via
- https://cmp.inmobi.com/choice/JYWDqeLS64fbt/www.express.co.uk/choice.js
- https://cmp.inmobi.com/tcfv2/cmp2.js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
