### ISSUE TITLE
Broken Site: abebooks.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1618]
### URLs affected

https://www.abebooks.com/

### Description of Breakage

With protections on the layout looks broken and the website is not fully showing. 

### Tracker Requests breaking the site

assets.brightspot.abebooks.a2z.com

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
