### ISSUE TITLE
Broken Site: Restrap

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1620]
### URLs affected

https://restrap.com/blogs/news/the-restrap-solstice-century-challenge-2023

### Description of Breakage

Form missing

### Tracker Requests breaking the site

1. www.klaviyo.com/media/js/public/klaviyo_subscribe.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Other Details

https://app.asana.com/0/1200277586140538/1206141406433447/f

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
