### ISSUE TITLE
Broken Site: dzen.ru

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1627]
### URLs affected

https://m.dzen.ru/pogoda/maps/nowcast?ll=1.441221000000028_43.59222400009268&z=9

### Description of Breakage

Map does not load because of a tracker being blocked

### Tracker Requests breaking the site

https://api-maps.yandex.ru/services/startup/v1

### Affected Platforms

- [ ] Browser Extensions
- [x] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
