### ISSUE TITLE
Broken Site: air-journal.fr

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/privacy-configuration#1630]
### URLs affected

https://www.air-journal.fr/

### Description of Breakage

Adblock wall on site caused by tracker blocking (surrogate script).

### Tracker Requests breaking the site

pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

Haven’t tested on Android or Windows but assume that it affects all platforms.

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
