### ISSUE TITLE
Broken Site: zoom.us

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1635]
### URLs affected

any zoom meeting

### Description of Breakage

on MacOS only, a user's video remains blank with protection ON. This is caused by the fingerprinting hardware protection.

### Tracker Requests breaking the site

NA

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
