### ISSUE TITLE
Snapengage breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1647]
Chat widgets from Snapengage are being blocked. e.g.
- https://www.expressvpn.com/support/
- https://www.sunriseseniorliving.com/ - button to start chat in bottom left not shown.
- https://www.ice.edu/ - chat button on right is broken.
- https://www.ccalliance.org/ - chat button on bottom right is missing.
- https://www.shaneco.com/
- https://www.acefitness.org/

Allowing requests to `https://storage.googleapis.com/code.snapengage.com/` fixes.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
