### ISSUE TITLE
Broken Site: oceanofcompressed.xyz

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/privacy-configuration#1652]
### URLs affected

https://oceanofcompressed.xyz/

### Description of Breakage

An adblock wall prevents the site from being used.

### Tracker Requests breaking the site

contextual.media.net/dmedianet.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

Element hiding is also needed to fix the issue.

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
