### ISSUE TITLE
Hubspot chat breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1656]
Live chat widgets loaded via hubspot are broken on multiple sites:
 - pippintitle.com
 - https://www.emis.com/
 - https://www.customwheeloffset.com/
- https://www.userinterviews.com/support-category/participant-resources
Allowing the following requests fixes:
- `api.hubspot.com/livechat-public/v1/message/public`
- `js.hubspot.com/web-interactives-embed.js`
-  `api.hubspot.com/livechat-public/v1/message/public`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
