### ISSUE TITLE
Broken Site: breitbart.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1660]
### URLs affected

https://www.breitbart.com/politics/2023/12/17/waffle-house-customer-shoots-kills-man-allegedly-threatened-shoot-patrons/

### Description of Breakage

site requires user to accept social cookies to view social media post and comments. It makes it harder for the user to do that with CPM ON.

### Tracker Requests breaking the site

NA

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
