### ISSUE TITLE
Broken Site: news.ti.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1677]
### URLs affected

https://news.ti.com/blog/2023/11/14/how-ti-is-creating-sustainable-future?HQS=corp-cmpcul-sus-sustainablefuture_20231130_4Q23-bhp-blog-null-wwe

### Description of Breakage

CPM breaks on the site because cookie value gets lost and thus cookie settings are not saved correctly

### Tracker Requests breaking the site

NA

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
