### ISSUE TITLE
Broken Site: tirerack.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1680]
### URLs affected

https://www.tirerack.com/content/tirerack/desktop/en/homepage.html

### Description of Breakage

Live chat button does not show if GPC is enabled.

### Tracker Requests breaking the site

GPC.

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
