### ISSUE TITLE
Pop Ups for on-line banking

### ISSUE THREAD

**Issue by csklovie** [duckduckgo/privacy-configuration#1682]
### URLs affected

secunm.org

### Description of Breakage

Not able to get into ‘Payments' due to pop up blocking

### Tracker Requests breaking the site

secunm.org

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
