### ISSUE TITLE
Broken Site: tradersync.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1687]
### URLs affected

https://tradersync.com/

### Description of Breakage

Chat widget doesn't load.

### Tracker Requests breaking the site

https://www.googletagmanager.com/gtag/js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
