### ISSUE TITLE
Broken Site: newser.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1689]
### URLs affected

https://newser.com

### Description of Breakage

Layout is somewhat broken, the black top-header bar for navigation is too tall.

### Tracker Requests breaking the site

https://a.pub.network/newser-com/cls.css

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
