### ISSUE TITLE
Broken Site: dallasnews.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1691]
### URLs affected

https://www.dallasnews.com/

### Description of Breakage

Secondary navigation menu header is missing, layout is broken.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

This is caused by one of the "default" (aka generic) element hiding rules.

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
