### ISSUE TITLE
Broken Site: kits4beats.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1697]
### URLs affected

https://kits4beats.com

### Description of Breakage

"Please disable your ad blocker" wall

### Tracker Requests breaking the site

1. https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
