### ISSUE TITLE
Broken Site: thesimsresource.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1706]
### URLs affected

https://www.thesimsresource.com/downloads/details/id/1684626

### Description of Breakage

After clicking "Download" button, an extra 60 delay is shown prompting the user to disable their ad blocker.

### Tracker Requests breaking the site

1. https://www.googleoptimize.com/optimize.js?id=OPT-5HMGRJN
2. https://www.googletagmanager.com/gtag/js?id=AW-471179842
3. https://www.googletagmanager.com/gtag/js?id=AW-11045996978

(The script https://www.thesimsresource.com/js/ad-loader.js only displays the warning if two or more requests are blocked of four, and we don't block the fourth. So to work around this we only need to unblock two of the above requests.)

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
