### ISSUE TITLE
Broken Site: pandora.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1710]
### URLs affected

https://pandora.com

### Description of Breakage

Log in with trial account, click an artist and click to listen to their songs. A prompt is shown to watch one advert first, but the advert never opens and therefore the music never plays.

### Tracker Requests breaking the site

1. imasdk.googleapis.com/js/sdkloader/ima3.js

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
