### ISSUE TITLE
Broken Site: axs.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1712]
### URLs affected

https://www.axs.com/events/509509/sublime-with-rome-tickets?skin=redrocks

### Description of Breakage

After clicking "GET TICKETS" and then "OK", an error saying that the session has expired is displayed.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Relates to the tracker parameter protection feature.

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
