### ISSUE TITLE
Broken Site: theposh.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1714]
### URLs affected

https://www.theposh.com/table/226

### Description of Breakage

The table of football teams does not show up, instead there is a blank space in the page.

### Tracker Requests breaking the site

1. https://secure.widget.cloud.opta.net/v3/v3.opta-widgets.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
