### ISSUE TITLE
Broken Site: bananarepublic.gap.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1717]
### URLs affected

https://bananarepublic.gap.com/browse/product.do?pid=754454002&cid=3017934&pcid=48422&vid=1#pdp-page-content

### Description of Breakage

The sidebar is missing the "FIT: TRUE TO SIZE" selector and the "REVIEWS" button. The layout of the sidebar looks kind of broken.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Seems related to the website's `navigator.globalPrivacyControl` handling code-paths.

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
