### ISSUE TITLE
Broken Site: diariodesevilla.es

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1721]
### URLs affected

https://www.diariodesevilla.es/

### Description of Breakage

Page has grey overlay and you can't scroll or interact with anything.

### Tracker Requests breaking the site

1. https://sdk.mrf.io/statics/marfeel-sdk.js
2. https://experiences.mrf.io/passexperience/dw-check.html
3. https://experiences.mrf.io/statics/inline-experiences/esnext/standalone.js
4. https://flowcards.mrf.io/transformer/marfeelpassexperienceengine.mrf.io

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
