### ISSUE TITLE
Broken Site: applesfera.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1723]
### URLs affected

https://www.applesfera.com/apple-1/apple-cuerdas-no-solo-europa-presion-justicia-su-presunto-monopolio

### Description of Breakage

Dailymotion video on the page doesn't load or play, displays as a black box.

### Tracker Requests breaking the site

1. https://c.amazon-adsystem.com/aax2/apstag.js
2. https://securepubads.g.doubleclick.net/tag/js/gpt.js
3. https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202401030101/pubads_impl.js
4. https://securepubads.g.doubleclick.net/gampad/ads

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
