### ISSUE TITLE
Broken Site: triblive.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1730]
### URLs affected

https://triblive.com/

### Description of Breakage

"Please disable your ad blocker" wall displayed on the site.

### Tracker Requests breaking the site

1. https://securepubads.g.doubleclick.net/tag/js/gpt.js
2. https://www.googletagservices.com/tag/js/gpt.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
