### ISSUE TITLE
Broken Site: stuff.co.nz

### ISSUE THREAD

**Issue by muodov** [duckduckgo/privacy-configuration#1740]
### URLs affected

https://stuff.co.nz

### Description of Breakage

Site loader is stuck

### Tracker Requests breaking the site

1. https://securepubads.g.doubleclick.net/tag/js/gpt.js
2. https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202401100101/pubads_impl.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
