### ISSUE TITLE
Broken Site: inquirer.com

### ISSUE THREAD

**Issue by muodov** [duckduckgo/privacy-configuration#1742]
### URLs affected

https://www.inquirer.com/

### Description of Breakage

Site does not load after the login

### Tracker Requests breaking the site

https://c.amazon-adsystem.com/aax2/apstag.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Site breaks when we use a surrogate. Blocking this request completely makes the site work

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
