### ISSUE TITLE
Broken Site: newsmax.com

### ISSUE THREAD

**Issue by muodov** [duckduckgo/privacy-configuration#1743]
### URLs affected

https://www.newsmax.com/

### Description of Breakage

Videos don't work if the user rejects optional cookies

### Tracker Requests breaking the site

-

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
