### ISSUE TITLE
Broken Site: dictionary.com

### ISSUE THREAD

**Issue by muodov** [duckduckgo/privacy-configuration#1746]
### URLs affected

https://www.dictionary.com/browse/all

### Description of Breakage

Embedded video is not shown

### Tracker Requests breaking the site

player.anyclip.com/anyclip-widget/lre-widget/prod/v1/src/lre.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

The same video player is used on other sites

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
