### ISSUE TITLE
Broken 3rd party: taboola.com in safari 17 private browsing mode

### ISSUE THREAD

**Issue by omriariav** [duckduckgo/privacy-configuration#1757]
### URLs affected

Go to any of the following URLs in Safari 17 when private browsing mode is turned on:
https://apnews.com/article/nasa-spacex-launch-astronauts-private-d850e84f510125d62c3678093837e868
https://www.globes.co.il/news/article.aspx?did=1001468359
https://www.ynet.co.il/economy/article/hymytw2yt
You can also see the issue on any website that is using Taboola JavaScript SDK for content recommendation 

### Description of Breakage

Taboola is a 3rd party JavaScript SDK that is running in leading publishers globally. In Safari 17, when the user is using private browsing, Taboola content gets blocked regardless of the tracking prevention.

Our main JavaScript files (loader.js and impl.{version}.js) are being blocked on many of our publisher sites. This results in our widgets not being rendered on many publisher sites, leading to viewership and revenue loss.

After some research, I've found these files to be marked with a high fingerprinting score on the tracker-rader file for Taboola:
(found here: https://raw.githubusercontent.com/duckduckgo/tracker-radar/main/domains/US/taboola.com.json).
This is very likely due to the usage of native APIs such as session storage, cookies, etc., in different modules/functions. It goes without saying that we're not fingerprinting using these APIs; their usage is for rendering, capping, and contextual needs. 

Safari folks [told us](https://bugs.webkit.org/show_bug.cgi?id=266540#c3) that the lists Safari uses are coming from DuckDuckGo.

We would love to have you look into it and if possible, provide us with the instructions and guidelines for writing
a surrogate or other technique that can restore Taboola rendering functionality.

Thanks for your cooperation.

### Tracker Requests breaking the site

https://cdn.taboola.com/libtrc/globesil/loader.js (our main loader file)
https://cdn.taboola.com/libtrc/impl.20240114-2-RELEASE.js (our implementation file)

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

Regardless of Safari usage, we are keen to develop a surrogate for DuckDuckGo products. 

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
