### ISSUE TITLE
Broken Site: www.sbs.com.au

### ISSUE THREAD

**Issue by kdzwinel** [duckduckgo/privacy-configuration#1761]
### URLs affected

www.sbs.com.au video on demand playback

### Description of Breakage

Asks to disable adblock

### Tracker Requests breaking the site

tremorhub.com
cm.g.doubleclick.net/pixel

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
