### ISSUE TITLE
Broken Site: washingtonpost.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1773]
### URLs affected

https://www.washingtonpost.com/crossword-puzzles/daily/

### Description of Breakage

crossword puzzle is broken

### Tracker Requests breaking the site

googleapis.com 

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
