### ISSUE TITLE
Broken Site: reisezoom.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1775]
### URLs affected

https://reisezoom.com/canon-g7x-mark-ii-test-tipps-einstellungen/

### Description of Breakage

images

### Tracker Requests breaking the site

ezodn.com

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
