### ISSUE TITLE
Broken Site: missing email signups

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#1777]
### URLs affected

all, example https://www.lyssachiavari.com/newsletter/

### Description of Breakage

blocking email newsletter signups from mailerlite.com

### Tracker Requests breaking the site

mailerlite.com

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
