### ISSUE TITLE
Broken Site: clearmemorysolution.com

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1786]
### URLs affected

https://clearmemorysolution.com/presentation

### Description of Breakage

It's not possible to play the video. Nothing happens when tapping on the "play" button.
![clearmemorysolution](https://github.com/duckduckgo/privacy-configuration/assets/7963079/432e594c-890f-47e7-bb2c-0b411f2289fc)

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
