### ISSUE TITLE
Broken Site: onlyfans.com

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1787]
### URLs affected

https://id.onlyfans.com/...
(Creator flow)

### Description of Breakage

You cannot take a selfie during the approval flow to become a "creator".

![onlyfans](https://github.com/duckduckgo/privacy-configuration/assets/7963079/a37c33a3-6032-451a-90a2-becf8ff4cde2)

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
