### ISSUE TITLE
Broken Site: naturemetabolism.com

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1788]
### URLs affected

https://naturemetabolism.com/gdn-comp

### Description of Breakage

It's not possible to play the video. Nothing happens when tapping on the "play" button.

![naturemetabolism](https://github.com/duckduckgo/privacy-configuration/assets/7963079/eeca2706-3618-4b2e-ad31-86ff87b7b1e6)

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
