### ISSUE TITLE
Broken Site: upperbodystretch.com

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1789]
### URLs affected

https://upperbodystretch.com/

### Description of Breakage

It's not possible to play the video. Nothing happens when tapping on the "play" button.
![upperbodystretch](https://github.com/duckduckgo/privacy-configuration/assets/7963079/62980f17-be25-486f-95e3-75a647e4efaf)

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
