### ISSUE TITLE
Broken Site: trustid.co.uk

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1792]
### URLs affected

https://cloudapi.trustid.co.uk/...
https://rtwapi.trustid.co.uk/...
https://rtw.trustid.co.uk/...

### Description of Breakage

Cannot take selfie.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
