### ISSUE TITLE
Broken Site: itau.com.br

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1793]
### URLs affected

https://facialwebcapture.cloud.itau.com.br/...

### Description of Breakage

Cannot take selfie.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
