### ISSUE TITLE
Broken Site: glennbeck.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1806]
### URLs affected

https://www.glennbeck.com/st/newsletter

### Description of Breakage

email input form does not display because of a blocked tracker

### Tracker Requests breaking the site

https://load.sumo.com/

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
