### ISSUE TITLE
Broken Site: app.boltive.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1813]
### URLs affected

https://app.boltive.com/login

### Description of Breakage

Login fails with a network error.

### Tracker Requests breaking the site

1. `https://publisher.adlightning.com/user-api/session/login`

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
