### ISSUE TITLE
Broken Site: https://www.canva.com/

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1818]
### URLs affected

https://www.canva.com/en_gb/

### Description of Breakage

"This browser is unsupported, download the desktop client"

<img width="1324" alt="image" src="https://github.com/duckduckgo/privacy-configuration/assets/338988/fdab1334-9103-4e5d-8868-126bcf79c8ff">

### Tracker Requests breaking the site

.

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [x] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
