### ISSUE TITLE
Broken Site: algomalegalclinic.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1822]
### URLs affected

https://www.algomalegalclinic.com/canada-pension-plan

### Description of Breakage

Some links don't work.

### Tracker Requests breaking the site

1. https://www.googletagmanager.com/gtag/js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
