### ISSUE TITLE
Broken Site: onlinebanking.53.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1824]
### URLs affected

https://onlinebanking.53.com/olb/

### Description of Breakage

Page content is blank.

### Tracker Requests breaking the site

Custom UA

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
