### ISSUE TITLE
Broken Site: evernote.com

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#1827]
### URLs affected

https://www.evernote.com/client/web

### Description of Breakage

After logging in browser is reported as not supported

### Tracker Requests breaking the site

,

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Other Details

<img width="1603" alt="image" src="https://github.com/duckduckgo/privacy-configuration/assets/338988/841a5e1f-1091-4782-b303-3c1e4cd73aa0">

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
