### ISSUE TITLE
Broken Site: eatroyo.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#1830]
### URLs affected

https://eatroyo.com/collections/all

### Description of Breakage

Images don't load

### Tracker Requests breaking the site

https://www.googletagmanager.com/gtag/js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
