### ISSUE TITLE
Broken Site: idahonews.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1834]
### URLs affected

https://idahonews.com/

### Description of Breakage

Pages turn blank with protection ON. This is caused by a tracker.

### Tracker Requests breaking the site

www.googletagservices.com/tag/js/gpt.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
