### ISSUE TITLE
Broken Site: discord.com

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/privacy-configuration#1839]
### URLs affected

https://discord.com

### Description of Breakage

“Unsupported browser” message appears when trying to use mic/camera in voice channel.

![discord_unsupported-browser_2024-02-23](https://github.com/duckduckgo/privacy-configuration/assets/94173/7e57e3fe-e8f9-48e0-bfad-c7654fdcbb74)

### Tracker Requests breaking the site

User agent detection breaking the site.

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
