### ISSUE TITLE
Broken Site: godaddy.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1845]
### URLs affected

sso.godaddy.com

### Description of Breakage

Access blocked to DDG users to the site.
A banner pops up a few minutes after landing and remaining on the page.

### Tracker Requests breaking the site

none. UA issue.

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
