### ISSUE TITLE
Broken Site: aviatornation.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1847]
### URLs affected

https://www.aviatornation.com/

### Description of Breakage

Images don't display

### Tracker Requests breaking the site

https://rapid-cdn.yottaa.com/rapid/lib/ZfJxptseJcUQIA.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
