### ISSUE TITLE
Broken Site: instagram.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1856]
### URLs affected

instagram.com

### Description of Breakage

CPM race condition leads to blank screen

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
