### ISSUE TITLE
Broken Site: sbs.com.au

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1861]
### URLs affected

https://www.sbs.com.au/ondemand/watch/1759807555754

### Description of Breakage

video playback error where users are asked to turn off their ad blocker

### Tracker Requests breaking the site

[dpm.demdex.net](https://dpm.demdex.net/id)

### Affected Platforms

- [X] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
