### ISSUE TITLE
Broken Site: verify.id.me

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1865]
### URLs affected

https://verify.id.me/en/live-selfie/

### Description of Breakage

Camera access blocked.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
