### ISSUE TITLE
Broken Site: channel4.com and 6play.fr

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1884]
### URLs affected

channel4.com
6play.fr

### Description of Breakage

To avoid further similar mitigations, rules for fwmrm.net have been simplified

### Tracker Requests breaking the site

v.fwmrm.net/ad

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
