### ISSUE TITLE
Broken Site: crunchyroll.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1888]
### URLs affected

https://www.crunchyroll.com/watch/GVWU07159/untitled

### Description of Breakage

Video doesn't play.

### Tracker Requests breaking the site

1. TBD

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing in favor of broader iOS/macOS exception issue #1965.
