### ISSUE TITLE
Broken Site: tumblr.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1894]
### URLs affected

https://tumblr.com

### Description of Breakage

A "please disable your ad-blocker" wall is displayed

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

Element hiding triggers it.

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
