### ISSUE TITLE
Broken Site: disneyplus.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#1897]
### URLs affected

www.disneyplus.com

### Description of Breakage

infinite protection reload on homepage due to autoconsent

### Tracker Requests breaking the site

none

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by muodov** [comment]
This was fixed in https://github.com/duckduckgo/autoconsent/pull/393

**Comment by muodov** [comment]
Reopening because the Reject button doesn't work in some regions (Hungary was reported)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
