### ISSUE TITLE
Broken Site: si.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1902]
### URLs affected

https://www.si.com/nba/scoreboard

### Description of Breakage

"Please disable your ad-blocker" wall is displayed

### Tracker Requests breaking the site

1. https://adserver.adtech.advertising.com/pubapi/3.0/1/948147.0/0/0/ADTECH;v=2;cmd=bid;cors=yes

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
