### ISSUE TITLE
Broken Site: hgtv.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1904]
### URLs affected

https://www.hgtv.com/shows/home-town/tour-and-erin-and-ben-napiers-country-home-pictures

### Description of Breakage

Cannot page through the photos, the arrow buttons don't show up.

### Tracker Requests breaking the site

1. https://cdn.optimizely.com/js/24096340716.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
