### ISSUE TITLE
Broken Site: fattoincasadabenedetta.it

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#1906]
### URLs affected

https://www.fattoincasadabenedetta.it/ricetta/pizzette-di-pasta-sfoglia/

### Description of Breakage

Video won't always play when clicked.

### Tracker Requests breaking the site

1. https://c.amazon-adsystem.com/aax2/apstag.js

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
