### ISSUE TITLE
Broken Site: jumio.ai

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1929]
### URLs affected

https://securelivemediallc.web.amer-1.jumio.ai/web/v4/app/credential/0/identification/capture/nid/front/camera

### Description of Breakage

Selfie identification doesn't work on Android

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
