### ISSUE TITLE
Broken Site: web.de

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#1931]
### URLs affected

https://web.de

### Description of Breakage

Partial homepage loads due to custom UA

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [x] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
