### ISSUE TITLE
Broken Site: duck.com

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#1958]
### URLs affected

duck.com

### Description of Breakage

Instead of the DDG UA, we use the generic Android UA for this domain.

This causes the homepage to treat the browser as an uninstalled Android user, and shows them the App Install CTA on the homepage.

### Tracker Requests breaking the site

n/a

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
