### ISSUE TITLE
Broken Site: All airbnb

### ISSUE THREAD

**Issue by anikiki** [duckduckgo/privacy-configuration#1979]
### URLs affected

https://www.airbnb.com/account-fov

### Description of Breakage

Camera not working.

### Tracker Requests breaking the site

N/A

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

No

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
