### ISSUE TITLE
Video not playing on independent.co.uk

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/privacy-configuration#2017]
### URLs affected

https://www.independent.co.uk/sport/us-sport/caitlin-clark-first-pick-wnba-draft-b2529254.html

### Description of Breakage

Not possible to play embedded video.

### Tracker Requests breaking the site

* static.adsafeprotected.com/iasPET.1.js
* npttech.com/advertising.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
