### ISSUE TITLE
Broken Site: zojirushi.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#2021]
### URLs affected

https://www.zojirushi.com

### Description of Breakage

Trustarc popup takes very long to process consent.

### Tracker Requests breaking the site

1. https://googleads.g.doubleclick.net/ads/preferences/naioptout

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
