### ISSUE TITLE
Broken Site: id.seb.se

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#2025]
### URLs affected

https://id.seb.se/ccs

### Description of Breakage

Page loads with blank content.
![Screenshot 2024-04-24 at 10 06 19](https://github.com/duckduckgo/privacy-configuration/assets/248111/a343b837-fc29-4c18-a25a-8ac59c2a3f67)

### Tracker Requests breaking the site

Reverting to default Safari UA fixes.

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
