### ISSUE TITLE
Broken Site: wideopencountry.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#2028]
### URLs affected

https://www.wideopencountry.com/kind-wood-use-smoking-meat/

### Description of Breakage

Video doesn't load

### Tracker Requests breaking the site

1. `live.primis.tech/live/`
2. `live.primis.tech/content/omid/static/`
3. `video.primis.tech/`

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
