### ISSUE TITLE
Broken Site: lotustalk.com

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#2031]
### URLs affected

https://www.lotustalk.com/threads/for-sale-2021-evoragt-manual.545649/

### Description of Breakage

Ad links do not open.

### Tracker Requests breaking the site

1. Links bounce via go.skimresources.com, which gets blocked on apple platforms.

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
