### ISSUE TITLE
Broken Site: budgetbytes.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#2039]
### URLs affected

https://www.budgetbytes.com/air-fryer-potatoes/

### Description of Breakage

can't save recipes 

### Tracker Requests breaking the site

grow.me

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
