### ISSUE TITLE
Broken Site: danibowman.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#2045]
### URLs affected

https://danibowman.com/

### Description of Breakage

missing facebook chat

### Tracker Requests breaking the site

1. facebook.com
2. facebook.net

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
