### ISSUE TITLE
Missing social media section on several sites

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#2047]
### URLs affected

ninjakitchen.com
sharkclean.com

### Description of Breakage

missing a social media section 

### Tracker Requests breaking the site

curalate.com/sites/

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
