### ISSUE TITLE
Broken Site:  marlboro.com

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#2057]
### URLs affected

https://www.marlboro.com/pages/home.html

### Description of Breakage

Content missing on marlboro.com

### Tracker Requests breaking the site

1. altriagroupinc.tt.omtrdc.net/rest/v1/delivery

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

No

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
