### ISSUE TITLE
Broken Site: harborfreight.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#2059]
### URLs affected

harborfreight.com

### Description of Breakage

Mutliple blank space caused by a tracker

### Tracker Requests breaking the site

https://st.dynamicyield.com/st

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
