### ISSUE TITLE
Broken Site: foodfornet.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#2065]
### URLs affected

https://foodfornet.com/strongest-energy-drinks/

### Description of Breakage

social media widgets are not displayed

### Tracker Requests breaking the site

1. https://scripts.mediavine.com/tags/food-for-net.js
2. faves.grow.me
3. api.grow.me

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
