### ISSUE TITLE
Broken Site: ign.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#2068]
### URLs affected

https://www.ign.com/videos/square-enix-takes-140-million-hit-on-content-abandonment-losses-ign-daily-fix

### Description of Breakage

Switching videos lead the second one to stop playing after a few seconds. 
ima3 surrogate is causing he issue.

### Tracker Requests breaking the site

https://imasdk.googleapis.com/js/sdkloader/ima3.js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
