### ISSUE TITLE
Broken Site: kitchenaid.com

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#2070]
### URLs affected

https://www.kitchenaid.com/

### Description of Breakage

Sign-up for coupon element missing

### Tracker Requests breaking the site

https://whirlpool.tt.omtrdc.net/rest/v1/delivery

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
