### ISSUE TITLE
Broken Site: odyelectricvitality.com.au

### ISSUE THREAD

**Issue by icodebyamanda** [duckduckgo/privacy-configuration#2097]
### URLs affected

https://www.bodyelectricvitality.com.au/choosing-an-ibs-and-sibo-friendly-milk/

### Description of Breakage

elements missing: "more ideas", search and go back to the top

### Tracker Requests breaking the site

c.slickstream.com/app/2.13.88/app.js
c.slickstream.com/app/2.13.88/boot-loader.js
googletagmanager.com/gtag/js

### Affected Platforms

- [X] Browser Extensions
- [X] Android Browser
- [X] iOS Browser
- [X] macOS Browser
- [X] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
