### ISSUE TITLE
Broken Site: https://app.asana.com/0/1206777341262243/1207404495921706/f

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#2104]
### URLs affected

https://www.ghostlifestyle.com/pages/ghost-story

### Description of Breakage

Video doesn't play,[ internal issue](https://app.asana.com/0/1206777341262243/1207404495921706/f)

### Tracker Requests breaking the site

NA

### Affected Platforms

- [ ] Browser Extensions
- [X] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

None

### Verified on other browsers

None

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
