### ISSUE TITLE
Broken Site: grilledcheesesocial.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#2107]
### URLs affected

https://grilledcheesesocial.com/2022/05/11/bourdains-mortadella-sandwich

### Description of Breakage

Steps to reproduce:
1. Click the "Jump to Recipe" button.
2. Ensure the "Recommended" section with links to other recipes is linked directly under the "Recipe" section header.

Note: After the first time, take care to scroll back to the top of the page, clear all site cookies and reload the page before trying again. Otherwise the "Recommended" section won't show up.

### Tracker Requests breaking the site

`https://*.grow.me/*`

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
