### ISSUE TITLE
Broken Site: qvc.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#2109]
### URLs affected

https://www.qvc.com/paper-mario%3A-the-thousand-year-door---nintendoswitch.product.E321792.html

### Description of Breakage

"New to QVC? ..." coupon banner and "Watch Our Latest Livestreams" section is missing.

### Tracker Requests breaking the site

`https://*.monetate.net/*`

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
