### ISSUE TITLE
Broken Site: fsastore.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#2114]
### URLs affected

https://fsastore.com/adventure-medical-mountain-sunset-hiker-kit/40948.html

### Description of Breakage

"Frequently Bought Together" section near the bottom of the page is not populated with products.

### Tracker Requests breaking the site

`https://*.listrakbi.com/*`

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
