### ISSUE TITLE
Broken Site: bestbuy.com

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#2117]
### URLs affected

https://www.bestbuy.com/?intl=nosplash

### Description of Breakage

"Featured products for you" section near bottom of the website is missing.

### Tracker Requests breaking the site

1. `https://d.us.criteo.com/delivery/retailmedia`

### Affected Platforms

- [ ] Browser Extensions
- [ ] Android Browser
- [ ] iOS Browser
- [ ] macOS Browser
- [ ] Windows Browser

### Other Details

GPC also needs to be disabled.

### Tested without Privacy Protections

Yes

### Verified on other browsers

Yes

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
