### ISSUE TITLE
Authentication issue logging into teams.microsoft.com

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#242]
**Background**

We've had a number of site breakage issues for teams.microsoft.com for Chrome users that have downloaded the latest 2022.5.30 version of the extension.

Internal issue: https://app.asana.com/0/1200277586140538/1202373160744651/f

The following is a screenshot of the issue reproduced:
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/338988/171391780-ee666f63-b602-40df-9ee7-ee810c661915.png">

**Proposed plan of action**

- Disable 'cookie' protection specifically for tabs with teams.microsoft.com
- Investigate the issue further if there's a better mitigation we can use.

**Comment by SlayterDev** [comment]
Fixed in https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/1218
