### ISSUE TITLE
Authentication issue with start.me

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#245]
**Background**

https://twitter.com/startme/status/1532042141207343107

"Hello [@DuckDuckGo](https://twitter.com/DuckDuckGo)
, since yesterday people that have installed the DuckDuckGo Privacy extension are having problems staying logged in on [http://start.me](https://t.co/Sf0J6L2jzt). Do you have some documentation for this extension? We like to resolve this asap."

Cause this appears [also](https://github.com/duckduckgo/privacy-configuration/issues/242) to be caused by the cookie blocking feature.

**Proposed plan of action**

- Disable 'cookie' protection specifically for tabs with start.me
- Investigate the issue further if there's a better mitigation we can use.

**Comment by SlayterDev** [comment]
Fixed in https://github.com/duckduckgo/duckduckgo-privacy-extension/releases/tag/2022.6.1
