### ISSUE TITLE
Google Pay payment flow breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#281]
Some sites (e.g., scanlantheodore.com) experience breakage in the Google Pay payment flow option.

We've found that the following cookie domains need to be exempted in order to allow this flow to proceed:

- accounts.google.com
- pay.google.com
- payments.google.com

As an example of how to reproduce this breakage, try the following flow on us.scanlantheodore.com (last verified 2022-06-28):

1. add item to cart, go to cart and checkout
2. select the google pay option
3. enter account name, proceed
4. there is an error "Your browser has cookies disabled. Make sure that your cookies are enabled and try again."
    - → exception for "accounts.google.com" in the "cookie" protection mitigates this
5. after entering password, pay popup shows but flickers/reloads repeatedly
    - → exception for "pay.google.com" in the "cookie" protection mitigates the flickering, though the popup continues to show a loading spinner
    - → exception for "payments.google.com" in the "cookie" protection allows the payment option to load

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
