### ISSUE TITLE
Facebook unsupported useragent on iOS

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#297]
On iOS, when going to m.facebook.com, there is a banner at the top "Unsupported browser: You're using a browser that isn't supported by Facebook, so we've redirected you to a simpler version to give you the best experience."

<img src="https://user-images.githubusercontent.com/8598426/177526013-f9c8295a-e003-42fb-b774-0f03f069ab94.PNG" width=50% height=50%>

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
