### ISSUE TITLE
Bing maps breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#321]
Bing is a large provider of map functionality, and thus blocking certain requests to bing causes widespread breakage of interactive maps and other location-related functionality (e.g., location search boxes) on websites.

Some example pages known to experience location/maps breakage when blocking bing (last verified 2022-07-15):

- https://www.ups.com/dropoff?loc=en_US
  - map appears greyed out and cannot be interacted with
- https://www.bridgestonetire.ca/dealer/
  - location search box doesn't render; map doesn't render
- https://routeplanner.uk/
  - map doesn't render, instead the page is largely blank
- https://www.riteaid.com/
  - clicking "Your store"/"select store" in the top right does nothing
- https://www.harriscountyfemt.org/
  - map is greyed out and cannot be interacted with
- https://ohgo.com/akron
  - map does not render
- https://www.dhl.de/de/privatkunden/dhl-standorte-finden.html (last verified 2022-10-10)
  - map does not render
  - requests required:
    - `www.bing.com/maps/sdk/mapcontrol` (`script`) - initiator
    - `www.bing.com/rb/3z/jnc,nj/<hex-upper>.js` (`script`) (inconsistent)

The following is a summary of requests that we've found to cause high severity breakage:

- `www.bing.com/api/maps/mapcontrol`
  - required for other requests to initiate
- `www.bing.com/maps/sdkrelease/mapcontrol`
  - required for other requests to initiate
- `www.bing.com/rp/`
  - these requests are used for various parts of map functionality, as well as e.g., required to show the location search box on https://www.bridgestonetire.ca/dealer/
  - NOTE: these requests are found on Firefox
- `r.bing.com/rp/`
  - same as above, but these requests are found on Chrome rather than Firefox
- `www.bing.com/api/v6/Places/AutoSuggest`
  - required for location suggestions as one types

Example breakage on UPS:

<p float="left" align="middle">
<img src="https://user-images.githubusercontent.com/8598426/179484792-fd0e4c02-759d-4557-ae5d-86e3391a9aec.png" width=40% height=40%>
<img src="https://user-images.githubusercontent.com/8598426/179484864-145035db-b91f-41f9-8fd7-e40033ec9a67.png" width=40% height=40%>
</p>

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
