### ISSUE TITLE
🍪 Cookie Prompt Management usability issues

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#326]
This issue covers usability concerns caused by our cookie consent management (CPM) feature.

You can find more about how this privacy protection works in the [autoconsent](https://github.com/duckduckgo/autoconsent) repository.

### Terminology

- CPM = Cookie Prompt Management (our privacy protection)
- CMP = Consent Management Provider/Platform: software that provides (among other things) cookie pop-up functionality

### Types of breakage

The following outlines the typical forms of usability issues we can see with our CPM feature:

- (T.A) **prevented interaction**

  Sometimes our feature will handle CMPs in such a way that the site doesn't recognise the CMP has been handled. In these cases, the site may prevent further interaction.

- (T.B) **incorrect notice of management**

  Sometimes the CPM will indicate that cookies have been handled, even though they have not.

### Known cases

At the end of each example URL is the last date on which the issue has been verified.

- https://www.volkskrant.nl/ (2022-07-29)

  Breakage categories: **T.B** (incorrect notice)

  When navigating to the site, CPM reports that a cookie prompt has been managed, but the site immediately redirects to https://myprivacy.dpgmedia.nl/consent?siteKey=...&callbackUrl=https%3a%2f%2fwww.volkskrant.nl%2fprivacy-wall%2faccept%3fredirectUri%3d%252f and shows a CMP with a blurred background.

- https://www.kicker.de/ (2023-02-20)
  - (Android) page keeps reloaded when CPM enabled
  - https://github.com/duckduckgo/privacy-configuration/pull/691

- https://www.epojisteni.cz/ **T.A** (2023-03-10)
  - (Windows) interaction is broken (overlay prevents interacting with the page)
  - Asana: https://app.asana.com/0/1200277586140538/1204151514436943/f

- https://www.autotrader.co.uk/ **T.A** (2023-04-18)
  - (Android) cannot scroll
  - https://app.asana.com/0/1200277586140538/1204421509219519/f

- https://www.livescience.com/ (2023-05-08)
  - (Android) cannot scroll
  - https://app.asana.com/0/1200277586140538/1204522885984449/f

- https://www.hl.co.uk/ (2023-05-09)
  - Android,Windows - site locks up and shows grey overlay
  - https://app.asana.com/0/1200277586140538/1204559320711146/f

- https://bild.de (2023-05-26)
  - https://app.asana.com/0/1114857721287938/1204659919386666/f
  - screen freezes on load (iOS)
- https://ksta.de (2023-05-26)
  - https://app.asana.com/0/1114857721287938/1204659919386666/f
  - speculative, likely same as surrounding issues
- https://t-online.de (2023-05-26)
  - screen freezes on load (iOS)
  - https://app.asana.com/0/1114857721287938/1204659919386666/f

- https://derstandard.de/ (2023-05-26)
  - blurred page background with no foreground when CPM is enabled
- https://duden.de/ (2023-05-26)
  - page freezes for a considerable amount of time
- https://welt.de/ (2023-05-26)
  - page freezes after a short time, for a couple of seconds, then shows cookie prompt anyway

- https://www.tomsguide.com/ (2023-05-30)
  - site hangs for several seconds (tested UK region, US seems fine)
  - https://app.asana.com/0/1200277586140538/1204522885984554/f

- https://www.nationalgrid.co.uk/power-cut-information (2023-06-26)
  - screen is blurred and doesn't allow proceeding
  - https://app.asana.com/0/1200277586140538/1204522885984681/f

- https://www.motherdenim.com/ (2023-07-13)
  - can't scroll. content not loading on pages like https://www.motherdenim.com/collections/denim-cropped
  - https://app.asana.com/0/0/1205010991570492/f

-https://www.healthline.com (2023-07-19)
  - causes a full page ad
  - https://app.asana.com/0/inbox/11472677167854/1205090295531385/1205093920706731
  
- https://pcworld.com **T.A** (2023-07-28)
  - (Android) page freezes for several seconds
  - https://app.asana.com/0/1200277586140538/1204522885984854/f
- https://www.autotrader.co.uk/ **T.A** (2023-07-28)
  - (Android) page freezes for several seconds
  - https://app.asana.com/0/1200277586140538/1204522885984854/f
- https://www.autotrader.co.uk/ **T.A** (2023-07-28)
  - (Android) page freezes for several seconds
  - https://app.asana.com/0/1200277586140538/1204522885984854/f
- https://www.autotrader.co.uk/ **T.A** (2023-07-28)
  - (Android) page freezes for several seconds
  - https://app.asana.com/0/1200277586140538/1204522885984854/f
- https://www.larazon.es/ (2024-04-23)
  - If you click the "Rechazar todo” (reject all) button, they are rejected but the cookie popup doesn’t disappear. 
  - https://app.asana.com/0/1201844467387842/1207097434253108/f

### Other CMP providers with minor breakage

Minor breakage e.g., prompt might not show, but doesn't affect rest-of-site functionality.

- `cookiemanager.net` (2022-09-23)
- `osano.com` (2022-09-23)

# Active mitigations (other)

- https://github.com/duckduckgo/privacy-configuration/pull/521

# Related issues

- https://github.com/duckduckgo/privacy-configuration/issues/477
- https://github.com/duckduckgo/privacy-configuration/issues/344
- https://github.com/duckduckgo/privacy-configuration/issues/334

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
