### ISSUE TITLE
aternos.org adwall 

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#328]
On aternos.org, an adwall is often presented when attempting to "create a server". Note that this adwall can be bypassed through the "Continue with adblocker anyway" option, though the adwall reappears when the page is loaded again.

There is a description of the adwall in https://support.aternos.org/hc/en-us/articles/360034748092.

- example URL: https://aternos.org/server/
- Asana URL: https://app.asana.com/0/1200277586140538/1200336957310250/f

We have found that unblocking the following requests is sufficient to prevent the adwall:

Last verified 2022-09-12.

- `mp.4dex.io/prebid`
- `adx.adform.net/adx/openrtb`
- `htlb.casalemedia.com/cygnus`
- `bidder.criteo.com/cdb`
- `venatusmedia-d.openx.net/w/1.0/arj`
- `hbopenbid.pubmatic.com/translator`
- `secure.quantserve.com/quant.js`
- `prebid.a-mo.net/a/c`
- `hb-api.omnitagjs.com/hb-api/prebid/v1`
- `tlx.3lift.com/header/auction`

![image](https://user-images.githubusercontent.com/8598426/182816553-4dd74ad7-8638-451f-a09b-45728beab3d5.png)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
