### ISSUE TITLE
fastly.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#332]
This issue outlines breakage identified with requests associated with the `fastly.com` domain.

- https://www.outletcity.com/de-de/shop/herren/bademode-trends/ (last verified 2022-08-05)
  - product images do not render
  - mitigated by unblocking `outletcity.freetls.fastly.net/_ui/project/global/vendor.shared.xy93fbaf65.js`
- https://www.masslottery.com/ (last verified 2022-08-05)
  - site renders blank and does not proceed to load
  - **mitigated** by unblocking `mslc-prod-herokuapp-com.global.ssl.fastly.net/main.8736233213226195.js`
    - #333

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
