### ISSUE TITLE
privacymanager.io breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#334]
This issue outlines breakage for requests associated with the `privacymanager.io` domain.

- https://www.diepresse.com/ (last verified 2022-08-05)
  - cookie banner does not show (not managed)
- https://www.weer.nl/regenradar (last verified 2022-08-05)
  - cookie banner does not show (not managed)

#### https://pickmypostcode.com/ (last verified 2022-08-08)

- when clicking "customise" in the cookie banner at the bottom of the screen, nothing happens

- requests required
  - required for prompt to show
    - `gdpr-wrapper.privacymanager.io/gdpr/548dcb0e-b1a4-407e-8b4c-070476cb7142/gdpr-liveramp.js`
    - `cmp-consent-tool.privacymanager.io/latest/index.html`
    - `gdpr.privacymanager.io/latest/gdpr.bundle.js`
    - `cmp-consent-tool.privacymanager.io/latest/runtime.js`
    - `cmp-consent-tool.privacymanager.io/latest/polyfills.js`
    - `cmp-consent-tool.privacymanager.io/latest/vendor.js`
    - `cmp-consent-tool.privacymanager.io/latest/main.js`
    - `cmp-consent-tool.privacymanager.io/latest/847.js`
    - `cmp-consent-tool.privacymanager.io/latest/650.js`
    - `cmp-consent-tool.privacymanager.io/latest/defaultTheme.css`
    - `vendors.privacymanager.io/vendor-list.json`
  - `cmp-consent-tool.privacymanager.io/latest/605.js` (required for the "Manage Settings" option)
  - required for images/logos on prompt
    - `cmp-consent-tool.privacymanager.io/latest/icon-chevron-left.svg` (back button when in "Manage Settings")
    - `gdpr-wrapper.privacymanager.io/gdpr/548dcb0e-b1a4-407e-8b4c-070476cb7142/manager-logo.png` (main logo)

Additionally, on Android the following requests are required:

- `vendors.privacymanager.io/vendor-list.json`

#### https://www.geenstijl.nl/cookie-consent (last verified 2022-08-05)

- a pink overlay shows referencing cookies ("cookiewall"), and the site cannot be accessed.

- requests required
  - required for prompt to show:
  - `gdpr-wrapper.privacymanager.io/gdpr/af8f9e56-f698-46be-a9c5-f33a2932cb5d/gdpr-liveramp.js`
  - `gdpr.privacymanager.io/1/gdpr.bundle.js`
  - `cmp-consent-tool.privacymanager.io/latest/index.html`
  - `cmp-consent-tool.privacymanager.io/latest/runtime.js`
  - `cmp-consent-tool.privacymanager.io/latest/polyfills.js`
  - `cmp-consent-tool.privacymanager.io/latest/vendor.js`
  - `cmp-consent-tool.privacymanager.io/latest/main.js`
  - `cmp-consent-tool.privacymanager.io/latest/847.js`
  - `cmp-consent-tool.privacymanager.io/latest/650.js`
  - `cmp-consent-tool.privacymanager.io/latest/defaultTheme.css`
  - `vendors.privacymanager.io/vendor-list.json`
  - required for "Instellingen beheren" button to function
    - `cmp-consent-tool.privacymanager.io/latest/605.js`
  - required for images/logos on prompt:
    - `gdpr-wrapper.privacymanager.io/gdpr/af8f9e56-f698-46be-a9c5-f33a2932cb5d/manager-logo.png`
    - `cmp-consent-tool.privacymanager.io/latest/assets/icons/how-is-my-data-used.svg`
    - `cmp-consent-tool.privacymanager.io/latest/assets/icons/consent.svg`
    - `cmp-consent-tool.privacymanager.io/latest/assets/icons/cookie.svg`
    - `cmp-consent-tool.privacymanager.io/latest/icon-chevron-left.svg` (represents the "back" button)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
