### ISSUE TITLE
pdst.fm breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#338]
This issue outlines breakage for requests associated with the `pdst.fm` domain.

- https://podcasts.google.com/search/vergecast (last verified 2022-08-15)
  - clicking the play button on an episode yields a "This episode couldn't be played" error
  - resources of the form
    - `pdst.fm/e/chtbl.com/track/<SRID: podcast ID>/traffic.megaphone.fm/<RID: episode ID>.mp3`
- https://overcast.fm/+UUoBoQk5E (last verified 2022-08-15)
  - clicking the play button does not play audio and does not advance the ticker
  - resources of the form
    - `pdst.fm/e/<DOMAIN>/episodes/<GUID: episode ID>.mp3`
    - `pdst.fm/e/chtbl.com/track/<SRID: podcast ID>/traffic.megaphone.fm/<RID: episode ID>.mp3`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
