### ISSUE TITLE
privacy-center.org breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#339]
This issue outlines breakage for requests associated with the `privacy-center.org` domain.

- articles on https://www.telegraaf.nl/ (last verified 2022-08-15)
  - primary videos don't load
  - required requests
    - `sdk.privacy-center.org/<GUID>/loader.js`
    - `sdk.privacy-center.org/sdk.<HEX>.js`
    - `sdk.privacy-center.org/ui-gdpr-nl.<HEX>.js`
- https://www.bfmtv.com/lyon/replay-emissions/bonsoir-lyon/le-jt-de-bonsoir-lyon-du-12-08-2022_VN-202208120459.html (last verified 2022-08-15)
  - primary videos don't load
  - required requests
    - `sdk.privacy-center.org/<GUID>/loader.js`
    - `sdk.privacy-center.org/sdk.<HEX>.js`
    - `sdk.privacy-center.org/ui-gdpr-en.<HEX>.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
