### ISSUE TITLE
dhl.de map breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#340]
Blocking `c1.adform.net/serving/cookie/match` on https://www.dhl.de/de/privatkunden/dhl-standorte-finden.html prevents the "Proceed to maps" button from functioning (clicking the button does nothing), preventing the map from being accessible.

Last verified 2022-08-15.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
