### ISSUE TITLE
sky.com login breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#342]
Blocking `accounts.sky.com.edgesuite.net/assets/sky_common.js` on `sky.com` causes an issue where attempting to login yields an error after entering e-mail address. Note: as of 2023-03-07 this is `skyid.sky.com`.

Example URL: https://www.sky.com/signin

Last verified: 2023-03-07

Asana task:
- https://app.asana.com/0/1200223097357040/1202732214370631/f
- https://app.asana.com/0/1200223097357040/1204126961049031/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
