### ISSUE TITLE
privacy-mgmt.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#344]
This issue outlines breakage for requests associated with the `privacy-mgmt.com` domain.

- https://www.derstandard.de/consent/tcf/ (last verified 2022-08-16)
  - page renders blurred and cannot be interacted with, possibly with a banner than cannot be bypassed
- https://t3n.de/consent (last verified 2022-08-28)
  - cookie banner shows loading animation on proceed button, cannot be interacted with
- https://www.spiegel.de/auto/vw-id-buzz-video-test-mit-dem-elektrischen-bulli-remake-a-0c9b37a6-1edf-45dd-b8f3-9919bbd912aa (last verified 2022-09-09)
  - video shows a spinner and does not play
  - requests required
    - note that `sp-spiegel-de.spiegel.de` CNAMEs to `cdn-331.privacy-mgmt.com`
    - `sp-spiegel-de.spiegel.de/mms/v2/get_site_data` (`xmlhttprequest`) - initiator for other requests
    - `sp-spiegel-de.spiegel.de/wrapper/tcfv2/v2/gdpr/native-message/new-user` (`xmlhttprequest`) - initiator for other requests
    - `sp-spiegel-de.spiegel.de/index.html` (`sub_frame`) - initiator for other requests
    - `sp-spiegel-de.spiegel.de/Notice.0b008.js` - required for consent prompt to show
    - `sp-spiegel-de.spiegel.de/Notice.a2194.css` (`stylesheet`) - required for alignment of consent prompt
    - `sp-spiegel-de.spiegel.de/consent/tcfv2/consent/v2/18284/consent-all` (`xmlhttprequest`) - required for "accept all" to correctly function. After this, video can play
- https://www.mediaevent.de (last verified 2022-09-16)
  - clicking to manage cookies (in footer) has no effect
  - requests required:
    - `gdpr-tcfv2.sp-prod.net/wrapperMessagingWithoutDetection.js` - initiator
    - various `privacy-mgmt.com` requests
- https://www.computerworld.com/article/3673092/digital-whiteboards-next-must-have-tool-for-hybrid-teams.html (last verified 2022-09-16)
  - no cookie popup shows, preventing management of cookies
  - requests required:
    - `ccpa.sp-prod.net/ccpa.js` - initiator
    - `cmp.computerworld.com/mms/get_site_data` (`xmlhttprequest`) (CNAME to `message.sp-prod.net`) - initiator
    - `cmp.computerworld.com/mms/v2/message_url` (`xmlhttprequest`) (CNAME to `message.sp-prod.net`) - initiator
    - `ccpa-notice.sp-prod.net/` (`subdocument`) - initiator
    - `ccpa-notice.sp-prod.net/(polyfills|Notice).<hex>.(js|css)`
    - (various `privacy-mgmt.com` requests, some CNAMEd)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
