### ISSUE TITLE
pickfu.com login breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#346]
Going to https://www.pickfu.com/users/sign_in, entering an e-mail address + password and proceeding with the login yields a "Login failed" error.

Last verified 2022-08-17.

Asana task: https://app.asana.com/0/1200277586140538/1202803422112308/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
