### ISSUE TITLE
yotpo.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#348]
This issue outlines breakage for requests associated with the `yotpo.com` domain.

- https://www.liquid-iv.com/collections/all (last verified 2022-08-17)
  - upon page load, there is an error message "Something went wrong", and product images do not load
  - requests required:
    - `api.yotpo.com/products/LnbeeKL6s28RHA1yyH2eVS74IdnWrTCYyvfqvxn2/[0-9]+/bottomline`
- https://www.headkandypro.com/collections/bags-travel/products/travelista-hair-dryer (last verified 2022-08-17)
  - related items and reviews sections do not show
  - requests required:
    - `staticw2.yotpo.com/AfdZhtYzILmHx5dB7gDH1CfNm3PAzI1nAo8ENliG/widget.js`
      - initiator for other requests
    - `staticw2.yotpo.com/batch/app_key/AfdZhtYzILmHx5dB7gDH1CfNm3PAzI1nAo8ENliG/domain_key/6826852024390/widget/main_widget`
      - required for "other top rated products", and reviews sections to show
     - `cdn-yotpo-images-production.yotpo.com/Product/[0-9]+/[0-9]+/square.jpg`
       - product images for "other top rated products" section
     - `staticw2.yotpo.com/assets/yotpo-widget-font.woff`
       - rating stars, navigation chevrons
    - `api.yotpo.com/v1/widget/reviews`
      - required to post reviews
    - `api.yotpo.com/questions/send_confirmation_mail`
      - required to post questions
    - `api.yotpo.com/reviews/[0-9]+/vote/up`, `api.yotpo.com/reviews/[0-9]+/vote/up/true`, `api.yotpo.com/reviews/[0-9]+/vote/down`, `api.yotpo.com/reviews/[0-9]+/vote/down/true`
      - required for up/down voting reviews
- https://lancasterarchery.com/products/30-06-paper-tune-it-d-i-y-archery-paper-tuning-system (last verified 2022-08-17)
  - reviews section does not display
  - requests required:
    - `staticw2.yotpo.com/BvpwWeEeHfikewSPQZECpyoyQG2syCdyEBUQLQ5A/widget.js`
      - initiator for other requests
    - `staticw2.yotpo.com/batch/app_key/BvpwWeEeHfikewSPQZECpyoyQG2syCdyEBUQLQ5A/domain_key/6724299882682/widget/main_widget`
      - required for reviews section to display (not this will render grey without other requests)
    - `staticw2.yotpo.com/BvpwWeEeHfikewSPQZECpyoyQG2syCdyEBUQLQ5A/widget.css`
      - required for reviews to render
    - `staticw2.yotpo.com/assets/yotpo-widget-font.woff`
      - various icons (e.g., thumbs up/down)
    - `api.yotpo.com/v1/widget/reviews`
      - required for posting reviews
    - `api.yotpo.com/reviews/[0-9]+/vote/up`, `api.yotpo.com/reviews/[0-9]+/vote/up/true`, `api.yotpo.com/reviews/[0-9]+/vote/down`, `api.yotpo.com/reviews/[0-9]+/vote/down/true`
      - required for up/down voting reviews
- https://www.astrogaming.com/en-us/products/headsets/a10-gen-2.html (last verified 2022-09-27)
  - reviews don't show
  - requests required:
    - (in addition to above)
    - `staticw2.yotpo.com/batch/9rWlnYQZzR8lneVRjOB3bcNA70dLVgj7GfnBGhi5/a10-gen-2` (`xmlhttprequest`)
- https://www.kingarthurbaking.com/recipes/barista-biscotti-bites-recipe#review-section (last verified 2022-09-27)
  - reviews don't show
  - requests required:
    - `www.googletagmanager.com/gtm.js` (currently surrogate) - initiator
    - (various yotpo requests, already covered)
- https://usa.youswim.com/collections/all/products/verve-standard-waist-two-piece?variant=44987122909500 (2023-07-11)
  - images in reviews don't load
  - requests required:
    - `cdn-yotpo-images-production.yotpo.com`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
