### ISSUE TITLE
kxcdn.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#352]
This issue outlines breakage for requests associated with the `kxcdn.com` domain.

- https://saberforge.com/collections/lgt-sabers (last verified 2022-08-17)
  - product images don't render
- https://www.vetnpetdirect.com.au/collections/dog-beds (last verified 2022-08-17)
  - product images don't render
- https://www.skinnymixes.com/collections/keto-naturals (last verified 2022-08-23)
  - product images don't render
  - requests required
    - `searchanise-ef84.kxcdn.com/widgets.49763.min.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
