### ISSUE TITLE
baukjen.com chat widget breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#355]
https://www.baukjen.com/pages/sizing-guide - chat widget does not show. Without protections, the widget shows after some scrolling.

Last verified 2022-08-23

Unblocking `www.googletagmanager.com/gtm.js` allows the chat widget to eventually show.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
