### ISSUE TITLE
marketo.com, mktoweb.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#361]
This issue outlines breakage for requests associated with the `marketo.com` domain.

- https://www.constructionline.co.uk (last verified 2022-09-05)
  - clicking "Get in Touch" shows a blank form (main form content does not render, and instead shows site underneath)
  - requests required
    - `app-lon08.marketo.com/js/forms2/js/forms2.min.js`
      - initiator for other requests
    - `app-lon08.marketo.com/index.php/form/getForm`
      - required for form to render
- https://www.dailysignal.com/ (last verified 2022-09-13)
  - mailing list sign up (bottom of page) doesn't show
  - requests required:
    - `app-ab04.marketo.com/js/forms2/js/forms2.min.js`
    - `app-ab04.marketo.com/index.php/form/getForm`
    - `app-ab04.marketo.com/index.php/form/XDFrame` (`sub_frame`) - required for form submission
    - `app-ab04.marketo.com/index.php/leadCapture/save2` (`xmlhttprequest`) - required for form submission
- https://memorialhermann.org/ (last verified 2022-09-13)
  - mailing list sign up (in footer) doesn't show
  - requests required:
    - `app-ab09.marketo.com/js/forms2/js/forms2.min.js`
    - `app-ab09.marketo.com/index.php/form/getForm`
    - `app-ab09.marketo.com/index.php/form/getKnownLead`
    - `app-ab09.marketo.com/index.php/form/XDFrame` (`sub_frame`) - required for form submission
    - `app-ab09.marketo.com/index.php/leadCapture/save2` (`xmlhttprequest`) - required for form submission
- https://www.digikey.com/ (last verified 2022-09-13)
  - submission on mailing list form at bottom of page does not function
  - requests required:
    - `app-ab06.marketo.com//index.php/form/getForm`
- https://www.bayliner.com (last verified 2022-09-20)
  - contact form at bottom of page doesn't show
  - requests required:
    - `162-kuf-529.mktoweb.com/js/forms2/js/forms2.min.js` - initiator
    - `162-kuf-529.mktoweb.com/index.php/form/getForm` (`script`) - allows form to show, initiator
    - `162-kuf-529.mktoweb.com/index.php/form/XDFrame` (`subdocument`) - for form submission
    - `162-kuf-529.mktoweb.com/index.php/leadCapture/save2` (`xmlhttprequest`) - for form submission

#### See also

- https://github.com/duckduckgo/content-blocking-whitelist/pull/63

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
