### ISSUE TITLE
bazaarvoice.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#365]
This issue outlines breakage for requests associated with the `bazaarvoice.com` domain.

Example URLs:

- https://www.costco.com/.product.100696541.html (last verified 2022-09-06)
  - reviews section does not render
- https://www.scotts.com/en-us/products/lawn-food/scotts-turf-builder-triple-action-california (last verified 2022-09-06)
  - reviews section does not render
- https://zerowater.com/collections/all-water-filter-products/products/wall-mount-filtered-shower-head (last verified 2022-09-06)
  - reviews section does not render
  - "ask a question" section does not render
- https://www.targetoptical.com/to-us/8053672801354 (last verified 2022-09-08)
  - "recommended for you" / "recently viewed" elements don't appear above glasses (partway down page)
  - requests required
    - `static.curations.bazaarvoice.com/gallery/targetoptical/prod/loader.js`
- https://www.rei.com/product/110118/ust-paratinder-550-utility-cord-30 (last verified 2022-09-13)
  - reviews and Q&A sections don't show
  - requests required:
    - (various)
    - `display.ugc.bazaarvoice.com/static/rei-inc/main_site/1094/15372/en_US/stylesheets/screen.css` (`stylesheet`) - required for reviews section to show

Requests identified:

- `apps.bazaarvoice.com/deployments/.*/.*/production/en_US/bv.js` (script)
  - required for initiating other requests
- `apps.bazaarvoice.com/apps/reviews/reviews-[0-9.]+.js`
  - required for reviews to display
- `apps.bazaarvoice.com/deployments/.*/.*/production/en_US/reviews-config.js`
  - required for reviews to display
- `api.bazaarvoice.com/data/`
  - required for reviews to display
- `display.ugc.bazaarvoice.com/`
  - required for reviews to display

- `display.ugc.bazaarvoice.com/common/util/storage.htm` (sub_frame)
  - required for being able submit reviews on Costco (otherwise page does not redirect when clicking to make a review)

#### See also

- https://app.asana.com/0/0/1141114784677157/f
- https://app.asana.com/0/0/1178958315987018/f
- https://app.asana.com/0/0/1176531860173466/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
