### ISSUE TITLE
yandex.ru breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#366]
This issue outlines breakage for requests associated with the `yandex.ru` domain.

### Maps

- https://zmaps.net/company/arleta-dmv-8007770133 (last verified 2022-09-06)
  - map does not show above directions
  - requests required
    - `static-maps.yandex.ru/1.x/`
- https://rusneb.ru/catalog/000199_000009_008752333/ (last verified 2022-09-06)
  - map does not render in drop down
  - requests required
    - `api-maps.yandex.ru/2.0-stable/`
    - `api-maps.yandex.ru/2.0/combine`
- https://www.ucheba.ru/uz/51729 (last verified 2022-09-07)
  - clicking to show map instead gives a blank popup
  - required requests
    - `api-maps.yandex.ru/2.0-stable/`
    - `api-maps.yandex.ru/2.0/combine`
- https://rsa.worldorgs.com/catalog/cape-town/design-agency/graphic-design-house (last verified 2022-09-07)
  - map does not show on side pane
  - requests required
    - `api-maps.yandex.ru/2.1/`
      - required for map to show
    - `api-maps.yandex.ru/services/search/v2/`
      - required for search
    - `api-maps.yandex.ru/services/coverage/v2/`
      - required to show more information about a location when clicking on location name in expanded map
    - `api-maps.yandex.ru/services/search//v2/`
      - required to go to current location when clicking on the "this location" arrow (top-left in expanded view)

### Video

- https://dzen.ru/video/watch/62fde6b26afa9c424f0730b4 (last verified 2022-09-19)
  - video doesn't render, play icon doesn't render
  - requests required:
    - `strm.yandex.ru/get/[^/]+` (`xmlhttprequest`) - for video to show/play
- https://tvrain.ru/live/womenabove/ (last verified 2022-09-19)
  - video doesn't play
  - requests required:
    - `frontend.vh.yandex.ru/player/[0-9]+` (`subdocument`)
  - adwall on video
  - requests required:
    - `strm.yandex.ru/vh-special-converted/vod-content/.*` (`xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
