### ISSUE TITLE
💬 Chat widget breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#367]
This issue summarises breakage associated with chat widgets.

- https://github.com/duckduckgo/privacy-configuration/issues/479
- https://github.com/duckduckgo/privacy-configuration/issues/430
- https://github.com/duckduckgo/privacy-configuration/issues/422
- https://github.com/duckduckgo/privacy-configuration/issues/416
- https://github.com/duckduckgo/privacy-configuration/issues/413
- https://github.com/duckduckgo/privacy-configuration/issues/412
- https://github.com/duckduckgo/privacy-configuration/issues/411
- https://github.com/duckduckgo/privacy-configuration/issues/410
- https://github.com/duckduckgo/privacy-configuration/issues/409
- https://github.com/duckduckgo/privacy-configuration/issues/408
- https://github.com/duckduckgo/privacy-configuration/issues/407
- https://github.com/duckduckgo/privacy-configuration/issues/379
- https://github.com/duckduckgo/privacy-configuration/issues/355
- https://github.com/duckduckgo/privacy-configuration/issues/900
- https://github.com/duckduckgo/privacy-configuration/issues/1416
- #1643
- https://github.com/duckduckgo/privacy-configuration/issues/1111

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
