### ISSUE TITLE
Log in with Amazon breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#368]
- https://www.budget.com/en/home (last verified 2022-09-07)
  - clicking the "Login with Amazon" button does nothing
  - requests required
    - `api-cdn.amazon.com/sdk/login1.js`
- https://www.youtv.de/ (last verified 2022-09-07)
  - clicking the "Login with Amazon" button does nothing
  - requests required
    - `api-cdn.amazon.com/sdk/login1.js` (required for button to be interactive)
    - `na.account.amazon.com/ap/oa/proxy.html` (sub_frame - after account confirmation, without this request the subdocument will remain and login will not proceed)
- https://www.solar.com/login (last verified 2022-09-07)
  - clicking the "Login with Amazon" button does nothing
  - requests required
    - `api-cdn.amazon.com/sdk/login1.js` (required for button to be interactive)
    - (...) - frame shows a 400 bad request error, mitigation not yet identified

#### See also

- https://app.asana.com/0/0/1141114784677151/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
