### ISSUE TITLE
Reddit breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#369]
- https://forums.spacebattles.com/threads/ace-combat-7-discussion-thread.366416/page-160?post=61185991#post-61185991 (last verified 2022-09-06)
  - Reddit embed is hard to read and textual
  - requests required
    - `www.redditstatic.com/reddit-embed.2sfteBYriHU.css` - (stylesheet) allows embed background to render
    - `www.redditstatic.com/reddit-embed.7jSB6XsbXeE.js` - allows the upvote/comment counts to render at the bottom of the embed
    - `www.redditstatic.com/circled-snoo-1x.png` - allows the Reddit logo to render in top right of embed
- https://www.theverge.com/2016/5/19/11717476/reddit-post-embed-feature-news-media (last verified 2022-09-08)
  - embedded Reddit comments don't render
  - requests required
    - `www.reddit.com/comments/4k32b7.json` (xmlhttprequest) (and similar requests)

- https://deathstranding.fandom.com/wiki/Death_Stranding_Wiki (last verified 2022-09-06)
  - Reddit comments in side pane (right) don't render
  - requests required
    - `www.reddit.com/r/DeathStranding.json`

- https://www.theverge.com/ (2023-05-27)
  - Reddit embeds appear blank
  - requests required:
    - `embed.reddit.com/widgets.js`
    - `embed.reddit.com/r/<pathcomp>/comments/<pathcomp>/<pathcomp>/`
    - `www.redditstatic.com/shreddit/`

- https://www.gamingbible.com/news/red-dead-redemption-2-players-grim-animal-detail-760635-20230525 (2023-05-27)
  - Reddit embeds appear blank
  - requests required:
    - `embed.reddit.com/r/<pathcomp>/comments/<pathcomp>/<pathcomp>/`
    - `www.redditstatic.com/shreddit/`

#### See also

- https://app.asana.com/0/0/1142101072811450/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
