### ISSUE TITLE
Hubspot form breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#370]
- https://www.cm-alliance.com/wisdom-of-crowds-bengaluru-oct-2019-registration (last verified 2022-09-08)
  - cannot submit form
  - requests required
    - `forms.hsforms.com/submissions/v3/public/submit/formsnext/multipart/1602894/66a492bb-81b9-4f21-83d2-6e58c02145a9` (sub_frame)
      - without this, clicking the submit button does nothing
    - `forms.hsforms.com/emailcheck/v1/json-ext` (xmlhttprequest) (not required for form submission)
      - without this, live checking of e-mail validity does not function
- https://blog.prepscholar.com/ (last verified 2022-09-08)
  - e-mail submission button does not function (mailing list sign up)
  - requests required
    - `forms.hsforms.com/submissions/v3/public/submit/formsnext/multipart/360031/974d38ff-dbac-407c-b5c7-6cdccb7a9ef` (sub_frame)
- https://blog.yaleappliance.com/ (last verified 2022-09-08)
  - e-mail submission button does not function (mailing list sign up)
  - requests required
    - `forms.hsforms.com/submissions/v3/public/submit/formsnext/multipart/91694/1bf50b36-9979-4b1a-a26f-8f3a497d1921` (sub_frame)
- https://www.slintel.com/demo (last verified 2022-09-08)
  - cannot submit form
  - requests required
    - `forms.hsforms.com/submissions/v3/public/submit/formsnext/multipart/7119044/e90858e5-e45c-4ded-aae9-8815ec9f2baa` (sub_frame)
- https://greenyplus.com/ (2024-02-09)
  - "Zum Newsletter ammelden" form doesn't open
  - requests required:
    - various `hubspot.com/web-interactives*`

#### See also

- https://app.asana.com/0/0/1141733122928361/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
