### ISSUE TITLE
Mailchimp breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#372]
- https://www.emmettandstone.co.uk/ (last verified 2022-09-08)
  - clicking the "Latest News" e-mail subscription button has no effect (top right)
  - requests required
    - `downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js` - initiator for other requests
    - `mc.us3.list-manage.com/subscribe/form-settings` - initiator for other requests
    - `downloads.mailchimp.com/js/signup-forms/popup/unique-methods/079edf446cb10dc5225dfe31714cd182fefedaf3/popup.js` - initiator for other requests
    - `downloads.mailchimp.com/css/signup-forms/popup/079edf446cb10dc5225dfe31714cd182fefedaf3/common.css` (`stylesheet`) - for form layout
    - `downloads.mailchimp.com/css/signup-forms/popup/079edf446cb10dc5225dfe31714cd182fefedaf3/modal.css` (`stylesheet`)
    - `downloads.mailchimp.com/css/signup-forms/popup/079edf446cb10dc5225dfe31714cd182fefedaf3/layout-2.css` (`stylesheet`)
    - `mc.us3.list-manage.com/subscribe/form-post-json` - required for submitting form (form submit button has no action without this)
- https://www.trustedreviews.com/ (last verified 2022-09-12)
  - hovering over the "sign up" button for the mailing list sign up form does not alter the cursor to indicate it is clickable
  - requests required:
    - `cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
