### ISSUE TITLE
cnn.com video breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#373]
- https://go.cnn.com/ (last verified 2022-09-08)
  - video doesn't play (spinner spins or a while, then resets)
  - requests required
    - `c.amazon-adsystem.com/aax2/apstag.js`
    - `prebid.adnxs.com/pbc/v1/cache` (`xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
