### ISSUE TITLE
fwmrm.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#374]
- https://www.nba.com/watch/video/fiba-eurobasket-2022-sept-8 (last verified 2022-09-09)
  - video does not play
  - requests required
    - `mssl.fwmrm.net/libs/adm/6.22.1/AdManager.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
