### ISSUE TITLE
gemius.pl breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#376]
- https://wiadomosci.wp.pl/co-z-psami-krolowej-elzbiety-ii-jest-komunikat-6811372992547424a (last verified 2022-09-12)
  - adwall appears which reappears on reload
  - requests required:
    - `wp.hit.gemius.pl/xgemius.js`
- https://sport.tvp.pl/62663851/polska-ukraina-na-zywo-mecz-18-finalu-eurobasketu-transmisja-online-live-stream-11092022-gdzie-ogladac-mecz-koszykowki (last verified 2022-09-12)
  - adblock warning and video does not load
  - requests required:
    - `gapl.hit.gemius.pl/gplayer.js`
    - `pro.hit.gemius.pl/gstream.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
