### ISSUE TITLE
polldaddy.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#378]
- https://www.mariowiki.com/Main_Page (last verified 2022-09-12)
  - community poll does not show
  - requests required:
    - `secure.polldaddy.com/p/11180992.js` - required for poll to show
    - `polls.polldaddy.com/vote-js.php` - required for vote button to function
- https://roserambles.org/ (last verified 2022-09-12)
  - rating at top of page doesn't show
  - requests required:
    - `polldaddy.com/js/rating/rating.js` - initiator for other requests
    - `polldaddy.com/ratings/rate.php` - initiator for other requests
    - `polldaddy.com/images/ratings/star-yellow-sml.png` - required for stars to render
    - `polldaddy.com/images/ratings/info.png` - required for info icon
    - `polldaddy.com/ratings/rating-results.php` - required for interacting with info icon
    - `polldaddy.com/images/ico-rating-close.png` - close icon for page from expanding info
    - `polldaddy.com/favicon@2x.png` - "create own rating" icon in info page
- https://www.reddeeradvocate.com/ (last verified 2022-09-12)
  - reader poll does not show (partway down page)
  - requests required:
    - `secure.polldaddy.com/p/11194141.js` - required for poll to show
    - `polls.polldaddy.com/vote-js.php` - required for vote button to function
- https://www.speedcafe.com/ (last verified 2022-09-12)
  - poll does not show when clicking vote
  - requests required:
    - `static.polldaddy.com/p/11197695.js` - required for poll to show

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
