### ISSUE TITLE
tiqcdn.com breakage (Tealium)

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#379]
- https://bleacherreport.com/houston-texans (last verified 2022-09-12)
  - broken Tweet embeds
  - requests required:
    - `tags.tiqcdn.com/utag/bleacherreport/main/prod/utag.js` - initiator for other requests
    - `tags.tiqcdn.com/utag/bleacherreport/main/prod/utag.44.js` - for tweet to render
- https://store-us.vmware.com/upgrade-from-parallels-and-save-on-vmware-fusion (last verified 2022-09-12)
  - live chat button doesn't show
  - requests required:
    - `tags.tiqcdn.com/utag/vmware/magento-privacy/prod/utag.js` - initiator for other requests
    - `tags.tiqcdn.com/utag/vmware/magento-privacy/prod/utag.641.js` - for chat button to show + load
- https://www.bloomingdales.com/account/signin (2023-05-30)
  - https://app.asana.com/0/0/1204670471114497/f
  - "could not connect to server" error when attempting to sign in
  - `tags.tiqcdn.com/utag/bcom/main/prod/utag.js` + `fingerprintingCanvas`
- https://www.chilis.com/menu/appetizers/chicken-bacon-ranch-quesadillas (2023-05-30)
  - clicking "start order" has no effect
  - https://app.asana.com/0/0/1204670471114497/f
  - `tags.tiqcdn.com/utag/brinker/chilis.com/prod/utag.js`
- https://outlet.asics.com/gb/en-gb/gel-kayano-28/p/1011B189-403.html?size=7.5&width=Standard (2023-06-21)
  - reviews don't show, review stars don't show above product
  - in addition to Tealium, requires greylabeldelivery for reviews section
  - requires `visitor-service-us-east-1.tealiumiq.com/asics/main/<hex>` for review stars (somewhat flakey)
- https://www.sage.com/en-us/sage-business-cloud/intacct/
  - clicking 'take a product tour' does nothing
- https://www.politico.com/news/2023/10/09/israel-seeks-weapons-missiles-artillery-from-us-00120587
  - newsletter sign up form missing
- https://talkmobile.co.uk/contact-us
  - chat support widget missing
- https://www.sportsmansguide.com/product/index/bates-men039s-tactical-sport-2-side-zip-tactical-boots
  - product reviews missing
- https://github.com/duckduckgo/privacy-configuration/issues/798
- https://github.com/duckduckgo/privacy-configuration/issues/1255
- https://github.com/duckduckgo/privacy-configuration/issues/1334
- https://github.com/duckduckgo/privacy-configuration/issues/1344
- https://github.com/duckduckgo/privacy-configuration/issues/1353
- https://github.com/duckduckgo/privacy-configuration/issues/1382

Due to the wide array of site breakage issues caused by blocking requests to tags.tiqcdn.com, we are unblocking requests to `tags.tiqcdn.com/utag/` everywhere. All other protections will still apply.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
