### ISSUE TITLE
ravenjs.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#380]
- https://store.bitdefender.com/order/checkout.php (last verified 2022-09-12)
  - page renders blank
  - requests required:
    - `cdn.ravenjs.com/3.26.2/angular/raven.min.js`
- https://engine.apollographql.com/user-settings (last verified 2022-09-12)
  - "error loading settings"
  - requests required:
    - `cdn.ravenjs.com/3.22.1/raven.min.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
