### ISSUE TITLE
cdn-apple.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#381]
- https://www.fooducate.com/ (last verified 2022-09-12)
  - going to log in, then clicking option to sign in with Apple does nothing
  - requests required:
    - `appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
