### ISSUE TITLE
hdliveextra-a.akamaihd.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#382]
- https://www.nbcsports.com/video/what-are-dallas-cowboys-options-following-dak-prescotts-injury (last verified 2022-09-12)
  - video does not show, instead some template code shows
  - requests required:
    - `hdliveextra-a.akamaihd.net/HD/scripts/pdk6/v1.8/(config|modules)/*` (unknown exact requests)
    - `hdliveextra-a.akamaihd.net/HD/scripts/pdk6/v1.8/css/nbcsports.css` - for better display of pending video
    - `hdliveextra-a.akamaihd.net/HD/i/video_sports/*` - for video to play
    - `hdliveextra-a.akamaihd.net/HD/scripts/ads.js` - adwall
    - `pdk.theplatform.com/pdk6/next/pdk/player.js` - required for video to play
- https://www.golfchannel.com/news/10-million-purse-payout-2022-us-womens-open (last verified 2022-09-12)
  - video doesn't load
  - requests required:
    - same as nbcsports.com, but `v1.7` instead of `v1.8`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
