### ISSUE TITLE
xhcdn.com breakage [NSFW]

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#383]
:warning: **WARNING: This section contains NSFW adult sites.** :warning:

:warning:  Requests to the `xhcdn.com` domain are primarily associated with NSFW sites.

- [NSFW SITE](https://xhamster.com) (last verified 2022-09-12)
  - images and majority of content don't render
  - requests required:
    - `xhcdn.com/*` (`script`, `image`, `media`) (unknown/all)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
