### ISSUE TITLE
developers.google.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#384]
- https://www.zipformplus.com/ (last verified 2022-09-12)
  - site doesn't load
  - required requests:
    - `developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js`

Some more examples on https://publicwww.com/websites/%22https%3A%2F%2Fdevelopers.google.com%2Fmaps%2Fdocumentation%2Fjavascript%2F%22/

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
