### ISSUE TITLE
adobedtm.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#385]
- https://www.bjs.com/product/mms-snickers-skittles-and-more-chocolate-candy-bars-bulk-full-size-halloween-candy-30-ct/281077 (last verified 2022-09-13)
  - main page content does not render
  - requests required:
    - `assets.adobedtm.com/c3ed03742aaa/749e52fdc16c/launch-1efc4081e9c9.min.js`
- https://www.fedex.com/fedextrack/system-error?trknbr=test (last verified 2022-09-29)
  - chat widget/assistant does not show
  - requests required:
    - `assets.adobedtm.com/686b8f0c4520/a46df9c77975/launch-b5423a732003.min.js` - initiator
    - `assets.adobedtm.com/686b8f0c4520/a46df9c77975/<hex-lower>/RC<hex-lower>-source.min.js`
- https://github.com/AdguardTeam/AdguardFilters/issues/71786 (2023-05-25)
  - cannot scroll past first page
- https://photos.shutterfly.com/library (2023-05-30)
  - gets stuck at "Loading Photos..." (doesn't proceed past spinner)
  - `assets.adobedtm.com/528526b3f782/ddfab9399b13/launch-1480b4cd5321.min.js`
- https://www.kohls.com/myaccount/kohls_login.jsp (2023-06-01)
  - login button doesn't have any effect
  - `assets.adobedtm.com/6d2e783bbfe3/c0c47c5c96c6/launch-b2dd4b082ed7.min.js`
- https://www.vineyardvines.com/ (2023-06-02)
  - page loads blank
  - `assets.adobedtm.com/launch-EN21e80d3a727846b899ca33ba56352232.min.js`
- https://support.lenovo.com/us/en/contact-us (2023-06-02)
  - `assets.adobedtm.com/498114d772a9/6d11747b73d1/launch-ENf21e1fe3b8f547fd9e6c8ae1af4b8762.min.js`
- https://www.safeway.com/shop/product-details.188570015.html (2023-06-02)
  - "most popular" section gets stuck loading, same with reviews
  - `assets.adobedtm.com/launch-ENd8a7ca47a5e943c9915bbea04a4d1b05.min.js`
- https://www.harley-davidson.com/us/en/motorcycles/road-glide-limited.html (2023-06-15)
  - page doesn't render. Slightly improved when adobedtm is not blocked
- https://auspost.com.au/ (2023-06-15)
  - clicking "log in" has no effect (does not show account options)
- https://www.jewelosco.com/shop/search-results.html (2023-06-21)
  - after searching, shows a spinner and doesn't load the product images

Tags: adobe, adobedtm

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
