### ISSUE TITLE
microsofttranslator.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#386]
- https://tradukka.com/translate/en/ (last verified 2022-09-13)
  - translate feature doesn't work (shows loading dots)
  - requests required:
    - `ssl.microsofttranslator.com/ajax/v2/toolkit.ashx`
    - `api.microsofttranslator.com/v2/ajax.svc/TranslateArray`
- (any non-English site in the Edge browser) (last verified 2022-09-13)
  - for example, https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal
  - attempting to use the built-in translation feature (URL bar on right-hand side, translate) results in an error
  - requests required:
    - `api.cognitive.microsofttranslator.com/translate` (`xmlhttprequest`)

#### See also

- https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/464

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
