### ISSUE TITLE
apple.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#387]
- https://www.balkanweb.com/ (last verified 2022-09-13)
  - "download on the app store" icon doesn't render
  - requests required:
    - `linkmaker.itunes.apple.com/en-gb/badge-lrg.svg`
- https://www.zacks.com/ (last verified 2022-09-13)
  - "download on app store" image doesn't render (near bottom of page, on right)
  - requests required:
    - `linkmaker.itunes.apple.com/assets/shared/badges/en-us/appstore-lrg.svg`
- https://freedomfirstnetwork.com/ (last verified 2022-09-15)
  - podcasts ("our lineup" section) don't show
  - requests required:
    - `embed.podcasts.apple.com/.*` (various requests)
    - `amp-api.podcasts.apple.com/.*` (various requests)
    - `js-cdn.music.apple.com/.*` (various requests)
- `https://www.themuscleprogram.com/yoga-for-bodybuilders/` (last verified 2022-09-15)
  - apple music embed does not show (right hand side, partway down page)
  - requests required:
    - `embed.music.apple.com/us/album/heavy-metal-workout/1086091310` (`subdocument`) - initiator
    - `js-cdn.music.apple.com/.*` (various requests)
    - `embed.music.apple.com/.*` (various requests)
    - `amp-api.music.apple.com/.*` (various requests)
    - `xp.apple.com` (various requests)
    - `audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/.*` (`media`) - for playing audio

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
