### ISSUE TITLE
Google adwall / ads breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#388]
- https://www.openculture.com/ (last verified 2022-09-13)
  - adwall appears after a few seconds on page load
  - requests required:
    - `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` (currently surrogate)
- https://www.laprensa.hn/honduras/honduras-lluvias-merman-pero-hermine-avanza-y-traera-mas-precipitaciones-GJ10191700 (last verified 2022-09-23)
  - news video doesn't play
  - requests required:
    - `tpc.googlesyndication.com/pagead/js/loader21.html` (`subdocument`) - after a few seconds the video/reel will play
- https://rumble.com/vox9rz-ep.-2622b-a-year-is-almost-up-nobody-playing-the-game-gets-a-free-pass-nobo.html (last verified 2022-09-23)
  - after clicking to play video, shows a loading bar with no indicator of how long the loading will take (can take many seconds)
  - requests required:
    - `tpc.googlesyndication.com/pagead/js/loader21.html` (`subdocument`) - shows ad + option to skip
- https://www.hindustantimes.com (last verified 2023-02-07)
  - adwall which forces page refresh
  - requests required:
    - `ads.pubmatic.com/AdServer/js/pwt/156370/2494/pwt.js`
- https://zefoy.com/ (2023-08-14)
  - adwall which prevents access to the site
  - https://app.asana.com/0/1200277586140538/1205265226106808
  - various `googlesyndication.com` requests
- https://play.luckylandslots.com/loader (2023-11-07)
  - https://app.asana.com/0/1200277586140538/1205889100396677
  - adwall message on Firefox
  - `pagead2.googlesyndication.com/pagead/show_ads.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
