### ISSUE TITLE
Discord breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#389]
- https://warhammer40k.fandom.com/wiki/Warhammer_40k_Wiki (last verified 2022-09-13)
  - Discord panel doesn't show (right hand side, below "our apps")
  - requests required:
    - `discord.com/widget` (`sub_frame`) - initiator for other requests
    - `discord.com/assets/e33e6e9d9de3d3040d8b.js` - for panel to show
    - `discord.com/assets/index.693fb6cb383c52b4acb1.css` - for panel to show
    - `discord.com/api/guilds/443469289610149888/widget.json` (`xmlhttprequest`) - for member count + member list to show
    - `cdn.discordapp.com/widget-avatars/.*/.*` (`image`) - for member avatar images
    - `discord.com/assets/8f20d57d7d0ea34489dcdd432437f71c.svg` - Discord logo
    - `discord.com/assets/746a4f241e03deffc59b08c5650cf458.woff` (`font`) - font/alignment
    - `discord.com/assets/32c4f766e4892c054dfd367dbe0fc6dc.woff` (`font`) - font/alignment
- https://swtorista.com/ (last verified 2022-09-13)
  - showcase image doesn't render (top right)
  - requests required:
    - `cdn.discordapp.com/attachments/783793672482586664/1018887603279368222/unknown.png`
- https://swglegends.com/ (last verified 2022-09-13)
  - various background images don't show in community section
  - requests required:
    - `cdn.discordapp.com/attachments/[0-9]+/[0-9]+/.*.(png|PNG)` (various `image` requests)
- https://aiming.pro/wrist-aiming-vs-arm-aiming-in-fps-games (last verified 2022-09-13)
  - shows incorrect online member count (1000) (left pane)
  - requests required:
    - `discordapp.com/api/guilds/408972316756803585/widget.json` (`xmlhttprequest`)
- https://sourcebincc.net/ (last verified 2022-09-13)
  - Netflix icons don't render
  - requests required:
    - `media.discordapp.net/attachments/933299130162356244/940448172415803422/netflix.png`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
