### ISSUE TITLE
bigcommerce.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#390]
- https://store.almanac.com/buy-old-farmers-almanac (last verified 2022-09-03)
  - barely any content renders
  - requests required:
    - `cdn11.bigcommerce.com/<id>/images/stencil/.*` (`image`, `imageset`) - various image assets
    - `cdn11.bigcommerce.com/<id>/stencil/<id>/css/theme-<id>.css` - layout
    - (various `script` requests) - required for interaction, e.g., switching between product images
- https://www.renogy.com/ (last verified 2022-09-13)
  - various content images do not render; banner appears with no context (just the "x")
  - requests required:
    - `store-fhnch.mybigcommerce.com/content/images/popup1.jpg` - for popup image
    - various `store-fhnch.mybigcommerce.com/content/*` `image` requests - images on page

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
