### ISSUE TITLE
highcharts.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#391]
- https://socialblade.com/ (last verified 2022-09-13)
  - YouTube embed doesn't play (clicking has no effect)
  - requests required:
    - `code.highcharts.com/highcharts.js`
- https://www.bestplaces.net/ (last verified 2022-09-13)
  - interactive population graph near bottom of page does not show
  - requests required:
    - `code.highcharts.com/highcharts.js`
    - `code.highcharts.com/modules/heatmap.js`
    - `code.highcharts.com/modules/tilemap.js`
- https://injuryfacts.nsc.org/work/work-overview/work-safety-introduction/ (last verified 2022-09-13)
  - embedded graphs don't render
  - requests required:
    - `cloud.highcharts.com/inject/.*/` (`script`)
    - `code.highcharts.com/*` (`script`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
