### ISSUE TITLE
auth.adobe.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#392]
- https://www.nbc.com/ (last verified 2022-09-13)
  - login options don't show (top right), replaced with a spinner
  - requests required:
    - `entitlement.auth.adobe.com/entitlement/v4/AccessEnabler.js`
    - `sp.auth.adobe.com/entitlement/v4/AccessEnablerProxy.html` (`sub_frame`)
    - `sp.auth.adobe.com/entitlement/v4/AccessEnablerProxy.js`
    - `sp.auth.adobe.com/o/client/register` (`xmlhttprequest`)
    - `sp.auth.adobe.com/o/client/token` (`xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
