### ISSUE TITLE
demdex.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#393]
- https://www.homedepot.com/auth/view/createaccount/diy (last verified 2022-09-14)
  - "technical issue" error after submitting account creation
  - requests required:
    - `dpm.demdex.net/id` (`xmlhttprequest`)
- (last verified 2022-10-10)
  - clicking button on "activate Bing maps" popup doesn't have any effect
  - requests required:
    - `dpm.demdex.net/id` (`xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
