### ISSUE TITLE
bolt.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#395]
- https://www.benefitcosmetics.com/en-gb/cart (last verified 2022-09-14)
  - (after adding items to cart)
  - bolt checkout button doesn't show (below estimated total)
  - requests required:
    - `connect.bolt.com/connect.js` - initiator for other requests
    - `connect.bolt.com/v1/checkout_button` (`xmlhttprequest`, there is also `object`, but this doesn't appear to be required)
    - for functionality of button:
      - `connect.bolt.com/2582031/build/checkout_iframe_split.html` (`subdocument`) - initiator for other requests
      - `connect.bolt.com/v1/merchant` (`xmlhttprequest`) - for showing checkout frame
      - `connect.bolt.com/2582031/build/dd900fce6d6ee70528c0-main-vendor.js` - for showing checkout frame
      - `connect.bolt.com/2582031/build/02546539a75c55a02a98-main-split.js` - for showing checkout frame
      - `api.bolt.com/v1/orders/<id>` (`xmlhttprequest`) - for checkout frame main content
      - `img.bolt.com/x76/merchants/Benefit_Cosmetics_UK_logo_1631025605923589563.png` (`image`) - merchant logo in checkout frame

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
