### ISSUE TITLE
trustedshops.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#396]
- https://www.castlecameras.co.uk/ (last verified 2022-09-14)
  - "trusted shops" widget (shows a trust/review score) doesn't show (bottom left)
  - requests required:
    - `widgets.trustedshops.com/js/X2C156A7358BCDDF1064E7587B58E2D69.js` - initiator for other requests
    - `widgets.trustedshops.com/assets/trustbadge.js`
- https://www.12voltplanet.co.uk/ (last verified 2022-09-14)
  - "trusted shops" widget doesn't show
  - requests required:
    - `widgets.trustedshops.com/js/X746EEB848F3C5462386F7642A45D62D8.js`
    - `widgets.trustedshops.com/assets/trustbadge.js`
    - `widgets.trustedshops.com/assets/images/trustmark_120x120.png` - trusted shops trustmark icon in widget
- https://www.fritz-berger.de/ (last verified 2022-09-14)
  - trusted shops content doesn't render in footer of page
  - requests required:
    - `legal-images.trustedshops.com/Rechtspartner-Logo.png` - required for padlock trusted shops image
    - `widgets.trustedshops.com/js/XFA9EAE1212C1E5B8203C5506C1C258D2.js` - for trusted shops badge
    - `widgets.trustedshops.com/assets/trustbadge.js` - for trust badge
    - `widgets.trustedshops.com/assets/images/trustmark_120x120.png` - for logo in badge
    - `widgets.trustedshops.com/assets/images/trustmark_60x60.png` - logo in expanded badge (click on badge)
    - `widgets.trustedshops.com/assets/images/shield-simplified.svg` - shield icon in expanded badge
    - reviews at bottom of footer:
      - `api.trustedshops.com/rest/public/v2/shops/XFA9EAE1212C1E5B8203C5506C1C258D2/quality/reviews.json` - summary of reviews (score)
      - `widgets.trustedshops.com/reviews/tsSticker/tsSticker.js` - initiator
      - `gw1.api.trustedshops.com/rest/internal/v2/shops/XFA9EAE1212C1E5B8203C5506C1C258D2/reviews.json`
      - `gw1.api.trustedshops.com/rest/internal/v2/shops/XFA9EAE1212C1E5B8203C5506C1C258D2/quality/reviews.json`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
