### ISSUE TITLE
powerreviews.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#397]
- https://www.pgatoursuperstore.com/flat-front-7-fashion-golf-short-with-active-waistband/2000000002862.html (last verified 2022-09-14)
  - when attempting to change product size/colour, a semi-transparent overlay will appear, blocking interaction with the page
  - requests required:
    - `ui.powerreviews.com/stable/4.0/ui.js`
  - reviews/q&a section doesn't load
  - requests required:
    - `ui.powerreviews.com/stable/4.0/ui.js` - initiator
    - `ui.powerreviews.com/tag-builds/10377/4.0/display.engine.js`
    - `display.powerreviews.com/m/65932/l/en_US/product/2000000002862/reviews` (`xmlhttprequest`) - reviews section
    - `display.powerreviews.com/m/65932/l/en_US/product/2000000002862/questions` (`xmlhttprequest`) - Q&A section
    - `writeservices.powerreviews.com/voteugc` (`xmlhttprequest`) - voting on reviews

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
