### ISSUE TITLE
zmags.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#398]
- https://www.homfurniture.com/living-room (last verified 2022-09-14)
  - main content doesn't render / large amounts of content missing (e.g., "shop by category" and images)
  - requests required:
    - `c.zmags.com/static/manifest.js` - initiator
    - `c.zmags.com/static/vendor.js` - initiator
    - `c.zmags.com/static/client.js` - initiator
    - `c.zmags.com/api/groups/<hex>` (`xmlhttprequest`)
    - `c.zmags.com/api/experiences/<hex>` (`xmlhttprequest`)
    - `c.zmags.com/api/companies/<hex>/settings` (`xmlhttprequest`)
    - `c.zmags.com/assets/images/.*` (`image`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
