### ISSUE TITLE
investis.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#399]
- https://www.bandmretail.com/ (last verified 2022-09-14)
  - share price doesn't show
  - requests required:
    - `irs.tools.investis.com/clients/uk/bandm1/ticker/ticker.aspx` (`subdocument`)
    - `irs.tools.investis.com/clients/uk/bandm1/fonts/icomoon.woff` (`font`) - arrow next to percentage
- https://www.kingspan.com/group/ (last verified 2022-09-14)
  - stock ticker doesn't show (scroll to top of page, should then appear in bottom right)
  - requests required:
    - `irs.tools.investis.com/Clients/uk/kingspan/Ticker/Ticker.aspx` (`subdocument`) - for main ticker to show
    - `irs.tools.investis.com/Clients/uk/kingspan/Ticker/Images/down.png` - down arrow image
    - `irs.tools.investis.com/Clients/uk/kingspan//fonts/BrownPro-Light.woff` (`font`) - clearer rendering/alignment of text

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
