### ISSUE TITLE
infogram.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#400]
- https://www.riotinto.com/invest/reports/sustainability-report (last verified 2022-09-14)
  - embedded infogram doesn't render
  - requests required:
    - `e.infogram.com/js/dist/embed.js` - initiator
    - `e.infogram.com/<hex-dashed>` (`subdocument`) - for rendering

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
