### ISSUE TITLE
⚙️ Surrogate breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#401]
### gpt

- `www.googletagservices.com/tag/js/gpt.js`

- https://985thesportshub.com/ (last verified 2022-09-14)
  - cannot interact with navigation bar
  - *blocking* the request is sufficient. Bug with surrogate
    - see also https://app.asana.com/0/0/1202961637623817/f
- https://www.hardwarezone.com.sg/feature-8-things-know-apple-iphone-14-pro-max-review-singapore-price-specs (last verified 2022-09-15)
  - site does not load for several seconds (opaque overlay)
  - requests required:
    - `www.googletagservices.com/tag/js/gpt.js` (currently surrogate) - initiator
    - `securepubads.g.doubleclick.net/gpt/pubads_impl_2022090801.js`
    - `securepubads.g.doubleclick.net/gampad/ads` (`xmlhttprequest`)
- https://github.com/duckduckgo/privacy-configuration/issues/1045
- https://thenationaldesk.com/ (last verified 2023-11-9)
  - site loads blank

### google-ima

- https://www.crazygames.com/game/time-shooter-2 (2023-10-20)
  - https://app.asana.com/0/1200277586140538/1205755947770843/f
  - `imasdk.googleapis.com/js/sdkloader/ima3.js`
- https://www.raiplay.it/dirette/index.html (2023-10-20)
  - video doesn't play
  - https://app.asana.com/0/1200277586140538/1205755947770866/f
- https://www.radio.de/s/rockantenne (2023-10-20)
  - music doesn't play
  - https://app.asana.com/0/1200277586140538/1205755947770857/f
- https://live.itftennis.com/en/live-streams/video.php?vid=44635486 (2023-10-20)
  - https://app.asana.com/0/1200277586140538/1205755947770850/f
  - video doesn't play
- https://www.rawstory.com/brian-stelter/
  - audio summary doesn't play
- https://games.usatoday.com/games/amu-jumble
  - pre-roll ad hangs and doesn't allow game to load
- https://gbnews.com
  - videos don't play

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
