### ISSUE TITLE
listenlive.co breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#402]
- https://www.hot97.com/listen-live (last verified 2022-09-14)
  - audio player does not show, music content doesn't show
  - requests required:
    - `widgets.listenlive.co/1.0/tdwidgets.min.js` - initiator
    - `sdk.listenlive.co/web/2.9/td-sdk.min.js` - initiator
    - `widgets.listenlive.co/1.0/player.min.js` - for player to show
    - `widgets.listenlive.co/1.0/songhistory.min.js` - for "recently played" section header to show
    - `widgets.listenlive.co/1.0/fab.min.js` - for recently played song list to show, for audio to play

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
