### ISSUE TITLE
alipay.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#403]
- https://npmmirror.com/ / https://cnpmjs.org/ (last verified 2022-09-14)
  - site does not load, instead there is a placeholder image taking up entire screen
  - requests required:
    - `render.alipay.com/p/s/taobaonpm_click/image_1` (`image`)
    - `render.alipay.com/p/s/taobaonpm_click/npmtaobao_banner` (`image`) - gets rid of blank image box on now-loaded page

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
