### ISSUE TITLE
alicdn.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#404]
- https://www.daraz.com.bd/products/realme-i184521618-s1129576510.html (last verified 2022-09-14)
  - go to "add item to cart", then select to "register". There is a spinner for a couple of seconds which then times out and errors (should show SMS verification slider)
  - requests required:
    - `aeu.alicdn.com/AWSC/uab/1.140.0/collina.js`
- https://account.antpool.com/sign_in (last verified 2022-09-14)
  - cannot retrieve phone auth (slider blocked)
  - requests required:
    - `g.alicdn.com/AWSC/uab/1.140.0/collina.js`
    - `g.alicdn.com/AWSC/WebUMID/1.90.2/um.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
