### ISSUE TITLE
cnn.com (request) breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#405]
- https://newz.ai/ (last verified 2022-09-15)
  - some images don't render
  - requests required:
    - `cdn.cnn.com/cnnnext/dam/assets/[^/]+.jpe?g` (`image`)
    - `media.cnn.com/api/v1/images/stellar/prod/[^/]+.jpg` (`image`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
