### ISSUE TITLE
searchanise.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#406]
- https://credobeauty.com/products/lip-balm-elixir (last verified 2022-09-15)
  - product search does not show dynamic results when typing
  - requests required:
    - `www.searchanise.com/widgets/shopify/init.js` - initiator
    - (most other requests then come from `searchanise-ef84.kxcdn.com`)
    - `www.searchanise.com/getwidgets` (`script`) - required for products to show in dynamic search
- https://www.badgerbalm.com/ (last verified 2022-09-15)
  - dynamic search results don't show when typing in search box
  - requests required:
    - `www.searchanise.com/widgets/shopify/init.js` - initiator
    - `www.searchanise.com/getwidgets` (`script`) - required for results to show
    - after performing search:
      - `www.searchanise.com/getresults` (`script`) - for results to display in grid rather than list

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
