### ISSUE TITLE
mylivechat.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#408]
- https://www.minisplitwarehouse.com/page/lg-mini-split-art-cool (last verified 2022-09-15)
  - "chat with us" widget doesn't show (bottom right)
  - requests required:
    - `mylivechat.com/chatwidget.aspx` - initiator
    - `s2.mylivechat.com/livechat2/livechat2.aspx` - initiator
    - `s2.mylivechat.com/livechat2/resources2.aspx` - initiator
    - `s2.mylivechat.com/livechat2/script/livechatinit2.js`
    - `s2.mylivechat.com/livechat2/images/[^/]+.png` (`image`) - "sign in with" icons
    - `s2.mylivechat.com/livechat2/.*` (various requests)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
