### ISSUE TITLE
custhelp.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#409]
- https://support-uk.panasonic.eu/ (last verified 2022-09-15)
  - "chat with us" widget doesn't show. Clicking "live chat" link doesn't load
  - requests required:
    - `panasonic-eu.widget.custhelp.com/ci/oit/getConfigs` (`xmlhttprequest`)
    - `panasonic-eu.widget.custhelp.com/ci/api/v1/customFields` (`xmlhttprequest`)
    - `panasonic-eu.widget.custhelp.com/ci/oit/authenticateChat` (`xmlhttprequest`) - for connecting to chat
- https://www.centerparcs.co.uk/ (last verified 2022-09-15)
  - chat widget does not show (bottom right)
  - requests required:
    - `centerparcs.widget.custhelp.com/s/oit/latest/common/v0/libs/oit/loader.js` - initiator
    - `centerparcs.widget.custhelp.com/s/oit/latest/common/v0/libs/oit/loader-frame.js` - initiator
    - `centerparcs.widget.custhelp.com/s/oit/latest/common/v0/libs/requirejs/require.js` - initiator
    - `centerparcs.widget.custhelp.com/s/oit/latest/inlays/oracle/chat-embedded/inlay.js` - initiator
    - `centerparcs.widget.custhelp.com/s/oit/latest/common/v0/common.js` - initiator
    - `centerparcs.widget.custhelp.com/s/oit/latest/.*` (various requests)
    - `centerparcs.widget.custhelp.com/ci/.*` (various requests)
    - `centerparcs.chat.custhelp.com/engagement/api/consumer/centerparcs/v1/getEngagementQueue` (`xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
