### ISSUE TITLE
Salesforce breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#410]
- https://www.citrix.com/support (last verified 2022-09-15)
  - widget gets stuck loading after clicking "start chat"
  - requests required:
    - `citrixsystems.force.com/consulting/embeddedService/sidebarApp.app` (`xmlhttprequest`) - initiator
    - `citrixsystems.force.com/consulting/l/.*` (various `script` requests)
    - `static.lightning.force.com/na152/l/.*` (various `script` requests)
    - `static.lightning.force.com/na152/auraFW/javascript/[^/]+/aura_prod.js`
    - `citrixsystems.force.com/consulting/aura` (`xmlhttprequest`)
    - (in addition, various `salesforceliveagent.com` requests are present)
- https://www.centurylink.com/home/help/chat.html (last verified 2022-09-07)
  - chat widget does not show
  - requests required
    - required for widget to show
      - `www.googletagmanager.com/gtm.js` (currently a surrogate)
      - `c.la1-c1cs-ia2.salesforceliveagent.com/content/g/js/48.0/deployment.js`
    - required for widget to expand when clicked
      - `d.la3-c1cs-ph2.salesforceliveagent.com/chat/rest/Visitor/Settings.jsonp`
      - `d.la3-c1cs-ph2.salesforceliveagent.com/chat/rest/Visitor/Settings.jsonp`
- https://eshop.macsales.com/Service/ (last verified 2022-09-07)
  - "Start chat" button (top left) doesn't show
  - requests required
    - `c.la2-c1-dfw.salesforceliveagent.com/content/g/js/42.0/deployment.js`
    - `d.la2-c1-dfw.salesforceliveagent.com/chat/rest/Visitor/Settings.jsonp`
- https://www.nxp.com/ (last verified 2022-09-07)
  - chat widget does not show
  - requests required
    - `c.la1-c2-fra.salesforceliveagent.com/content/g/js/55.0/deployment.js`
    - `d.la1-c2-fra.salesforceliveagent.com/chat/rest/Visitor/Settings.jsonp`

#### See also

- https://app.asana.com/0/1201734708866422/1202022205233886/f
- https://app.asana.com/0/0/1201506519463002/f
- https://app.asana.com/0/0/818765608271893/f
- https://app.asana.com/0/0/1143990159155800/f
- https://app.asana.com/0/0/1143829067573938/f
- https://app.asana.com/0/569473074191537/803535969816807/f
- https://app.asana.com/0/0/818765608271893/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
