### ISSUE TITLE
intercom.io breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#411]
- https://www.habito.com/ (last verified 2022-09-09)
  - chat widget does not show
  - requests required
    - `widget.intercom.io/widget/gglb3xso` - required for widget to show
    - `api-iam.intercom.io/messenger/web/ping` (`xmlhttprequest`) - required for initial chat connection ("Something went wrong" if not allowed)
    - `api-iam.intercom.io/messenger/web/help_center_content` (`xmlhttprequest`) - required for suggested articles
    - `api-iam.intercom.io/messenger/web/home_cards` (`xmlhttprequest`) - required for initial help content
    - `api-iam.intercom.io/messenger/web/articles/[0-9]+` (`xmlhttprequest`) - required for clicking on articles to function
    - `api-iam.intercom.io/messenger/web/messages` (`xmlhttprequest`) - required for sending messages
    - `api-iam.intercom.io/messenger/web/conversations/[0-9]+/reply` (`xmlhttprequest`) - required for sending further messages

#### See also

- https://app.asana.com/0/569473074191537/793379899948860/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
