### ISSUE TITLE
livechatinc.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#412]
- https://www.castlecameras.co.uk/ (last verified 2022-09-14)
  - chat widget does not show
  - requests required:
    - `cdn.livechatinc.com/tracking.js` - initiator for other requests
    - `api.livechatinc.com/v3.3/customer/action/get_dynamic_configuration` - initiator
    - `api.livechatinc.com/v3.3/customer/action/get_configuration` - initiator
    - `secure.livechatinc.com/customer/action/open_chat` (`subdocument`) - initiator
    - `api.livechatinc.com/v3.3/customer/action/get_localization`
    - `cdn.livechatinc.com/widget/static/js/iframe.222338d2.chunk.js`
    - `cdn.livechatinc.com/widget/static/js/0.96a16c18.chunk.js`
    - `cdn.livechatinc.com/widget/static/js/2.ae17a60b.chunk.js`
    - `api.livechatinc.com/v3.3/customer/rtm/ws` (`websocket`)
    - for chat content:
      - `cdn.livechatinc.com/widget/static/js/main-view.80fd853e.chunk.js`
      - `cdn.livechatinc.com/widget/static/js/3.cd7b604a.chunk.js`
    - `queue.livechatinc.com/logs` (`xmlhttprequest`) - this request will keep retrying (thousands of times) if blocked
- https://www.waves.com/contact-us (last verified 2023-05-08)
  - clicking chat button has no effect
  - requests required:
    - `livechatinc.com/*` (various)
- https://info.tradera.com/kontakt/ (last verified 2023-05-08)
  - chat widget does not show
  - requests requried:
    - `livechatinc.com/*` (various)
- https://www.turbodebt.com/live-chat/ (last verified 2023-05-08)
  - chat (i.e., most of page) does not render
  - requests required:
    - `livechatinc.com/*` (various)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
