### ISSUE TITLE
boldchat.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#413]
- https://www.marshalls.co.uk/commercial (last verified 2022-09-14)
  - chat widget does not show
  - requests required:
    - `vmss.boldchat.com/aid/238427623834426527/bc.vms4/vms.js` - initiator
    - `vms.boldchat.com/aid/238427623834426527/bc.pv` (`script`) - allows widget to show
    - for clicking widget:
      - `livechat.boldchat.com/aid/238427623834426527/mobilechat/launcher.jsp`
      - `livechat.boldchat.com/aid/238427623834426527/mobilechat/loader.jsp`
    - for frame content:
      - `livechat.boldchat.com/aid/238427623834426527/mobilechat/visitor.jsp` (`subdocument`)
      - `images.boldchat.com/images/floating/menu.png` - menu icon
      - `images.boldchat.com/images/floating/minimize-arrow.png` - minimize icon

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
