### ISSUE TITLE
weather.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#415]
- https://www.nbcchicago.com/ (last verified 2022-09-15)
  - weather panel is missing map (right hand side)
  - requests required:
    - `widgets.media.weather.com/wxwidget.loader.js` - initiator
    - `widgets-green.media.weather.com/wxwidget.loader.js` - initiator
    - `widgets-green.media.weather.com/widgets/wxwidget.map.js`
    - `widgets-green.media.weather.com/wxwidget.mosaic.js`
    - `widgets-green.media.weather.com/wxwidget.common.js`
    - `widgets-green.media.weather.com/basemaps` (`xmlhttprequest`)
    - `widgets-green.media.weather.com/menu` (`xmlhttprequest`)
    - `widgets-green.media.weather.com/chunks/wxwidget.mapDefaultLayout.js` - zoom in/out
    - `*.weather.com/.*` (various requests) - other content

**Comment by sammacbeth** [comment]
- https://weather.com/ (last verified 2023-02-22)
   - Adblocker wall
   - requests required:
     - `securepubads.g.doubleclick.net/pagead/ppub_config`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
