### ISSUE TITLE
helpscout.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#416]
- https://www.roofingmegastore.co.uk/ (last verified 2022-09-15)
  - chat widget does not show
  - requests required:
    - `beacon-v2.helpscout.net/` (`script`) - initiator
    - `beacon-v2.helpscout.net/static/js/main.<hex>.js`
    - `beacon-v2.helpscout.net/static/js/vendor.<hex>.js` - initiator
    - `beacon-v2.helpscout.net/static/js/full-beacon-init.<hex>.chunk.js`
    - (additional `*.helpscout.net/.*` requests for functionality)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
