### ISSUE TITLE
speedtestcustom.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#417]
- https://www.internetspeedtest.co.uk/ (last verified 2022-09-15)
  - speed test "Go" button doesn't show
  - requests required:
    - `glimp.speedtestcustom.com/` (`subdocument`) - initiator
    - (various `*.speedtestcustom.com/.*` requests for appearance & functionality)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
