### ISSUE TITLE
Disqus breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#419]
- https://mangapark.net/ (last verified 2022-09-15)
  - disqus chat section doesn't show
  - requests required:
    - `mangaparkcom.disqus.com/embed.js` - initiator
    - `*.disqus.com/.*` (various requests)
    - `*.disquscdn.com/.*` (various requests)
- https://bikepacking.com/news/fall-2022-bikepacking-collective-discounts/ (last verified 2022-09-15)
  - disqus chat section doesn't load
  - requests required:
    - `*.disqus.com` (various requests)
    - `*.disquscdn.com` (various requests)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
