### ISSUE TITLE
visa.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#420]
- https://www.dicegamedepot.com/checkout (last verified 2022-09-15)
  - (with item in cart) visa checkout option doesn't show
  - requests required:
    - `assets.secure.checkout.visa.com/checkout-widget/resources/js/integration/v1/sdk.js` - initiator
    - various `visa.com` requests

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
