### ISSUE TITLE
donorbox.org breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#421]
- https://earth.org/donations/ (last verified 2022-09-16)
  - donation panel doesn't show (right hand side)
  - requests required:
    - `donorbox.org/embed/eo-giving-campaign` (`subdocument`) - initiator
    - `donorbox.org/assets/.*` (`image`, `script`, `stylesheet`) - for widget display

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
