### ISSUE TITLE
contactatonce.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#422]
- https://www.lichtsinn.com/ (last verified 2022-09-16)
  - chat widget doesn't show
  - requests required:
    - `tag.contactatonce.com/tag/tag.js` - initiator
    - `tag.contactatonce.com/taglets` - initiator
    - `tag.contactatonce.com/api/v1.0/configuration/engagement` - initiator
    - `tag.contactatonce.com/api/v1.0/configuration/popingenerator` - initiator
    - `tag.contactatonce.com/scripts/popin.js` - initiator
    - `pres-us.contactatonce.com/.*` (`image`)
    - `cdn.contactatonce.com/.*` (various requests)
    - `event-api.contactatonce.com/.*` (various requests)
- https://www.lazydays.com/rvs/class-b-motorhomes (last verified 2022-09-16)
  - chat widget doesn't show
  - requests required:
    - as above

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
