### ISSUE TITLE
tripadvisor.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#424]
- https://www.visitestonia.com/en/mooste-manor (last verified 2022-09-16)
  - media on reviews doesn't render (scroll down to reviews section)
  - requests required:
    - `media-cdn.tripadvisor.com/media/.*` (`image`)
    - `www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s[^/]*.png` (`image`) - for ratings display
- https://alaska.guide/ (last verified 2022-09-16)
  - rating widget in footer doesn't show
  - requests required:
    - `www.tripadvisor.com/wejs` - initiator
    - `www.tripadvisor.com/WidgetEmbed-excellent`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
