### ISSUE TITLE
netlify.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#425]
- https://prettier.io/ (last verified 2022-09-16)
  - "deploys by Netflify" badge doesn't render in footer
  - requests required:
    - `www.netlify.com/img/global/badges/netlify-color-accent.svg`
- https://masstimes.org/ (last verified 2022-09-16)
  - logo doesn't render
  - requests required:
    - `cdn.netlify.com/.*` (`image`) - logos

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
