### ISSUE TITLE
attraqt.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#426]
- https://www.vans.co.uk/shop/en-gb/vans-gb/authentic-shoes (last verified 2022-09-16)
  - product images don't render in grid
  - requests required:
    - `fsm-vfc.attraqt.com/zones/1dba4cb6-f834-4d53-b529-dd28d73eec4f.min.js` - initiator
    - `fsm-vfc.attraqt.com/zones-js.aspx`
- https://www.specsavers.co.uk/contact-lenses (last verified 2022-09-16)
  - product images don't render in grid
  - requests required:
    - `fsm1-cdn.attraqt.com/zones/735a49fc-ca8f-40e3-bc55-bbaac9834bf1.min.js` - initiator
    - `fsm1-cdn.attraqt.com/zones-js.aspx`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
