### ISSUE TITLE
addthis.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#427]
- https://www.greentechmedia.com/articles/read/can-free-smart-thermostats-boost-demand-response-potential-in-the-covid-19-era (last verified 2022-09-16)
  - floating share pane doesn't show (right hand side)
  - requests required:
    - `s7.addthis.com/js/300/addthis_widget.js` - initiator
    - `s7.addthis.com/static/layers.fa6cd1947ce26e890d3d.js`
    - `s7.addthis.com/static/144.145922425febd366fe41.js` - allows flipboard logo to show
- https://www.lepointdufle.net/ (last verified 2022-09-16)
  - share buttons don't show (bottom of page)
  - requests required:
    - `s7.addthis.com/js/300/addthis_widget.js` - initiator
    - `s7.addthis.com/l10n/client.fr.min.json`
    - `s7.addthis.com/static/layers.fa6cd1947ce26e890d3d.js`
    - `s7.addthis.com/static/211.74cdf7c5aa233e149d75.js` - for gmail logo in "more options"
- https://www.wjbf.com/top-stories/csra-may-see-severe-weather-from-hurricane-ian-how-you-can-prepare/ (last verified 2022-09-27)
  - cannot interact with sharing icons (above main article body)
  - requests required:
    - `s7.addthis.com/js/300/addthis_widget.js` - allows cursor change on hover, initiator
    - `s7.addthis.com/static/layers.fa6cd1947ce26e890d3d.js`
    - `s7.addthis.com/static/209.7d7330bbfa2be6215e38.js`
    - `s7.addthis.com/static/211.74cdf7c5aa233e149d75.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
