### ISSUE TITLE
vk.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#428]
- https://yandex.ru/video/preview/4521186185452953419 (last verified 2022-09-16)
  - video preview does not play
  - requests required:
    - `vk.com/video_ext.php` (`subdocument`) - initiator
    - `*.vk.com/.*` (various requests) - for video playback

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
