### ISSUE TITLE
recurly.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#429]
- https://app.gitkraken.com/purchase-license?product=gitgui&license=PRO (last verified 2022-09-16)
  - site loads blank
  - requests required:
    - `js.recurly.com/v4/recurly.js`

#### See also

  - https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/483
  - https://app.asana.com/0/0/1190185650582875/f
  - https://app.asana.com/0/569473074191537/1180920159740327/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
