### ISSUE TITLE
usemessages.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#430]
- https://sitestacker.training/ (last verified 2022-09-16)
  - chat widget doesn't show
  - requests required:
    - `forms.hubspot.com/collected-forms/v1/config/json` (`xmlhttprequest`)
    - `js.usemessages.com/conversations-embed.js` - initiator
    - `api.hubspot.com/livechat-public/v1/message/public` (`xmlhttprequest`)
    - `app.hubspot.com/conversations-visitor/[0-9]+/threads/utk/<hex>` (`subdocument`)

#### See also

- https://app.asana.com/0/0/1188943018328138/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
