### ISSUE TITLE
activehosted.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#431]
- https://www.certicalia.com/blog/como-abrir-archivo-gml-online (last verified 2022-09-16)
  - mailing list signup form doesn't show
  - requests required:
    - `certicalia.activehosted.com/f/embed.php` (`script`)
- https://www.highlandwoodworking.com/ (last verified 2022-09-16)
  - mailing list signup form doesn't show
  - requests required:
    - `highlandwoodworking.activehosted.com/f/25` (`subdocument`) - for form to show
    - `highlandwoodworking.activehosted.com/proc.php` (`script`) - for form submission

#### See also

- https://app.asana.com/0/569473074191537/1199235927616301/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
