### ISSUE TITLE
embedly.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#432]
- https://www.netmoms.de/ (last verified 2022-09-16)
  - some image content doesn't render
  - requests required:
    - `cdn.embedly.com/widgets/platform.js`
- https://www.concertarchives.org/ (last verified 2022-09-16)
  - some main content (e.g., images) doesn't render
  - requests required:
    - `cdn.embedly.com/widgets/platform.js` - initiator
    - `cdn.embedly.com/js/all.<hex>.js`
    - `cdn.embedly.com/css/all.<hex>.css`
    - `cdn.embedly.com/widgets/media.html` (`subdocument`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
