### ISSUE TITLE
searchspring.io breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#435]
- https://www.ammunitiondepot.com/ (last verified 2022-09-20)
  - recommendations panel doesn't show
  - requests required:
    - `t7hd0g.a.searchspring.io/api/personalized-recommendations/profile.json`
    - `t7hd0g.a.searchspring.io/boost/t7hd0g/recommend` (`xmlhttprequest`)
- https://www.audioadvisor.com/ssearch.asp?txtsearch=radius (last verified 2022-09-20)
  - no search results show
  - requests required:
    - `xyrtl7.a.searchspring.io/api/search/search.json`
- https://www.tnuck.com/black-and-white-stripe-emerson-shirt-0.html (last verified 2022-09-20)
  - "items like this" element doesn't show
  - requests required:
    - `nmg9cn.a.searchspring.io/api/personalized-recommendations/profile.json`
    - `nmg9cn.a.searchspring.io/boost/nmg9cn/recommend` (`xmlhttprequest`)
- https://www.sportystoolshop.com/shop.html?q=tool (last verified 2023-02-07)
  - search results don't show
  - requests required:
    - `snapui.searchspring.io/96lc8j/.*`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
