### ISSUE TITLE
strpst.com breakage [NSFW]

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#438]
:warning: **WARNING: This section contains NSFW adult sites.** :warning:

:warning:  Requests to the `strpst.com` domain are associated with NSFW sites.

- [NSFW SITE](https://stripchat.com/) (last verified 2022-09-21)
  - images and majority of content don't render
  - requests required:
    - `*.strpst.com/*` (unknown/all)
- [NSFW SITE](https://xhamsterlive.com/) (last verified 2022-09-21)
  - main content/page does not render
  - requests required:
    - `*.strpst.com/*` (unknown/all)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
