### ISSUE TITLE
onlyfans.com (site) breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#440]
- 2022-09-21
  - Android: site gets stuck on loading
  - Requests required:
    - likely `d3oxtup47gylpj.cloudfront.net/theme/onlyfans/spa/chunk-vendors.js`, which is CNAMEd from `static.onlyfans.com`

#### See also

- https://app.asana.com/0/1200277586140538/1203021186853771/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
