### ISSUE TITLE
shopee (sites) breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#442]
- https://shopee.ph/ (last verified 2022-09-21)
  - site doesn't load
  - requests required
    - `deo.shopeemobile.com/shopee/.*` (CNAME to `deo.shopeemobile.com-v1.edgesuite.net`)
- https://shopee.com.my/ (last verified 2022-09-21)
  - same as shopee.ph
- https://shopee.com.br/ (last verified 2022-09-21)
  - same as shopee.ph

#### See also

- https://app.asana.com/0/1200223097357040/1203021278783646/f
- https://app.asana.com/0/1200223097357040/1201848375450744/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
