### ISSUE TITLE
daumcdn.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#444]
- https://www.tistory.com/ (last verified 2022-09-21)
  - majority of site content doesn't load
  - requests required:
    - `*.daumcdn.net/*` (various requests)
- https://miaasdh.halsuis.com/40 (last verified 2022-09-22)
  - majority of site content doesn't load
  - note: "powered by tistory"
  - requests required:
    - `*.daumcdn.net/*` (various requests)
- https://rageworx.pe.kr/1998 (last verified 2022-09-22)
  - majority of site content doesn't load
  - note: "powered by tistory"
  - requests required:
    - `*.daumcdn.net/*` (various requests)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
