### ISSUE TITLE
ahacdn.me breakage [NSFW]

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#447]
:warning: **WARNING: This section contains NSFW adult sites.** :warning:

:warning:  Requests to the `ahacdn.me` domain are associated with NSFW sites.

- [NSFW SITE](https://m.ashemaletube.com/) (last verified 2022-09-22)
  - images and majority of content don't render
  - requests required:
    - `cc.<dom>.com/*` (unknown/all) (CNAMEs to `cdn86811639.ahacdn.me`)
- [NSFW SITE](https://hqporner.com/) (last verified 2022-09-22)
  - main content/page does not render
  - requests required:
    - `fastporndelivery.<dom>.com/*` (unknown/all) (CNAMEs to  `cdn30851191.ahacdn.me`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
