### ISSUE TITLE
getshogun.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#450]
- https://bimotal.com/ (last verified 2022-09-22)
  - majority of content doesn't load
  - requests required:
    - `lib.getshogun.com/lazysizes/2.0.0/shogun-lazysizes.js`
    - `cdn.getshogun.com/css-4/632c1fb96218cb00ece08396.css` - page styling
    - `cdn.getshogun.com/5/global-assets-32e6dc0ce0c14084af17cf9924712c8f6baa7f63.js` - page interactivity
- https://thedrardisshow.com/ (last verified 2022-09-22)
  - various images don't render, layout
  - requests required:
    - `cdn.getshogun.com/css-4/62a951d823c25600c58f7a37.css` - layout
    - `lib.getshogun.com/lazysizes/2.0.0/shogun-lazysizes.js` - product images, other images
    - `cdn.getshogun.com/5/global-assets-6bd818efea8f371768a5b897ef30fedbd16be661.js` - donate to show section, initiator
    - `getshogun.com/api/products` (`xmlhttprequest`) - donate to show section

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
