### ISSUE TITLE
ads-twitter.com breakage [NSFW]

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#452]
:warning: **WARNING: This section contains NSFW adult sites.** :warning:

:warning:  Requests to the `ads-twitter.com` domain have been associated with NSFW sites.

- [NSFW SITE](https://hentaihaven.xxx/watch/itadaki-seieki/episode-1/) (last verified 2022-09-22)
  - adwall on video prevents video being played
  - requests required:
    - `static.ads-twitter.com/uwt.js` (`xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
