### ISSUE TITLE
klarna breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#455]
- https://www.spirithalloween.com/product/adult-scarecrow-costume/130539.uts (last verified 2022-09-22)
  - klarna price/logo doesn't render
  - requests required:
    - `na-library.klarnaservices.com/lib.js` - initiator
    - `bsrx9ma6.klarnaservices.com/v3/s` (`xmlhttprequest`) - for icon to show, initiator
    - `na-library.klarnaservices.com/osm-interstitial.js` - for "learn more" link to work
    - `na-library.klarnaservices.com/297.js` - for "learn more" link to work
- https://uk.coach.com/products/wyn-crossbody/C8439-B4RPS.html?frp=C8439%20B4RPS (2023-06-21)
  - Klarna icon doesn't render (shows as a grey box)
  - requests required:
    - `us-assets.klarnaservices.com/images/logo_black.png`
  - clicking "learn more" next to Klarna icon shows a blank screen
    - `eu-assets.klarnaservices.com/learn-more/index.html`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
