### ISSUE TITLE
listrakbi.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#457]
- https://www.catofashions.com/preferenceCenter.cfm/email-catalog-subscriptions (last verified 2022-09-22)
  - form does not display
  - requests required:
    - `cdn.listrakbi.com/scripts/script.js`
- https://www.choicehomewarranty.com/opt-out/ (last verified 2022-09-22)
  - opt-out form doesn't show
  - requests required:
    - `cdn.listrakbi.com/scripts/script.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
