### ISSUE TITLE
geetest.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#462]
- https://app.3commas.io/auth/login (last verified 2022-09-23)
  - verification widget does not load
    - note: it may take several (dozens) of refreshes to get the verification widget to show (should appear just under login form)
  - requests required:
    - `api.geetest.com/gettype.php` - initiator
    - `static.geetest.com/static/js/fullpage.9.1.0.js`
    - `api.geetest.com/get.php` - initiator
    - `static.geetest.com/static/wind/style_https.1.5.8.css` - for verification widget to render
    - `api.geetest.com/ajax.php` - required to avoid "network failure" when verification clicked
    - `api.geetest.com/reset.php` - for "retry" to function
    - for captcha:
      - `static.geetest.com/static/js/slide.7.8.8.js` - for captcha puzzle to load
      - `static.geetest.com/static/ant/style_https.1.2.6.css` - for captcha puzzle to render
      - `static.geetest.com/pictures/gt/.*` (`image`) - for captcha puzzle to render
- https://www.jbag888.com/m/login (last verified 2022-09-23)
  - verification widget doesn't load
  - requests required:
    - `api.geetest.com/gettype.php` - initiator
    - `static.geetest.com/static/js/fullpage.9.1.0.js` - initiator
    - `api.geetest.com/get.php`
    - `api.geetest.com/reset.php` - for "retry"
    - `api.geetest.com/ajax.php`
    - for captcha:
      - `static.geetest.com/static/js/slide.7.8.8.js`
      - `static.geetest.com/static/ant/style_https.1.2.6.css`
      - `static.geetest.com/pictures/gt/*` (`image`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
