### ISSUE TITLE
cookiepro.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#466]
- https://www.my-account.athome.domesticandgeneral.com/my-account (last verified 2022-09-23)
  - page redirects to an error page (fine w/o protections)
  - requests required:
    - `cookie-cdn.cookiepro.com/*` (various/unknown requests)
    - `widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js`
- https://www.gamesgames.com/game/merge-fruit (last verified 2022-09-23)
  - game does not load after clicking play
  - requests required:
    - `cookie-cdn.cookiepro.com/scripttemplates/otSDKStub.js` - initiator
    - `cookie-cdn.cookiepro.com/*` (various/unknown requests)
- https://www.azurestandard.com/shop/product/food/baking-pantry/cocoa-cacao/cocoa-butter/cocoa-butter-wafers-organic/13020 (last verified 2023-11-23)
   - Product reviews are blocked
- https://blog.totaladblock.com/stop-annoying-ads-on-your-android/
   - Product reviews are blocked

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
