### ISSUE TITLE
Ezoic breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#468]
- https://kosmofoto.com/2022/09/alfie-tych-half-frame-camera/ (last verified 2022-09-23)
  - main content images don't render
  - requests required:
    - `g.ezoic.net/*` (various requests)
    - `sf.ezoiccdn.com/*` (`script`) (various requests)
- https://www.fishkeepingworld.com/orchid-dottyback/ (last verified 2022-09-23)
  - fish video doesn't load
  - requests required:
    - `videosvc.ezoic.com/play` (`xmlhttprequest`) - initiator
    - `video-streaming.ezoic.com/*` (various requests) (`image`, `xmlhttprequest`)
    - `g.ezoic.net/ezvideo/ezvideo*` (`stylesheet`, `image`)
- https://www.borninspace.com/ (last verified 2022-09-23)
  - main content images don't render
  - requests required:
    - `sf.ezoiccdn.com/ezoimgfmt/www.borninspace.com/wp-content/uploads/2022/09/[^/]+` (`image`)
    - `g.ezoic.net/*` (various requests) (`xmlhttprequest`, `script`)
- https://airplaneacademy.com/piston-vs-turboprop-performance-efficiency-and-safety/
  - images don't load due to blocking go.ezodn.com requests

**Comment by sammacbeth** [comment]
- https://defkey.com/
  - Consent popup cannot be dismissed.
  - requests required:
     - `https://g.ezodn.com/cmp/v2/v.js`
     - `https://ezodn.com/cmp/gvl.json`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
