### ISSUE TITLE
mailerlite.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#470]
- https://www.subscribepage.com/oldmoneypricesbook (last verified 2022-09-23)
  - clicking submit with e-mail in form just reloads page rather than proceeding to "thank you"
  - requests required:
    - `static.mailerlite.com/*` (various) (`script`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
