### ISSUE TITLE
Google maps breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#472]
- https://www.sintonandrews.com/property/101259009278-claygate-road-northfields (last verified 2022-09-23)
  - map doesn't render
  - requests required:
    - `maps.google.co.uk/maps` (`subdocument`) - initiator
    - `www.google.com/maps/embed` (`subdocument`) - initiator
    - `maps.gstatic.com/maps-api-v3/embed/js/50/6/init_embed.js` - initiator
    - `www.google.com/maps/vt` (`image`, `xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
