### ISSUE TITLE
🔎 Embedded search breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#475]
- https://start.me/search/google?q=test (last verified 2022-09-23)
  - search broken
  - requests required:
    - `cse.google.com/cse.js`
- https://crowdedplannet.org/search (last verified 2023-01-31)
  - search box does not show
  - requests required:
    - `www.google.com/cse/static/`
- https://www.asknumbers.com/ (last verified 2023-01-31)
  - search box does not show (top of page)
  - requests required:
    - `www.google.com/cse/static` (for search box to show)
    - `cse.google.com/cse/element/v1` (for results after searching)
- https://www.desiringgod.org/search/results?q=test (last verified 2023-02-16)
  - search shows blank page
  - requests required:
    - `cse.google.com/cse/cse.js`
- https://www.khanacademy.org/search?page_search_query=test (last verified 2023-02-16)
  - search doesn't load, only shows a loading spinner
  - requests required:
    - `cse.google.com/cse/cse.js`
- https://www.w3schools.com/colors/colors_picker.asp (last verified 2023-02-17)
  - clicking search bar doesn't work (search box doesn't show)
  - requests required:
    - `www.google.com/cse/cse.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
