### ISSUE TITLE
usercentrics.eu breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#477]
- https://www.joyn.de/play/live-tv?channel_id=165 (last verified 2022-09-24)
  - page does not load
  - requests required:
    - `api.usercentrics.eu/settings/GXjugz_sV/latest/*.json` (various requests) (`xmlhttprequest`)
    - `app.usercentrics.eu/browser-sdk/4.12.0/cross-domain-bridge.html` (`subdocument`) - initiator
    - `api.usercentrics.eu/tcf2/en-v2.json`
    - `aggregator.service.usercentrics.eu/aggregate/de` (`xmlhttprequest`)
    - `graphql.usercentrics.eu/graphql` (`xmlhttprequest`) - interactivity of cookie prompt
- https://www.flaschenpost.de/ (last verified 2022-09-24)
  - cookie prompt broken (e.g., clicking to go to more options shows blank elements)
  - requests required:
    - `api.usercentrics.eu/settings/9GJ_e4nDK/latest/languages.json`
    - `api.usercentrics.eu/settings/9GJ_e4nDK/latest/de.json`
    - `app.usercentrics.eu/browser-sdk/4.12.1/cross-domain-bridge.html` (`subdocument`) - initiator
    - `aggregator.service.usercentrics.eu/aggregate/de` (`xmlhttprequest`) - for text to show when going to manage cookies (sometimes requires exiting then re-entering the management screen)
- https://www.kicker.de/fuenf-fuenfer-die-kicker-noten-zur-dfb-pleite-gegen-ungarn-918680/slideshow (last verified 2022-09-24)
  - clicking to manage cookies (in footer) has no effect
  - requests required:
    - `privacy-proxy.usercentrics.eu/latest/uc-block.bundle.js` - initiator
    - `app.usercentrics.eu/browser-ui/latest/loader.js` - initiator
    - `app.usercentrics.eu/browser-ui/2.45.0/*` (`script`)
    - `api.usercentrics.eu/tcf2/en-v2.json`
    - `api.usercentrics.eu/settings/BlAjKmR1u/latest/de.json` - initiator
    - `graphql.usercentrics.eu/graphql` (`xmlhttprequest`) - without this, clicking to save settings gets stuck
- https://www.rowohlt.de/#uc-corner-modal-show (last verified 2022-09-24)
  - cookie prompt doesn't show when clicking to manage cookies (bottom of footer)
  - requests required:
    - (no novel requests)

**Comment by sammacbeth** [comment]
Additional breakage related to this domain on [verivox.de](https://www.verivox.de/):
- Page is not interactive
- Requests required:
  * `https://app.usercentrics.eu/session/1px.png`
  * `https://aggregator.service.usercentrics.eu/aggregate/de`
  * `https://api.usercentrics.eu/translations/translations-de.json`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
