### ISSUE TITLE
Nuance breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#479]
- https://www.ups.com/track (last verified 2022-09-24)
  - "Ask UPS" chat widget does not render
  - requests required:
    - `ups.inq.com/chatskins/launch/inqChatLaunch10005649.js` - initiator
    - `media-us1.digital.nuance.com/media/launch/chatLoader.min.js` - initiator
    - `media-us1.digital.nuance.com/media/launch/pr.min.js` - initiator
    - `media-us1.digital.nuance.com/media/launch/site_10005649_default.js` - initiator
    - `media-us1.digital.nuance.com/media/launch/tcFramework.min.js` - initiator
    - `ups.inq.com/tagserver/postToServer.min.htm` (`subdocument`) - initiator
    - `ups.inq.com/tagserver/postToServer.min.js` - initiator
    - `ups.inq.com/tagserver/(init|launch)/*` (`xmlhttprequest`)
    - for chat to show:
    - `media-us1.digital.nuance.com/media/launch/*` (`script`) (various requests)
    - `ups.inq.com/chatskins/sites/10005649/flash/UPS-2020-CARE-DT-GLOBAL_EN-PROD.mxml` (`xmlhttprequest`)
    - for chat functionality:
    - `chatrouter-ups.inq.com/chatrouter/chat/*` (`xmlhttprequest`)
    - `media-us1.digital.nuance.com/media/sites/*` (`image`) - for various icons (e.g., close icon)
- https://www.vodafone.co.uk/contact-us/ (last verified 2023-03-07)
  - Asana: https://app.asana.com/0/1200277586140538/1204110738065991/f
  - Chat doesn't load when clicking chat button
  - Requests required:
    - `tags.tiqcdn.com/utag/vodafone/uk-webchat/prod/utag.*.js`
    - `vodafoneuk.digital.nuance.com/tagserver/postToServer.min.htm`
- https://www.britishgas.co.uk/help-and-support/contact-us (2023-05-11)
  - Chat doesn't load when "Start chatting" is pressed

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
