### ISSUE TITLE
usabilla.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#482]
- https://www.chileatiende.gob.cl/fichas/3442-certificado-de-antecedentes (last verified 2022-09-26)
  - rate article widget doesn't show (right of screen)
  - requests required:
    - `w.usabilla.com/996ca51785d1.js` - for widget to show
    - for widget to load when clicked:
    - `w.usabilla.com/feedbacklet` (`script`)
    - `api.usabilla.com/v2/feedback/996ca51785d1.config` (`script`)
    - `api.usabilla.com/v2/f/996ca51785d1` (`xmlhttprequest`) - for submitting feedback
- https://www.6play.fr/ (last verified 2022-09-26)
  - feedback button doesn't load (right of screen)
  - requests required:
    - `w.usabilla.com/cfee41633aa4.js`
    - required for widget interaction:
    - `w.usabilla.com/feedbacklet` (`script`)
    - `api.usabilla.com/v2/feedback/cfee41633aa4.config` (`script`)
    - `api.usabilla.com/v2/f/cfee41633aa4` (`xmlhttprequest`) - required for form submission

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
