### ISSUE TITLE
segment.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#484]
- https://www.fender.com/en-US/start (last verified 2022-09-26)
  - clicking on product images doesn't load the product page
  - requests required:
    - `cdn.segment.com/analytics.js/v1/i1rOaVUFUcTNybqh631glUNsBFb9rP1I/analytics.min.js` - initiator
    - `cdn.segment.com/v1/projects/i1rOaVUFUcTNybqh631glUNsBFb9rP1I/settings` (`xmlhttprequest`) - initiator
    - `cdn.segment.com/analytics-next/bundles/870.bundle.323974846b6d45afb45e.js` - initiator
    - `cdn.segment.com/analytics-next/bundles/ajs-destination.bundle.35a8f6f19959bf2f455f.js` - initiator
    - `cdn.segment.com/analytics-next/bundles/schemaFilter.bundle.debb169c1abb431faaa6.js`
- https://newskybox.co.nz/register (last verified 2022-09-26)
  - page doesn't load (begins loading, but then turns blank)
  - requests required:
    - `cdn.segment.com/analytics.js/v1/kZELe5o8QGI8uHZYnu7jH9vht4TTT2o6/analytics.min.js` - initiator
    - `cdn.segment.com/v1/projects/kZELe5o8QGI8uHZYnu7jH9vht4TTT2o6/settings` (`xmlhttprequest`) - initiator
    - `cdn.segment.com/analytics-next/bundles/870.bundle.323974846b6d45afb45e.js` - initiator
    - `cdn.segment.com/analytics-next/bundles/ajs-destination.bundle.35a8f6f19959bf2f455f.js` - initiator
    - `cdn.segment.com/analytics-next/bundles/schemaFilter.bundle.debb169c1abb431faaa6.js` - initiator
    - `cdn.segment.com/next-integrations/integrations/google-tag-manager/2.5.1/google-tag-manager.dynamic.js.gz` (`script`) - initiator
    - `cdn.segment.com/next-integrations/integrations/vendor/commons.c42222c4cb2f8913500f.js.gz` (`script`)
- https://my.foxnews.com/ (last verified 2022-09-26)
  - clicking "create account" has no effect (note: set region to US)
  - requests required:
    - `cdn.segment.com/analytics.js/v1/4I2fAtE5IxTlczNT3F91OckHtI5wfR7g/analytics.min.js` - initiator
    - `cdn.segment.com/v1/projects/4I2fAtE5IxTlczNT3F91OckHtI5wfR7g/settings` (`xmlhttprequest`) - initiator
    - `cdn.segment.com/analytics-next/bundles/870.bundle.323974846b6d45afb45e.js` - initiator
    - `cdn.segment.com/analytics-next/bundles/ajs-destination.bundle.35a8f6f19959bf2f455f.js` - initiator
    - `cdn.segment.com/analytics-next/bundles/schemaFilter.bundle.debb169c1abb431faaa6.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
