### ISSUE TITLE
Google sign-in/login breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#489]
- https://www.duolingo.com (last verified 2022-09-27)
  - going to login page then clicking on Google sign in option shows a network error "We're having trouble connecting..."
  - requests required:
    - `apis.google.com/js/platform.js` - gets rid of network error, initiator
    - `apis.google.com/_/scs/abc-static/_/js/<slash-params>` (`script`) - initiator
    - `accounts.google.com/o/oauth2/iframe` (`subdocument`) - initiator
    - `www.gstatic.com/_/mss/boq-identity/_/js/<slash-params>` (`script`)
    - `accounts.google.com/o/oauth2/iframerpc` (`xmlhttprequest`) - for account login to succeed
- https://www.frysfood.com/account/create/ (last verified 2022-09-27)
  - sign in with Google option is greyed out
  - requests required:
    - `apis.google.com/js/platform.js`
    - (same as for duolingo)
- https://rewards.nianticlabs.com/pokemongo/signin (last verified 2022-09-27)
  - sign in with Google option doesn't function
  - requests required:
    - (same as above)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
