### ISSUE TITLE
yottaa.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#492]
- https://www.ashleyfurniture.com/p/skempton_counter_height_dining_table_and_bar_stools_set_of_3/D394-113.html (last verified 2022-09-27)
  - product rating doesn't show
  - requests required:
    - `cdn.yottaa.com/rapid.min.7.1.1.js`
- https://www.northerntool.com/shop/tools/category_air-tools-compressors+air-compressor-parts-maintenance+air-compressor-pumps (last verified 2022-09-27)
  - product ratings don't show
  - requests required:
    - `cdn.yottaa.com/rapid.min.7.1.1.js`
- https://www.scheels.com/p/lee-perfect-powder-measure/73430790058.html (last verified: 2023-07-17)
  - Content for" Q & A", "Reviews", "What everyone's saying" does not show at the bottom of the page
  - Request required:
    - `rapid-cdn.yottaa.com/rapid/lib/ows8CdAyrC5lTw.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
