### ISSUE TITLE
googleapis.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#494]
- https://rewards.nianticlabs.com/pokemongo/signin (last verified 2022-09-27)
  - page loads blank
  - requests required:
    - `storage.googleapis.com/nianticweb-ark/ark/ark.js` - initiator
    - `storage.googleapis.com/nianticweb-ark/ark/p-860d4171.system.js` - initiator
    - `storage.googleapis.com/nianticweb-ark/ark/p-5460e349.system.js` - initiator
    - `storage.googleapis.com/nianticweb-ark/ark/p-40449657.system.entry.js` - initiator
    - `storage.googleapis.com/nianticweb-ark/ark/p-c6134cba.system.js`
    - `storage.googleapis.com/nianticweb-ark/ark/p-0ee46cb2.system.js`
    - `storage.googleapis.com/nianticweb-branding/niantic/niantic-horizontal-black.svg` - for logo

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
