### ISSUE TITLE
jimstatic.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#496]
- https://www.dk-arts.ch/ (last verified 2022-09-27)
  - header image doesn't render, content image (near end of page) doesn't render
  - requests required:
    - `assets.jimstatic.com/web.js.83719edc2d6bb8e2ecec.js`
  - clicking to manage cookies (in footer) does nothing
  - requests required:
    - `assets.jimstatic.com/cookieControl.js.0ca0e448676b02a16026.js`
- https://www.dicetilldawn.com/ (last verified 2022-09-27)
  - main content image doesn't render; layout issues
  - requests required:
    - `assets.jimstatic.com/web.js.83719edc2d6bb8e2ecec.js` - images
    - `assets.jimstatic.com/web.css.77cfc915fe222f26e0fee5315a170b55.css` - layout
    - `assets.jimstatic.com/bfa0b4b8941d94d9d6d8bc6fe31ef9f9.woff` - sharing icons
  - cookie prompt
    - `assets.jimstatic.com/cookieControl.js.0ca0e448676b02a16026.js` - for prompt to load

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
