### ISSUE TITLE
Fingerprinting breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#499]
Breakage due to fingerprinting protections.

## Canvas fingerprinting

- https://www.amtrak.com/home.html (last verified 2022-09-27) (**mitigated**)
  - searching for a route sometimes errors (may need VPN set to US. Example route: PHL -> BOS)
  - disabling `fingerprintingCanvas` mitigates
- https://www.walgreens.com/login.jsp (last verified 2022-09-29) (**mitigated**)
  - attempting to log in yields a service error
  - disabling `fingerprintingCanvas` mitigates
- https://www.mrporter.com/en-us/mens/product/gucci/clothing/short-sleeve-polo-shirts/logo-jacquard-webbing-trimmed-stretch-cotton-pique-polo-shirt/30629810019746329 (last verified 2023-02-07)
  - cannot add to cart
- https://id.manulife.ca/signin (last verified 2023-03-07)
  - first sign-in attempt gives a loading spinner which doesn't complete
  - Asana: https://app.asana.com/0/1200277586140538/1204104128662910/f
- https://www.chase.com/ (last verified 2023-03-29)
  - prevents login
  - Asana: https://app.asana.com/0/1163321984198618/1204290835495482/f
- https://github.com/duckduckgo/privacy-configuration/issues/788
- https://www.citi.com
  - reported login issues
  - Asana: https://app.asana.com/0/0/1204824872955331/f

**Comment by sammacbeth** [comment]
- https://www.godaddy.com/domainsearch/find (last verified 2023-02-24)
   - Gets stuck loading.
   - Disabling `fingerprintingCanvas` mitigates.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
