### ISSUE TITLE
captcha-delivery.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#501]
- https://www.sncf-connect.com/app/home/search (last verified 2022-09-29)
  - page does not load (note: region needs to be set to US)
  - requests required:
    - `ct.captcha-delivery.com/c.js` - initiator
    - `geo.captcha-delivery.com/captcha/` (`subdocument`)
    - `dd.prod.captcha-delivery.com/image/*` (`image`) - for captcha image
    - `static.captcha-delivery.com/captcha/assets/*` (`image`, `stylesheet`) - for additional icons, styling
    - `geo.captcha-delivery.com/captcha/check` (`xmlhttprequest`) - for validation of captcha

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
