### ISSUE TITLE
azure.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#504]
- https://ici.tou.tv/imalirijit/S01E01?lectureauto=1 (last verified 2022-09-30)
  - video doesn't load (just shows a spinner)
  - requests required:
    - (note: DRM may need to be enabled; region Canada)
    - `amp.azure.net/libs/amp/2.3.9/azuremediaplayer.min.js`
- https://www.greatbritishchefs.com/ (last verified 2022-09-30)
  - video at top of page doesn't load
  - requests required:
    - `amp.azure.net/libs/amp/2.3.9/azuremediaplayer.min.js`

**Comment by tagawa** [comment]
Closing this:
* The first URL is a broken link (page removed).
* The second URL is now working (video plays).
