### ISSUE TITLE
theplatform.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#512]
- https://www.nbcsports.com/video/event/2022-ironman-kona-world-championship (last verified 2022-10-10)
  - video doesn't load/play
  - requests required:
    - `pdk.theplatform.com/pdk6/next/pdk/player.js` - initiator
    - `link.theplatform.com/s/BxmELC/media/3YImumU7Q4Yy` (`xmlhttprequest`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
