### ISSUE TITLE
dynamicyield.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#535]
- https://seatosummit.com/ (last verified 2022-11-07)
  - page renders blank
  - requests required:
    - `cdn.dynamicyield.com/api/8778679/api_static.js`
- https://www.brooklinen.com/products/super-plush-robe (last verified 2023-02-10)
  - product section renders blank
  - https://app.asana.com/0/569473074191537/1203943764489730/f
  - requests required:
    - `cdn.dynamicyield.com/api/8768435/api_dynamic.js`
    - `cdn.dynamicyield.com/api/8768435/api_static.js`
- https://www.carters.com/carters-baby-boy-sets/V_1O917710.html (last verified 2023-03-07)
  - Asana: https://app.asana.com/0/1200277586140538/1204126774857666/f
  - Elements on product page appear greyed out (e.g., add to cart)
  - requests required:
    - `cdn.dynamicyield.com/api/8778518/api_static.js`
- https://id.asics.com/ (2023-05-30)
  - page loads blank
  - https://app.asana.com/0/0/1204670471114497/f
- https://www.otterbox.com/en-us/outdoor
  - "more products" button to display more items isn't responsive
  - https://app.asana.com/0/1200277586140538/1206183256363349/f
- https://www.michaelkors.com/michael-kors-collection/clothing/suiting-blazers/
  - filtering selections won't take effect (boxes won't check)
  - https://app.asana.com/0/1206670747178362/1207054592368290/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
