### ISSUE TITLE
duden.de breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#558]
- https://www.duden.de/rechtschreibung/Werbeblocker (last verified 2022-11-28)
  - Adblocker wall asking the user to disable their adblocker
  - requests required:
    - `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` - replace surrogate.

**Comment by GuiltyDolphin** [comment]
See also https://github.com/duckduckgo/privacy-configuration/issues/388

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
