### ISSUE TITLE
ticketmaster.com breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#575]
- https://auth.ticketmaster.com/as/authorization.oauth2 (last verified 2022-12-13)
  - Stuck on verification success page after login.
  - Protections need disabling: `fingerprintingTemporaryStorage`
- https://www.ticketmaster.com/ (last verified 2022-12-13)
  - Blank page
  - requests required:
    - `ticketmaster4.map.fastly.net/eps-d` - CNAME issue

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
