### ISSUE TITLE
element hiding breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#592]
General issue for breakage associated with element hiding.

- https://www.wunderground.com/wundermap (last verified 2023-02-22)
  - macOS desktop - weather-time navigation buttons don't show on map
- https://www.wiwo.de/ (last verified 2022-12-30)
   - element hiding triggers adblock wall.
- https://metro.co.uk/ (last verified 2023-01-02)
   - element hiding triggers adblock wall.
- https://www.blick.ch/ (last verified 2023-01-20)
   - element hiding triggers adblock wall.
- https://thechive.com/ (last verified 2023-03-28)
  - Asana: https://app.asana.com/0/1200277586140538/1204279037846765/f
  - adwall triggers
- https://www.bizjournals.com/ (last verified 2023-04-24)
  - Asana: https://app.asana.com/0/0/1204461066916740/f
  - element hiding triggers adblock wall.
- https://mail.google.com/mail/u/0/#inbox (2023-06-27)
  - Google pop-up is hidden which prevents interaction with the page
  - https://app.asana.com/0/1202100992740591/1204916213990978/f
- https://slate.com/ (last verified 2023-07-21)
  - Asana: https://app.asana.com/0/0/1205084127366554/f
  - element hiding triggers adblock wall.
- https://dailycaller.com/ (last verified 2023-07-21)
  - Asana: https://app.asana.com/0/0/1205084127366549/f
  - element hiding triggers adblock wall.
- [dailymail.co.uk](https://www.dailymail.co.uk/) (last verified 2023-07-26)
  - Asana: https://app.asana.com/0/0/1205143305294831/f
  - element hiding triggers adblock wall.
- [eltiempo.com](https://www.eltiempo.com/) (last verified 2023-07-26)
  - Asana: https://app.asana.com/0/0/1205143305294831/f
  - element hiding triggers adblock wall.
- [dailyherald.com](https://www.dailyherald.com/) (last verified 2023-07-26)
  - Asana: https://app.asana.com/0/0/1205143305294831/f
  - element hiding triggers adblock wall.
- [publico.es](https://www.publico.es/) (last verified 2023-07-26)
  - Asana: https://app.asana.com/0/0/1205143305294831/f
  - element hiding triggers adblock wall.
- [rawstory.com](https://www.rawstory.com/) (last verified 2023-07-26)
  - Asana: https://app.asana.com/0/0/1205143305294831/f
  - element hiding triggers adblock wall.
- [allgemeine-zeitung.de]( https://www.allgemeine-zeitung.de) (last verified 2023-07-28)
  - Asana: https://app.asana.com/0/0/1205143305294831/f
  - element hiding triggers adblock wall.
- https://guard.io/n/register (2023-08-03)
  - hides Google registration option
  - https://app.asana.com/0/1200277586140538/1205202206641451/f
- vinted.fr (2023-08-04)
  - some non-ad top-banners are partly covered
  - https://app.asana.com/0/1200277586140538/1205209107272083/f
- https://accounts.cleartax.in/v2 (2023-08-04)
  - Google create-account option doesn't show
  - https://app.asana.com/0/1200277586140538/1205212409436917/f
- [thehindu.com](https://www.thehindu.com/) (last verified 2023-08-24)
  - element hiding triggers adblock wall.
  - element hiding prevents user's interaction with google sign in pop up which thus triggers a repetive sign in notification by the site pointing to the "invisible" pop up
  - https://app.asana.com/0/1200277586140538/1205326380537950/f
- beverfood.com (last verified 2023-12-21)
  - element hiding triggers adblock wall.
  - https://app.asana.com/0/1200277586140538/1206200473867498/f
- thewindowsclub.com (last verified 2023-12-21)
  - element hiding creates empty ad space
  - https://app.asana.com/0/1200277586140538/1206176325132987/f
- newser.com (last verified 2024-03-03)
  - element hiding triggers a ad block banner
  - https://app.asana.com/0/72649045549333/1206743977003100/f

## Resolved

- https://manhwatop.com/manga/heavenly-eats/chapter-1/ (last verified 2023-03-03)
  - comic content is hidden
  - selector overmatching on `read-container`
- https://www.mangaread.org/manga/the-weakest-adventurer-becomes-the-strongest-in-the-world-thanks-to-perfect-loot-rolls/chapter-0/ (last verified 2023-03-03)
  - comic content is hidden
  - selector overmatching on `read-container`
- https://www.politico.com/news/magazine/2022/12/15/national-archives-jfk-files-00074041 (last verified 2023-04-27)
  - article appears blank (elements are squashed to top)
- https://andzwa.medium.com/why-the-google-layoffs-are-about-personal-ambition-and-poor-leadership-817236947368 (last verified 2023-04-27)
  - `elementHiding` causes the search bar to become hidden
- https://www.dallasnews.com/ (last verified 2023-04-27)
  - Asana: https://app.asana.com/0/1200277586140538/1204125636489262/f
  - Featured bar is hidden, top layout appears squashed
- https://manhwascan.net/webtoon/where-is-my-hammer/chapter-15/ (last verified 2022-04-27)
   - comic content is hidden.

**Comment by sammacbeth** [comment]
- https://manhwascan.net/webtoon/where-is-my-hammer/chapter-15/ (last verified 2022-12-21)
   - comic content is hidden.

**Comment by sammacbeth** [comment]
- https://www.wiwo.de/ (last verified 2022-12-30)
   - element hiding triggers adblock wall.

**Comment by sammacbeth** [comment]
- https://metro.co.uk/ (last verified 2023-01-02)
   - element hiding triggers adblock wall.

**Comment by sammacbeth** [comment]
- https://www.blick.ch/ (last verified 2023-01-20)
   - element hiding triggers adblock wall.

**Comment by dharb** [comment]
__Incorporated into main description__
- https://www.bizjournals.com/ (last verified 2023-04-24)
  - element hiding triggers adblock wall.

**Comment by icodebyamanda** [comment]
**Incorporated into main description**

- https://slate.com/ (last verified 2023-07-21)
    - element hiding triggers adblock wall.

**Comment by icodebyamanda** [comment]
**Incorporated into main description**

- https://dailycaller.com/ (last verified 2023-07-21)
  - element hiding triggers adblock wall.

**Comment by icodebyamanda** [comment]
Incorporated into main description

- [thehindu.com](https://www.thehindu.com/) (last verified 2023-08-24)
  - element hiding triggers adblock wall.
  - element hiding prevents user's interaction with google sign in pop up which thus triggers a repetive sign in notification by the site pointing to the "invisible" pop up

**Comment by icodebyamanda** [comment]
**Incorporated into main description**

- [wildrivers.lostcoastoutpost.com/](wildrivers.lostcoastoutpost.com/) (last verified 2023-08-25)
  - element hiding triggers adblock wall.

**Comment by icodebyamanda** [comment]
Incorporated into main description

- beverfood.com (last verified 2023-12-21)
  - element hiding triggers adblock wall.

**Comment by icodebyamanda** [comment]
Incorporated into main description

- thewindowsclub.com (last verified 2023-12-21)
  - element hiding creates empty ad space

**Comment by icodebyamanda** [comment]
Incorporated into main description

- newser.com (last verified 2024-03-03)
  - element hiding triggers a ad block banner

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
