### ISSUE TITLE
digid.nl breakage

### ISSUE THREAD

**Issue by muodov** [duckduckgo/privacy-configuration#602]
digid.nl (last verified 2023-01-02)
- Site refuses to redirect to the native app in Android and iOS browsers.
- Changing our user-agent back to webview defaults fixes the issue

**Comment by rhodessteve** [comment]
This is still annoying, and its easier to just use Chrome browser than switch user agent, which obviously i'd rather not do. This works in other browsers but not DDG, please fix.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
