### ISSUE TITLE
whatsapp.com QR code doesn't show

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#620]
On https://web.whatsapp.com/ (Firefox), the QR code doesn't show and instead there is an indefinite loading spinner.

Disabling GPC consistently mitigates and allows the QR code to load.

- last verified 2023-01-16

Asana: https://app.asana.com/0/1200223097357040/1203710812458808/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
