### ISSUE TITLE
spot.im comments widget breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#622]
- https://www.foxnews.com/politics/jim-jordan-fires-back-white-house-biden-document-fight-republicans-want-fair-treatment (last verified 2023-01-17)
  - Comments widget is not loaded
  - requests required:
    - `*.spot.im/` - required for the comments widget

**Comment by sammacbeth** [comment]
- https://finance.yahoo.com/quote/AMWL/community (last verified 2023-01-18)
-

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
