### ISSUE TITLE
restoredrepublic.co breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#631]
- https://restoredrepublic.co/biden-doj-actively-working-to-reimpose-mask-mandates-on-flights/ (last verified 2023-01-19)
  - Videos do not load
  - requests required:
    - `https://rumble.com/j/p/ui.r2.js`
- https://makegreatnow.com/the-storm-is-coming-judgement-day/ (last verified 2023-01-19) Same as above
- https://elijahstreams.com/watch/watch.php?ID=1263
- https://funker530.com/video/rifleman-shoots-drone-munition-out-of-the-sky/
- https://m.beforeitsnews.com/prophecy/2023/01/new-juan-o-savin-nino-huge-some-very-good-news-2537556.html

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
