### ISSUE TITLE
target.com breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#635]
- target.com (last verified 2023-01-19)
  - Login is broken on android
  - requests required:
    - `https://assets.targetimg1.com/ssx/ssx.mod.js` (CNAME maps to `target-opus.map.fastly.net`).
    - ...
  - ...
- ...

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
