### ISSUE TITLE
challenges.cloudflare.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#641]
- https://thetrackernetwork.com/auth/login?domain=thetrackernetwork.com (last verified 2023-01-25)
  - captcha doesn't show, auth fails
- https://givebutter.com/login (last verified 2023-01-25)
  - sign in button shows loading spinner, cannot be clicked
- https://dl-protect.net/ (last verified 2023-01-25)
  - captcha doesn't show, can't proceed to generate short links

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
