### ISSUE TITLE
UsabalityHub "unsupported browser" error on Android

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#654]
URL: https://app.usabilityhub.com/users/sign_up
On Android, loading the page redirects to https://app.usabilityhub.com/unsupported_browser with an unsupported browser message.

Asana: https://app.asana.com/0/1200277586140538/1203770817820904/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
