### ISSUE TITLE
UserAgent breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#667]
The following collects user agent issues found across sites:

- `zalando.fr` (2024-02-06)
  - https://app.asana.com/0/1200277586140538/1206524363702250/f
  - error message on login, prevents login
  - macOS

### AppId

- https://www.republicservices.com/ (last verified 2023-02-08)
  - iOS: Menu appears broken (bullet points with missing content)
  - Asana: https://app.asana.com/0/1200223097357040/1203628766050990/f
- https://www.tiktok.com/ (last verified 2023-02-13)
  - Android/iOS: Videos on main page don't play
  - Asana: https://app.asana.com/0/1200277586140538/1203955580313656/f
- https://www.sme.sk/ (last verified 2023-03-07)
  - Android, iOS: main images don't render
  - Asana: https://app.asana.com/0/1200223097357040/1204077330782064/f
- https://wykop.pl/ (2023-05-30)
  - Android: malformed layout
  - Asana: https://app.asana.com/0/1200277586140538/1204700701607234/f
- https://plus.fifa.com/ (2023-08-15)
  - Android: site redirects to "unsupported browser" page, which doesn't render correctly
  - https://app.asana.com/0/1200277586140538/1205271473837648/f

### Webview version

- https://steamdb.info/sales/history/ (last verified 2023-02-08)
  - Android: verification hangs and the main site does not load
  - Asana: https://app.asana.com/0/1200277586140538/1203770817820916/f

Tags: user agent, useragent

**Comment by sammacbeth** [comment]
- https://signup.unclaimedmoneyinfo.com/ (last verified 2023-04-25)
  - Android: redirection is broken.
  - Asana: https://app.asana.com/0/1200277586140538/1204454663399122/f

**Comment by bwaresiak** [comment]
- https://wykop.pl (last verified 2023-05-30)
  - iOS: Layout is broken.
  - Asana: https://app.asana.com/0/1200277586140538/1204700701607234/f

**Comment by dharb** [comment]
- intymna.pl (last verified 2023-07-28)
 - iOS & Android: returns 403 error

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
