### ISSUE TITLE
iesnare breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#669]
The following sites encountered adwalls/warnings when attempting to submit reviews. Unblocking `mpsnare.iesnare.com/snare.js` mitigates.
- https://www.canadiantire.ca/en/pdp/husqvarna-lc-151-push-lawn-mower-20-in-0601543p.html (last verified 2023-02-08)
- https://www.diy.com/departments/28mm-matt-dark-grey-stone-effect-laminate-particle-board-post-formed-kitchen-worktop-l-2400mm/3663602636175_BQ.prd (last verified 2023-02-08)
- https://www.rei.com/product/191687/on-cloudflow-road-running-shoes-womens (last verified 2023-02-08)
- https://www.uptontea.com/formosa-oolong-tea/taiwan-loose-leaf-oolong-tea/p/V00262/ (last verified 2023-02-08)

Additional breakage:

- https://www.ups.com/lasso/forgot (last verified 2023-02-08)
  - after attempting to proceed when entering username/e-mail for forgetten password, there is an "error during processing"
  - requests required:
    - `mpsnare.iesnare.com/snare.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
