### ISSUE TITLE
cedexis breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#675]
- https://www.linkedin.com/ (last verified 2023-02-10)
  - Android: there is an "open in app / continue in browser" popup, but the buttons don't work, preventing access to the site
    - https://app.asana.com/0/1200277586140538/1203944030995365/f
  - requests required:
    - `cdx.cedexis.net` (unknown path)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
