### ISSUE TITLE
loggly breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#681]
- https://www.rte.ie/player/ (last verified 2023-02-13)
  - page renders blank (player doesn't show)
  - https://app.asana.com/0/1200223097357040/1203955578133416/f
  - requests required:
    - `cloudfront.loggly.com/js/loggly.tracker-2.1.min.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
