### ISSUE TITLE
quantcast breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#687]
- https://www.express.co.uk/news/uk/1735463/nicola-bulley-disappearance-search-expert-peter-faulding (last verified 2023-02-16)
  - comments don't show
  - requests required:
    - https://cmp.quantcast.com/choice/JYWDqeLS64fbt/www.express.co.uk/choice.js
    - element hiding is also required to be disabled (bug). #592

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
