### ISSUE TITLE
GPC Breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#700]
Breakage due to the `gpc` protection.

- https://www.duluthtrading.com/s/DTC/womens-folklore-flannel-shirt-56461.html (last verified 2023-02-22)
  - selecting product colours has no effect
- https://www.boston.com/news/local-news/2023/07/26/over-500-evacuated-from-boston-hotel-after-co-detected (2023-07-28)
  - comments section doesn't show
- https://www.eventbrite.com/account-settings/linked-accounts (2023-07-31)
  - login popups don't show when using the Facebook and Google sign-in options

See also:
- https://github.com/duckduckgo/privacy-configuration/issues/644
- https://github.com/duckduckgo/privacy-configuration/issues/620

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
