### ISSUE TITLE
ShortPixel Adaptive Images WordPress plugin breakage

### ISSUE THREAD

**Issue by pdobrescu** [duckduckgo/privacy-configuration#712]
- [https://www.siamkitchen.nl](https://www.siamkitchen.nl/) (last verified 2023-02-25)
  - All websites using the [ShortPixel Adaptive Images](https://wordpress.org/plugins/shortpixel-adaptive-images/) WordPress plugin aren't displaying images because the main script of the plugin - `https://cdn.shortpixel.ai/assets/js/bundles/spai-lib-bg.1.1.min.js` - is blocked.
  - requests required:
    - `https://cdn.shortpixel.ai/assets/js/bundles/spai-lib-bg.1.1.min.js` (`JS`) - should be unlocked

Thank you!

**Comment by GuiltyDolphin** [comment]
Thanks @pdobrescu

I checked some sites and managed to reproduce breakage on the following:
- https://www.alkaway.com.au/product-category/molecular-hydrogen-products/ (images don't show)
- https://www.storerboatplans.com/ (images blurred)
- https://futabausa.com/product-category/systems/air-systems/ (images blurred)

In each case unblocking `cdn.shortpixel.ai/assets/js/bundles/spai-lib-bg.1.1.min.js` resolved the issue.

I'll follow up with a mitigation.

**Comment by pdobrescu** [comment]
this is great, thanks a lot @GuiltyDolphin! from what I tested, it seems to be resolved, so thank you very much for taking care of this! 🙏
