### ISSUE TITLE
Twitter/tweet breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#717]
Breakage related to twitter (e.g., broken tweets):

- https://notthebee.com/article/our-country-is-gone-marjorie-taylor-greene-says-she-was-just-attacked-at-a-restaurant (last verified 2023-02-28)
  - some tweets don't load (show a timeout)
  - requests required:
    - `platform.twitter.com/embed/embed*`
- https://www.stanleycupofchowder.com/2023/2/22/23609719/morning-skate-pending-bruins-trade-rumors-vladislav-gavrikov-bruins-kraken-seattle-road-trip (last verified 2023-02-28)
  - tweets show in text mode, which prevents videos showing in tweets
  - requests required:
    - `platform.twitter.com/embed/embed*`
- https://www.reddit.com/r/nfl/ (last verified 2023-02-28)
  - tweets fail to load
  - requests required:
    - `platform.twitter.com/embed/embed*`
- https://www.woot.com/ (last verified 2024-04-10)
  - "Latest tweets" fail to load
  - requests required:
    - `platform.twitter.com/_next/static`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
