### ISSUE TITLE
strava.com breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#748]
- https://www.strava.com/dashboard (last verified 2023-03-21)
  - Dashboard contents do not load.
  - requests required:
    - `https://d3nn82uaxijpm6.cloudfront.net/packs/js/10603-0d2522db11b3d61a86c0.js` (`script`) - Script on Strava's CDN required to load the page correctly.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
