### ISSUE TITLE
iheart.com  breakage

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#760]
- https://www.coasttocoastam.com/show/2023-03-21-show/ (last verified 2023-03-23)
  - Breaking embedded audio from iheart.com
  - requests required:
    - `iheart.com` (`all types`) - <additional description>
    - ...
  - ...
- ...

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
