### ISSUE TITLE
viafoura.net comment sections breakage

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#763]
- Lots of broken comment sections (last verified 2023-03-24)
  - https://www.mirror.co.uk/news/uk-news/breaking-brit-dies-listeria-outbreak-29543733
  - https://www.telegraph.co.uk/business/2023/03/23/bank-england-raises-interest-rates-425pc-warns-pain/
  - requests required:
    - `viafoura.net` 
    - ...
  - ...
- ...

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
