### ISSUE TITLE
Tracker breakage: bing.com/th

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#765]
- start.gg (last verified 2023-08-09)
  - broken images
  - requests required:
    - `bing.com/th` (`image`) 
- drudgereport.com (last verified 2023-08-09)
  - broken images
  - requests required:
    - `bing.com/th` (`image`)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
