### ISSUE TITLE
connatix.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#768]
- https://www.accuweather.com/ (last verified 2023-03-27)
  - weather radar doesn't show (also in weather articles/pages)
  - Asana: https://app.asana.com/0/1200277586140538/1204268603385663/f
  - requests required:
    - `connatix.com/` (various requests)
- https://www.dailymail.co.uk/tvshowbiz/article-11993393/Lily-Allen-joins-husband-David-Harbour-Garden-Dreams-Talent-NY.html (last verified 2023-04-20)
  - "top stories" video doesn't show (blank space instead)
  - https://app.asana.com/0/1200289808319188/1204438236581193/f
  - requests required:
    - `connatix.com/` (various requests)
- https://www.huffpost.com/entry/chris-christie-trump-preview_n_65040b4ee4b0f5bc64a64906
  - main video doesn't play
  - couple of subdomains (like cdn. and video.) needed to be unblocked

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
