### ISSUE TITLE
cloudfront breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#774]
-  https://www.sigalert.com/ (last verified 2023-03-28)
  - map (main content) doesn't show
  - requests required:
    - `cdn-static.sigalert.com/240/*` cnames to `d2s6j0ghajv79z.cloudfront.net`
- https://nuhuskies.com/news/2023/11/11/mens-rowing-huskies-win-foot-of-the-charles-taking-first-and-second.aspx (last verified 2023-11-13)
  - related videos don't load
  - requests required:
    - `dbukjj6eu5tsf.cloudfront.net/assets.sidearmsports.com/common/js/20170825/video.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
