### ISSUE TITLE
basspro.com login breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#783]
- https://www.basspro.com/shop/en (last verified 2023-03-30)
  - clicking to log in causes an overlay which prevents interaction, and the login sidebar does not appear
  - Asana: https://app.asana.com/0/1200277586140538/1204297046405976/f
  - requests required:
    - `kampyle.com` (various requests/subdomains)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
