### ISSUE TITLE
financialpost login broken

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#785]
- https://financialpost.com/sign-in/ (last verified 2023-03-30)
  - clicking to login has no effect
  - Asana: https://app.asana.com/0/1199178362774117/1203487739579793/f
  - requests required:
    - `ak.sail-horizon.com/spm/spm.v1.min.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
