### ISSUE TITLE
bankofamerica.com breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#798]
- https://about.bankofamerica.com/en/making-an-impact/museums-on-us-find-locations-map (last verified 2023-04-03)
  - Map doesn't load.
  - requests required:
    - `https://target.bankofamerica.com/m2/bankofamerica/mbox/json` - CNAMEd to `https://bankofamerica.tt.omtrdc.net/`
    - `tags.tiqcdn.com/utag/bofa/main/prod/utag.sync.js`
  - ...
- ...

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
