### ISSUE TITLE
cigna.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#820]
- https://my.cigna.com/web/public/guest (last verified 2023-04-06)
  - Login broken
  - requests required:
    - `https://cigna.sc.omtrdc.net/public/digital-experience/js/common.js`
    - `https://proxy-mycigna-prod-678433465.us-east-1.elb.amazonaws.com/public/digital-experience/js/common.js`
  - ...
- ...

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
