### ISSUE TITLE
virginatlantic.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#826]
- https://www.virginatlantic.com/complete-purchase/trip-summary?... (last verified 2023-10-04)
  - page stuck in loading state
  - requests required:
    - `https://tms.virginatlantic.com/vaa/Bootstrap.js` CNAME'd to `https://vaa.edge.nc0.co/`
    - ...
  - ...
- ...

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
