### ISSUE TITLE
yottaa breakage

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/privacy-configuration#830]
- https://www.northerntool.com/products/northstar-gas-wet-steam-hot-water-pressure-washer-3000-psi-4-0-gpm-honda-engine-157310(last verified 2023-04-11)
  - no page content
  - requests required:
    - `yottaa.com/rapid.security.min` 
    - ...
  - ...
- ...

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
