### ISSUE TITLE
cnn.com video breakage

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#837]
- [cnn.com](https://edition.cnn.com/videos/politics/2023/04/14/barr-trump-mar-a-lago-classified-documents-probe-collins-intv-pt-vpx.cnn) (last verified 2023-04-14)
  - Video button isn't showing on Chrome

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
