### ISSUE TITLE
rocketnews24 images don't render

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#846]
- https://rocketnews24.com/ (last verified 2023-04-18)
  - Asana: https://app.asana.com/0/1200277586140538/1204378805271407/f
  - main article images don't render
  - requests required:
    - various doubleclick and googlesyndication requests, e.g.,
      - `securepubads.g.doubleclick.net/tag/js/gpt.js`
      - `securepubads.g.doubleclick.net/pagead/ppub_config`
      - `securepubads.g.doubleclick.net/pagead/managed/`
      - `securepubads.g.doubleclick.net/gampad/ads`
      - `pagead2.googlesyndication.com/getconfig/sodar`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
