### ISSUE TITLE
inquirer.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#869]
- https://www.inquirer.com/politics/election/mayors-race-jeff-brown-super-pac-agreement-ethics-board-coordination-20230424.html (last verified 2023-04-24)
  - Header hidden on article pages
  - requests required:
    - `https://cdn.speedcurve.com/js/lux.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
