### ISSUE TITLE
survey.walmart.com breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#882]
- https://survey.walmart.com/ (last verified 2023-04-27)
  - Page does not load
  - requests required:
    - `https://cdn.medallia.com/react-surveys/*` (`script` and `stylesheet`)
    - `https://global.cdn.survey.medallia.com/`
    - ...
  - ...
- ...

**Comment by GuiltyDolphin** [comment]
Closing in favour of #884.
