### ISSUE TITLE
medallia.com breakage

### ISSUE THREAD

**Issue by sammacbeth** [duckduckgo/privacy-configuration#884]
Surveys using medallia.com do not load.

- Likely same-entity (#460)
  - https://survey.medallia.ca/?McD-GSS-FeedlessSurvey&lang=fr_CA (last verified 2023-04-27)
  - https://survey.medallia.com.au/bws (last verified 2023-04-27)
- https://survey.airnewzealand.co.nz/?feedless-myvoice-102beea700406c3dc82d18785f91f4cf (last verified 2023-04-27)
- https://subwaylistens.com/?feedless-subwaylistens-17e0518717ba91216b85d22a9532103e (last verified 2023-04-27)
- #882 

Requests required:
 - `cdn.medallia.com/react-surveys/*`
 - `survey.medallia.com/`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
