### ISSUE TITLE
Liveperson chat breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#900]
- https://www.siriusxm.com/contact-us (last verified 2023-05-08)
  - "Chat now" button appears faded and cannot be clicked
  - requests required:
    - `liveperson.com` (various)
    - `liveperson.net` (various)
    - `lpsnmedia.net` (various)
- https://support.spotify.com/us/contact-spotify-support (last verified 2023-05-08)
  - chat section appears greyed out and cannot be interacted with
  - requests required:
    - `liveperson.net` (various)
    - `lpsnmedia.net` (various)
- https://ee.co.uk/contact-ee/account-billing/mobile (last verified 2023-05-08)
  - chat button doesn't show
  - requests required:
    - `liveperson.net` (various)
    - `lpsnmedia.net` (various)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
