### ISSUE TITLE
cookielaw breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#914]
- https://www.mopar.com/en-us/sign-in.html (last verified 2023-05-10)
  - sign in box doesn't show
- https://www.jumbo.com/ (last verified 2023-05-10)
  - login area doesn't show
- https://www.reuters.com/video/ (last verified 2023-05-10)
  - video doesn't load or show

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
