### ISSUE TITLE
optimizely breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#916]
- https://www.nike.com/au/launch (2023-05-10)
  - page doesn't render
  - `cdn.optimizely.com/datafiles/[a-Z0-9]+.json/tag.js`
- https://www.fedex.com/profile/#/login (2023-05-16)
  - 2FA toggle doesn't work.
  - `cdn.optimizely.com/datafiles/[a-Z0-9]+.json`

**Comment by sammacbeth** [comment]
- https://www.fedex.com/profile/#/login
  - 2FA toggle doesn't work.
  - `cdn.optimizely.com/datafiles/[a-Z0-9]+.json`

**Comment by sammacbeth** [comment]
- https://my.zipcar.com/search (2024-04-23)
   - Available cars are not loaded.
   - https://cdn.optimizely.com/js/271989291.js

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
