### ISSUE TITLE
aticdn.net breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#919]
- https://yourstory.com/ (2023-05-11)
  - page loads blank
  - `tag.aticdn.net/piano-analytics.js`
- https://ticket.toureiffel.paris/en (2023-05-11)
  - clicking "continue without saving" on cookie banner has no effect
  - `tag.aticdn.net/piano-analytics.js`
- https://www.sport1.de (2023-05-29)
  - hard adwall prevents using site
  - https://app.asana.com/0/1200277586140538/1204693862606177/f
  - `tag.aticdn.net/604311/smarttag.js`
- https://www.rte.ie/sport/hurling/2023/0529/1386276-can-we-play-you-every-week-wexford-kilkenny-conundrum/ (2023-05-29)
  - video does not play (clicking play button has no effect)
  - `tag.aticdn.net/592983/smarttag.js`

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
