### ISSUE TITLE
GTM breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#921]
Breakage from `googletagmanager.com/gtm.js`:

- https://www.aeromexico.com/en-us (2023-05-11, 2023-06-01)
  - cookie banner does not dismiss when "Accept" is clicked, preventing interaction with the page
- https://www.al.com/contributor/ (2023-05-11, 2023-06-01)
  - page gets stuck on loading icon, does not proceed
- https://www.bbcgoodfood.com/recipes/thai-green-chicken-curry (2023-06-01)
  - various elements overlap one another (layout issues)
- https://www.fortress.com.hk/en/contact_us (2023-06-12)
  - live chat widget doesn't show
  - https://www.reddit.com/r/uBlockOrigin/comments/141ixy9/comment/jn0v9iw
- https://www.garnethill.com/womens-fashion/coats-jackets/ (2023-06-20)
  - clicking on product images does not navigate to product page

Some entries in the following issues:
- https://github.com/duckduckgo/privacy-configuration/issues/348
- https://github.com/duckduckgo/privacy-configuration/issues/355
- https://github.com/duckduckgo/privacy-configuration/issues/410

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
