### ISSUE TITLE
fedex.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#927]
https://www.fedex.com/fedextrack (2023-05-12)
- there appear to be issues with Fedex shipment tracking when the extension is present. We've narrowed this down to the following protections which may be leading to the issue:
  - `fingerprintingCanvas`
  - `fingerprintingHardware`
  - `fingerprintingScreenSize`
  - `fingerprintingTemporaryStorage`

- fedex.com reports unsupported browser on Android (2023-08-03)
  - requires omit app + webview version

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
