### ISSUE TITLE
learning.edx.org breakage

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#934]
- https://learning.edx.org (last verified 2023-05-16)
  - Loading https://learning.edx.org/ https://learning.edx.org/course/course-v1:HarvardX+CS50+X/block-v1:HarvardX+CS50+X+type@sequential+block@a8730f85a9a94d41a784a58c4b6d8bdc
  - Reported here: https://www.reddit.com/r/duckduckgo/comments/13ijt89/potential_bug_in_ddg_privacy_essentials_firefox/
  - Reproduced in in the extensions

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
