### ISSUE TITLE
xcelenergy.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#941]
- https://my.xcelenergy.com/MyAccount/XE_Login?template=XE_MA_Template (last verified 2023-05-19)
  - referrer trimming is causing the sign in form to not appear - a `postMessage` error is thrown when the subdomain is removed from referrer.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
