### ISSUE TITLE
Amazon prime breakage

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#943]
- [amazon.co.uk/mc](https://www.amazon.co.uk/mc?ref_=ya_d_c_prime) (last verified 2023-05-21)
  - Page isn't loading properly, all of the content is missing
  - requests required:
    - `*.prime.dev` (`js`)
- https://www.amazon.de/gp/primecentral (last verified 2023-07-27)

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
