### ISSUE TITLE
Click to Load YouTube breakage on khanacademy.org

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#945]
- https://www.khanacademy.org/science/ap-chemistry-beta/x2eef969c74e0d802:atomic-structure-and-properties/x2eef969c74e0d802:composition-of-mixtures/v/worked-example-calculating-mass-of-substance-in-mixture (last verified 2023-05-22)
  - Some lessons on khanacademy.org use embedded YouTube videos. The website detects if those videos are blocked, and redirects to an alternative video or an error page if no alternatives are available.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
