### ISSUE TITLE
Click to Load YouTube breakage on music websites

### ISSUE THREAD

**Issue by kzar** [duckduckgo/privacy-configuration#950]
- https://www.last.fm/music , https://www.beatsense.com/gazetowave , https://www.discogs.com/release/1267265-DSwing-Featuring-Diane-Charlemagne-Take-Me (last verified 2023-05-24)
  - These music websites are tightly integrated with YouTube and unfortunately break or are hard to use when Click to Load YouTube is enabled.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
