### ISSUE TITLE
wunderground.com breakage

### ISSUE THREAD

**Issue by dharb** [duckduckgo/privacy-configuration#956]
- https://www.wunderground.com/video/top-stories/rain-through-holiday-weekend-along-southeast-coast (last verified 2023-05-25)
  - Video player doesn't load
  - requests required:
    - `https://securepubads.g.doubleclick.net/pagead/ppub_config`
  - https://app.asana.com/0/1200277586140538/1204681199972202

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
