### ISSUE TITLE
foxnews adwall

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#965]
- foxnews.com (2023-05-26)
  - https://app.asana.com/0/1200277586140538/1204683037000654/f
  - site appears to randomly generate ad selectors, some of which are affected by element hiding, and this leads to a (somewhat inconsistent) adwall

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
