### ISSUE TITLE
lowes.com breakage

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#991]
- [lowes.com](https://www.lowes.com/) (last verified 2023-06-13)
  - Search is not working

<img width="697" alt="image" src="https://github.com/duckduckgo/privacy-configuration/assets/338988/f18f6eb5-d06c-46a3-a00d-dc73f4e4db2f">

Asana: https://app.asana.com/0/1200277586140538/1204814667758853/f

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
