### ISSUE TITLE
amazon.com breakage

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/privacy-configuration#995]
- amazon.com (last verified 2023-06-13)
  - Spinner seen on page (https://www.amazon.co.uk/gcx/Gifts-for-everyone/gfhz/) caused by runtime checks
  - As we've had other breakage reports for amazon, disabling for now out of precaution as we investigate more.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
